class AppLocalizations {
  AppLocalizations(this.language);

  final String language;

  static const supportedLanguages = [
    'English',
    'Tamil',
    'Telugu',
    'Kannada',
    'Malayalam',
    'Hindi',
    'Marathi',
    'Urdu',
    'French',
    'Japanese',
  ];

  static final _translations = <String, Map<String, String>>{
    'Tamil': {
      'Caregiver Access': 'பராமரிப்பாளர் அணுகல்',
      'Continue': 'தொடரவும்',
      'Create account': 'கணக்கை உருவாக்கு',
      'Home': 'முகப்பு',
      'SOS': 'SOS',
      'Health': 'உடல்நலம்',
      'Emergency status': 'அவசர நிலை',
      'Stable': 'நிலையானது',
      'Emergency SOS': 'அவசர SOS',
      'Today\'s health snapshot': 'இன்றைய உடல்நல சுருக்கம்',
      'Care route': 'சிகிச்சை வழி',
      'Medicine reminder': 'மருந்து நினைவூட்டல்',
      'AI Health Assistant': 'AI உடல்நல உதவியாளர்',
      'Caregiver settings': 'பராமரிப்பாளர் அமைப்புகள்',
      'Sign out': 'வெளியேறு',
      'Medicine name': 'மருந்தின் பெயர்',
      'Time': 'நேரம்',
      'Submit reminder': 'நினைவூட்டலைச் சமர்ப்பி',
      'Enter medicine and time': 'மருந்து மற்றும் நேரத்தை உள்ளிடவும்',
      'Reminder saved': 'நினைவூட்டல் சேமிக்கப்பட்டது',
      'Delete reminder': 'நினைவூட்டலை நீக்கு',
      'Get guidance': 'வழிகாட்டுதலைப் பெறு',
      'Blood group': 'இரத்த வகை',
      'Allergies': 'ஒவ்வாமைகள்',
      'Contact': 'தொடர்பு',
      'Voice input': 'குரல் உள்ளீடு',
      'Guidance summary': 'வழிகாட்டுதல் சுருக்கம்',
      'Send SOS Now': 'இப்போது SOS அனுப்பு',
      'Nearby healthcare services': 'அருகிலுள்ள சுகாதார சேவைகள்',
      'Save record': 'பதிவைச் சேமி',
      'Saving...': 'சேமிக்கிறது...',
      'Today': 'இன்று',
      'Weight': 'எடை',
      'Height': 'உயரம்',
      'Not set': 'அமைக்கப்படவில்லை',
      'None': 'இல்லை',
      'Screen time today': 'இன்றைய திரை நேரம்',
      'hours': 'மணி',
      'Emergency contact': 'அவசர தொடர்பு',
      'Edit emergency contact': 'அவசர தொடர்பைத் திருத்து',
      'Call Emergency Contact': 'அவசர தொடர்பை அழை',
      'Enter data': 'தரவை உள்ளிடு',
      'Register as Donor': 'தானம் செய்பவராக பதிவு செய்யுங்கள்',
      'Register': 'பதிவு செய்',
      'Available Donors': 'கிடைக்கும் தானம் செய்பவர்கள்',
      'Blood Donation': 'இரத்த தானம்',
      'Describe your symptoms and Medly will suggest basic guidance and urgency levels.':
          'உங்கள் அறிகுறிகளை விவரிக்கவும்; Medly அடிப்படை வழிகாட்டுதலையும் அவசர நிலைகளையும் பரிந்துரைக்கும்.',
      'Describe your symptoms or ask for first aid guidance':
          'உங்கள் அறிகுறிகளை விவரிக்கவும் அல்லது முதலுதவி வழிகாட்டுதலைக் கேட்கவும்',
      'Map': 'வரைபடம்',
      'Find nearby care': 'அருகிலுள்ள சிகிச்சையைக் கண்டறியுங்கள்',
      'Distance': 'தூரம்',
      'ETA': 'எதிர்பார்க்கும் நேரம்',
      'Stop Navigation': 'வழிசெலுத்தலை நிறுத்து',
      'Start Navigation': 'வழிசெலுத்தலைத் தொடங்கு',
      'Following your location...': 'உங்கள் இருப்பைப் பின்தொடர்கிறது...',
      'Daily Exercises': 'தினசரி உடற்பயிற்சிகள்',
      'Based on your conditions': 'உங்கள் நிலைகளின் அடிப்படையில்',
      'All exercises done today! Keep the streak alive tomorrow!': 'இன்று அனைத்து உடற்பயிற்சிகளும் முடிந்தது! நாளை தொடர்ந்து செய்யுங்கள்!',
      'Connect Smartwatch': 'ஸ்மார்ட் வாச்சை இணைக்கவும்',
      'Find Hospitals & Pharmacies Near You': 'உங்கள் அருகில் மருத்துவமனைகள் & மருந்தகங்களைக் கண்டறியுங்கள்',
      'Walking': 'நடைபயிற்சி',
      'Stretching': 'நீட்சிப்பயிற்சி',
      'Deep Breathing': 'ஆழ்ந்த சுவாசம்',
      'Brisk Walking': 'வேகமான நடைபயிற்சி',
      'Gentle Walking': 'மெதுவான நடைபயிற்சி',
      'Meditation': 'தியானம்',
      'Yoga': 'யோகா',
      'Yoga Stretching': 'யோகா நீட்சிப்பயிற்சி',
      'Cycling': 'சைக்கிள் ஓட்டுதல்',
      'Jumping Jacks': 'ஜம்பிங் ஜாக்ஸ்',
      'Streak': 'தொடர்',
      'days': 'நாட்கள்',
      "day streak! Champions don't quit!": 'நாள் தொடர்! சாம்பியன்கள் விடமாட்டார்கள்!',
      "days strong! Don't break the chain!": 'நாட்கள் வலுவாக! சங்கிலியை துண்டிக்காதீர்கள்!',
      "days! Almost a week - keep pushing!": 'நாட்கள்! ஒரு வாரம் கிட்டத்தட்ட - தொடருங்கள்!',
      "day streak started! Build the habit!": 'நாள் தொடர் தொடங்கியது! பழக்கத்தை உருவாக்குங்கள்!',
      'done today. Start your streak now!': 'இன்று முடிந்தது. உங்கள் தொடரை இப்போது தொடங்குங்கள்!',
      'Refresh location': 'இருப்பைப் புதுப்பி',
      'Show Route on Map': 'வரைபடத்தில் வழியைக் காட்டு',
      'All': 'அனைத்தும்',
      'Dark Mode': 'இருண்ட பயன்முறை',
      'Dark theme active': 'இருண்ட தீம் செயலில் உள்ளது',
      'Light theme active': 'ஒளி தீம் செயலில் உள்ளது',
      'Set Step Goal': 'படி இலக்கை அமைக்கவும்',
      'steps': 'படிகள்',
      'Cancel': 'ரத்துசெய்',
      'Save': 'சேமி',
      'day streak': 'நாள் தொடர்',
      'best': 'சிறந்த',
      'Retry — Get My Location': 'மீண்டும் முயற்சி — என் இருப்பைப் பெறு',
      'Getting your GPS location...': 'GPS இருப்பைப் பெறுகிறது...',
      'Please wait while we find where you are': 'நீங்கள் எங்கே இருக்கிறீர்கள் என்று கண்டறியும் வரை காத்திருங்கள்',
      'Navigation started! Map follows your location.': 'வழிசெலுத்தல் தொடங்கியது! வரைபடம் உங்கள் இருப்பைப் பின்தொடர்கிறது.',
      'Trigger SOS?': 'SOS ஐ தூண்டவா?',
      'Tier 1 contact will receive a phone call. Other tiers will receive a WhatsApp message. Continue?': 'டியர் 1 தொடர்பு தொலைபேசி அழைப்பைப் பெறுவார். மற்ற டியர்கள் WhatsApp செய்தியைப் பெறுவார்கள். தொடரவா?',
      'You are OFFLINE. Tier 1 will be called directly. Other tiers will receive an SMS message. Continue?': 'நீங்கள் ஆஃப்லைனில் உள்ளீர்கள். டியர் 1 நேரடியாக அழைக்கப்படுவார். மற்ற டியர்கள் SMS செய்தியைப் பெறுவார்கள். தொடரவா?',
      'SEND SOS': 'SOS அனுப்பு',
      'Emergency Broadcast?': 'அவசர ஒலிபரப்பு?',
      'BROADCAST NOW': 'இப்போது ஒலிபரப்பு',
      'Edit Health Profile': 'சுகாதார சுயவிவரத்தைத் திருத்து',
      'Blood Group': 'இரத்த வகை',
      'Allergies': 'ஒவ்வாமைகள்',
      'Diseases / Conditions': 'நோய்கள் / நிலைகள்',
      'Weight (kg)': 'எடை (கிலோ)',
      'Height (cm)': 'உயரம் (செமீ)',
      'How to use AI Assistant': 'AI உதவியாளரை எவ்வாறு பயன்படுத்துவது',
      'Got it': 'புரிந்தது',
      'How to use': 'எவ்வாறு பயன்படுத்துவது',
      'Family Health Dashboard': 'குடும்ப சுகாதார டாஷ்போர்டு',
      'Add family member': 'குடும்ப உறுப்பினரைச் சேர்',
      'Add Family Member': 'குடும்ப உறுப்பினரைச் சேர்',
      'No family members yet': 'இன்னும் குடும்ப உறுப்பினர்கள் இல்லை',
      'Add family members to monitor their health': 'அவர்களின் சுகாதாரத்தைக் கண்காணிக்க குடும்ப உறுப்பினர்களைச் சேர்க்கவும்',
      'Health Info': 'சுகாதார தகவல்',
      'View Health History': 'சுகாதார வரலாற்றைக் காண',
      'Full Name': 'முழு பெயர்',
      'Relationship': 'உறவு',
      'Email (optional)': 'மின்னஞ்சல் (விருப்பம்)',
      'Email': 'மின்னஞ்சல்',
      'Age': 'வயது',
      'Phone': 'தொலைபேசி',
      'Add Member': 'உறுப்பினரைச் சேர்',
      'Name is required': 'பெயர் தேவை',
      'Edit': 'திருத்து',
      'Remove': 'நீக்கு',
      'Remove Family Member': 'குடும்ப உறுப்பினரை நீக்கு',
      'Add Health Data for {name}': '{name} க்கு சுகாதார தரவைச் சேர்',
      'Date: {date}': 'தேதி: {date}',
      'Blood Pressure': 'இரத்த அழுத்தம்',
      'Blood Sugar': 'இரத்த சர்க்கரை',
      'Heart Rate': 'இதய துடிப்பு',
      'Sleep (hours)': 'தூக்கம் (மணிநேரம்)',
      'Notes (optional)': 'குறிப்புகள் (விருப்பம்)',
      'added to family': '{name} குடும்பத்தில் சேர்க்கப்பட்டார்',
      'Remove {name} and all their health data?': '{name} மற்றும் அவர்களின் அனைத்து சுகாதார தரவையும் நீக்கவா?',
      'Hospital': 'மருத்துவமனை',
      'Pharmacy': 'மருந்தகம்',
      'Ambulance': 'ஆம்புலன்ஸ்',
      'places found': 'இடங்கள் கண்டறியப்பட்டன',
      'You': 'நீங்கள்',
      'Getting your GPS location...': 'உங்கள் GPS இருப்பைப் பெறுகிறது...',
      'Please wait while we find where you are': 'நீங்கள் எங்கே இருக்கிறீர்கள் என்று கண்டறியும் வரை காத்திருங்கள்',
      'Navigation started! Map follows your location.': 'வழிசெலுத்தல் தொடங்கியது! வரைபடம் உங்கள் இருப்பைப் பின்தொடர்கிறது.',
      'Neck Stretches': 'கழுத்து நீட்சிப்பயிற்சி',
      'Finger Bends': 'விரல் வளைவுகள்',
      'Shoulder Shrugs': 'தோள்பட்டை உயர்த்தல்',
      'Seated Marching': 'நாற்காலியில் நடை',
      'Arm Circles': 'கை வட்டங்கள்',
      'Chair Squats': 'நாற்காலி ஸ்குவாட்ஸ்',
      'Ankle Rotations': 'கணுக்கால் சுழற்சி',
      'Cat-Cow Stretch': 'பூனை-பசு நீட்சி',
      'Knee-to-Chest': 'முழங்கால்-மார்பு',
      'Quad Sets': 'குவாட் செட்கள்',
      'Seated Leg Raises': 'நாற்காலியில் கால் தூக்குதல்',
      'Step-ups': 'படி ஏறுதல்',
      'Standing Side Bends': 'நின்று பக்க வளைவுகள்',
      'Seated Exercises': 'நாற்காலி பயிற்சிகள்',
      'Neck Exercises': 'கழுத்து பயிற்சிகள்',
      'Abdominal Massage': 'வயிற்று மசாஜ்',
      'Gentle Neck Rolls': 'மெதுவான கழுத்து சுழற்சி',
      'Pursed Lip Breathing': 'உதடு குவித்து சுவாசம்',
      'Health Report': 'சுகாதார அறிக்கை',
      'Export monthly health data as PDF': 'மாதாந்திர சுகாதார தரவை PDF ஆக ஏற்றுமதி செய்',
      'Generating health report...': 'சுகாதார அறிக்கை உருவாக்கப்படுகிறது...',
      'Error generating report': 'அறிக்கை உருவாக்குவதில் பிழை',
      'Water Intake': 'தண்ணீர் அருந்துதல்',
      'glasses': 'கிளாஸ்கள்',
      'Set Water Goal': 'தண்ணீர் இலக்கை அமை',
      'Remove glass': 'கிளாஸ் நீக்கு',
      'Add glass': 'கிளாஸ் சேர்',
      '250ml per glass': 'ஒரு கிளாஸ் 250ml',
      'Goal reached!': 'இலக்கு எட்டப்பட்டது!',
      'remaining': 'மீதமுள்ளது',
      'Water goal reached! Great job staying hydrated!': 'தண்ணீர் இலக்கு எட்டப்பட்டது!',
    },
    'Telugu': {
      'Caregiver Access': 'సంరక్షకుని ప్రవేశం',
      'Continue': 'కొనసాగించండి',
      'Create account': 'ఖాతా సృష్టించండి',
      'Home': 'హోమ్',
      'SOS': 'SOS',
      'Health': 'ఆరోగ్యం',
      'Emergency status': 'అత్యవసర స్థితి',
      'Stable': 'స్థిరంగా ఉంది',
      'Emergency SOS': 'అత్యవసర SOS',
      'Today\'s health snapshot': 'నేటి ఆరోగ్య సారాంశం',
      'Care route': 'సంరక్షణ మార్గం',
      'Medicine reminder': 'మందుల రిమైండర్',
      'AI Health Assistant': 'AI ఆరోగ్య సహాయకుడు',
      'Caregiver settings': 'సంరక్షకుని సెట్టింగ్‌లు',
      'Sign out': 'సైన్ అవుట్',
      'Medicine name': 'మందు పేరు',
      'Time': 'సమయం',
      'Submit reminder': 'రిమైండర్ సమర్పించండి',
      'Enter medicine and time': 'మందు మరియు సమయం నమోదు చేయండి',
      'Reminder saved': 'రిమైండర్ సేవ్ చేయబడింది',
      'Delete reminder': 'రిమైండర్ తొలగించండి',
      'Get guidance': 'మార్గదర్శకత్వం పొందండి',
      'Blood group': 'రక్తం గ్రూప్',
      'Allergies': 'అలెర్జీలు',
      'Contact': 'సంప్రదించండి',
      'Voice input': 'వాయిస్ ఇన్‌పుట్',
      'Guidance summary': 'మార్గదర్శక సారాంశం',
      'Send SOS Now': 'ఇప్పుడు SOS పంపండి',
      'Nearby healthcare services': 'సమీప ఆరోగ్య సేవలు',
      'Save record': 'రికార్డును సేవ్ చేయండి',
      'Saving...': 'సేవ్ అవుతోంది...',
      'Today': 'ఈరోజు',
      'Weight': 'బరువు',
      'Height': 'ఎత్తు',
      'Not set': 'సెట్ చేయబడలేదు',
      'None': 'ఏదీ లేదు',
      'Screen time today': 'ఈరోజు స్క్రీన్ సమయం',
      'hours': 'గంటలు',
      'Emergency contact': 'అత్యవసర సంప్రదింపు',
      'Edit emergency contact': 'అత్యవసర సంప్రదింపును సవరించండి',
      'Call Emergency Contact': 'అత్యవసర సంప్రదింపును కాల్ చేయండి',
      'Enter data': 'డేటా నమోదు చేయండి',
      'Register as Donor': 'దాతగా నమోదు చేయండి',
      'Register': 'నమోదు చేయండి',
      'Available Donors': 'అందుబాటులో ఉన్న దాతలు',
      'Blood Donation': 'రక్తదానం',
      'Describe your symptoms or ask for first aid guidance':
          'మీ లక్షణాలను వివరించండి లేదా ప్రథమ చికిత్స మార్గదర్శకత్వం అడగండి',
      'Map': 'మ్యాప్',
      'Find nearby care': 'సమీపంలోని సంరక్షణను కనుగొనండి',
      'Distance': 'దూరం',
      'ETA': 'అంచనా సమయం',
      'Stop Navigation': 'నావిగేషన్ ఆపండి',
      'Start Navigation': 'నావిగేషన్ ప్రారంభించండి',
      'Following your location...': 'మీ స్థానాన్ని అనుసరిస్తోంది...',
      'Daily Exercises': 'రోజువారీ వ్యాయామాలు',
      'Based on your conditions': 'మీ పరిస్థితుల ఆధారంగా',
      'All exercises done today! Keep the streak alive tomorrow!': 'ఈ రోజు అన్ని వ్యాయామాలు పూర్తయ్యాయి! రేపు కూడా కొనసాగించండి!',
      'Connect Smartwatch': 'స్మార్ట్ వాచ్ కనెక్ట్ చేయండి',
      'Find Hospitals & Pharmacies Near You': 'మీ సమీపంలో ఆసుపత్రులు & మందుల దుకాణాలు కనుగొనండి',
      'Walking': 'నడక',
      'Stretching': 'స్ట్రెచింగ్',
      'Deep Breathing': 'లోతైన శ్వాస',
      'Brisk Walking': 'వేగవంతమైన నడక',
      'Gentle Walking': 'మెల్లగా నడక',
      'Meditation': 'ధ్యానం',
      'Yoga': 'యోగా',
      'Yoga Stretching': 'యోగా స్ట్రెచింగ్',
      'Cycling': 'సైక్లింగ్',
      'Jumping Jacks': 'జంపింగ్ జాక్స్',
      'Streak': 'స్ట్రీక్',
      'days': 'రోజులు',
      "day streak! Champions don't quit!": 'రోజుల స్ట్రీక్! ఛాంపియన్లు వదలరు!',
      "days strong! Don't break the chain!": 'రోజులు బలంగా! చైన్ తెంచవద్దు!',
      "days! Almost a week - keep pushing!": 'రోజులు! దాదాపు ఒక వారం - కొనసాగించండి!',
      "day streak started! Build the habit!": 'రోజుల స్ట్రీక్ ప్రారంభమైంది! అలవాటును పెంచుకోండి!',
      'done today. Start your streak now!': 'ఈ రోజు పూర్తయ్యింది. మీ స్ట్రీక్ ఇప్పుడు ప్రారంభించండి!',
      'Refresh location': 'స్థానం రిఫ్రెష్ చేయండి',
      'Show Route on Map': 'మ్యాప్‌లో మార్గం చూపించు',
      'All': 'అన్నీ',
      'Dark Mode': 'డార్క్ మోడ్',
      'Dark theme active': 'డార్క్ థీమ్ యాక్టివ్',
      'Light theme active': 'లైట్ థీమ్ యాక్టివ్',
      'Set Step Goal': 'దశ లక్ష్యాన్ని సెట్ చేయండి',
      'steps': 'దశలు',
      'Cancel': 'రద్దు',
      'Save': 'సేవ్ చేయండి',
      'day streak': 'రోజుల స్ట్రీక్',
      'best': 'ఉత్తమ',
      'Retry — Get My Location': 'మళ్ళీ ప్రయత్నించండి — నా స్థానం పొందండి',
      'Getting your GPS location...': 'GPS స్థానం పొందుతోంది...',
      'Please wait while we find where you are': 'మీరు ఎక్కడ ఉన్నారో కనుగొనే వరకు దయచేసి వేచి ఉండండి',
      'Navigation started! Map follows your location.': 'నావిగేషన్ ప్రారంభమైంది! మ్యాప్ మీ స్థానాన్ని అనుసరిస్తోంది.',
      'Trigger SOS?': 'SOS ను ప్రేరేపించాలా?',
      'SEND SOS': 'SOS పంపండి',
      'Emergency Broadcast?': 'అత్యవసర ప్రసారం?',
      'BROADCAST NOW': 'ఇప్పుడు ప్రసారం చేయండి',
      'Edit Health Profile': 'ఆరోగ్య ప్రొఫైల్ సవరించండి',
      'Blood Group': 'రక్త సమూహం',
      'Allergies': 'అలర్జీలు',
      'Diseases / Conditions': 'వ్యాధులు / పరిస్థితులు',
      'Weight (kg)': 'బరువు (కేజీ)',
      'Height (cm)': 'ఎత్తు (సెం.మీ)',
      'How to use AI Assistant': 'AI సహాయకుడిని ఎలా ఉపయోగించాలి',
      'Got it': 'అర్థమైంది',
      'How to use': 'ఎలా ఉపయోగించాలి',
      'Family Health Dashboard': 'కుటుంబ ఆరోగ్య డాష్‌బోర్డ్',
      'Add family member': 'కుటుంబ సభ్యుడిని జోడించండి',
      'Add Family Member': 'కుటుంబ సభ్యుడిని జోడించండి',
      'No family members yet': 'ఇంకా కుటుంబ సభ్యులు లేరు',
      'Add family members to monitor their health': 'వారి ఆరోగ్యాన్ని పర్యవేక్షించడానికి కుటుంబ సభ్యులను జోడించండి',
      'Health Info': 'ఆరోగ్య సమాచారం',
      'View Health History': 'ఆరోగ్య చరిత్ర చూడండి',
      'Full Name': 'పూర్తి పేరు',
      'Relationship': 'సంబంధం',
      'Email (optional)': 'ఇమెయిల్ (ఐచ్ఛికం)',
      'Email': 'ఇమెయిల్',
      'Age': 'వయస్సు',
      'Phone': 'ఫోన్',
      'Add Member': 'సభ్యుడిని జోడించండి',
      'Name is required': 'పేరు అవసరం',
      'Edit': 'సవరించండి',
      'Remove': 'తొలగించండి',
      'Remove Family Member': 'కుటుంబ సభ్యుడిని తొలగించండి',
      'Add Health Data for {name}': '{name} కు ఆరోగ్య డేటా జోడించండి',
      'Date: {date}': 'తేదీ: {date}',
      'Blood Pressure': 'రక్తపోటు',
      'Blood Sugar': 'రక్తంలో చక్కెర',
      'Heart Rate': 'హృదయ స్పందన రేటు',
      'Sleep (hours)': 'నిద్ర (గంటలు)',
      'Notes (optional)': 'గమనికలు (ఐచ్ఛికం)',
      'added to family': '{name} కుటుంబంలో జోడించబడింది',
      'Remove {name} and all their health data?': '{name} మరియు వారి అన్ని ఆరోగ్య డేటాను తొలగించాలా?',
      'Hospital': 'ఆసుపత్రి',
      'Pharmacy': 'మందుల దుకాణం',
      'Ambulance': 'ఆంబులెన్స్',
      'places found': 'ప్రదేశాలు కనుగొనబడ్డాయి',
      'You': 'మీరు',
      'Getting your GPS location...': 'మీ GPS స్థానం పొందుతోంది...',
      'Please wait while we find where you are': 'మీరు ఎక్కడ ఉన్నారో కనుగొనే వరకు దయచేసి వేచి ఉండండి',
      'Navigation started! Map follows your location.': 'నావిగేషన్ ప్రారంభమైంది! మ్యాప్ మీ స్థానాన్ని అనుసరిస్తోంది.',
      'Neck Stretches': 'మెడ స్ట్రెచెస్',
      'Finger Bends': 'వేలు వంపులు',
      'Shoulder Shrugs': 'భుజం ష్రగ్స్',
      'Seated Marching': 'కుర్చీలో నడక',
      'Arm Circles': 'చేతి వృత్తాలు',
      'Chair Squats': 'కుర్చీ స్క్వాట్స్',
      'Ankle Rotations': 'పాదముక్క తిప్పడం',
      'Cat-Cow Stretch': 'పిల్లి-ఆవు స్ట్రెచ్',
      'Knee-to-Chest': 'మోకాలి-ఛాతీ',
      'Quad Sets': 'క్వాడ్ సెట్లు',
      'Seated Leg Raises': 'కుర్చీలో కాలు ఎత్తడం',
      'Step-ups': 'అడుగులు ఎత్తడం',
      'Standing Side Bends': 'నిలబడి పక్క వంపులు',
      'Seated Exercises': 'కుర్చీ వ్యాయామాలు',
      'Neck Exercises': 'మెడ వ్యాయామాలు',
      'Abdominal Massage': 'కడుపు మసాజ్',
      'Gentle Neck Rolls': 'మెల్లగా మెడ తిప్పడం',
      'Pursed Lip Breathing': 'పెదవి కుదించి శ్వాస',
      'Health Report': 'ఆరోగ్య నివేదిక',
      'Export monthly health data as PDF': 'నెలవారీ ఆరోగ్య డేటాను PDF గా ఎగుమతి చేయండి',
      'Generating health report...': 'ఆరోగ్య నివేదిక రూపొందిస్తోంది...',
      'Error generating report': 'నివేదిక రూపొందించడంలో లోపం',
      'Water Intake': 'నీటి వినియోగం',
      'glasses': 'గ్లాసులు',
      'Set Water Goal': 'నీటి లక్ష్యం సెట్ చేయండి',
      'Remove glass': 'గ్లాసు తొలగించండి',
      'Add glass': 'గ్లాసు జోడించండి',
      '250ml per glass': 'ఒక్కో గ్లాసు 250ml',
      'Goal reached!': 'లక్ష్యం చేరుకుంది!',
      'remaining': 'మిగిలి ఉంది',
      'Water goal reached! Great job staying hydrated!': 'నీటి లక్ష్యం చేరుకుంది!',
    },
    'Kannada': {
      'Caregiver Access': 'ಪಾಲಕರ ಪ್ರವೇಶ',
      'Continue': 'ಮುಂದುವರಿಸಿ',
      'Create account': 'ಖಾತೆ ರಚಿಸಿ',
      'Home': 'ಮುಖಪುಟ',
      'SOS': 'SOS',
      'Health': 'ಆರೋಗ್ಯ',
      'Emergency status': 'ತುರ್ತು ಸ್ಥಿತಿ',
      'Stable': 'ಸ್ಥಿರ',
      'Emergency SOS': 'ತುರ್ತು SOS',
      'Today\'s health snapshot': 'ಇಂದಿನ ಆರೋಗ್ಯ ಸಾರಾಂಶ',
      'Care route': 'ಆರೈಕೆ ಮಾರ್ಗ',
      'Medicine reminder': 'ಔಷಧಿ ಜ್ಞಾಪನೆ',
      'AI Health Assistant': 'AI ಆರೋಗ್ಯ ಸಹಾಯಕ',
      'Caregiver settings': 'ಪಾಲಕರ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'Sign out': 'ಸೈನ್ ಔಟ್',
      'Medicine name': 'ಔಷಧಿಯ ಹೆಸರು',
      'Time': 'ಸಮಯ',
      'Submit reminder': 'ಜ್ಞಾಪನೆ ಸಲ್ಲಿಸಿ',
      'Enter medicine and time': 'ಔಷಧಿ ಮತ್ತು ಸಮಯ ನಮೂದಿಸಿ',
      'Reminder saved': 'ಜ್ಞಾಪನೆ ಉಳಿಸಲಾಗಿದೆ',
      'Delete reminder': 'ಜ್ಞಾಪನೆ ಅಳಿಸಿ',
      'Get guidance': 'ಮಾರ್ಗದರ್ಶನ ಪಡೆಯಿರಿ',
      'Blood group': 'ರಕ್ತದ ಗುಂಪು',
      'Allergies': 'ಅಲರ್ಜಿ',
      'Contact': 'ಸಂಪರ್ಕ',
      'Voice input': 'ಧ್ವನಿ ಇನ್‌ಪುಟ್',
      'Guidance summary': 'ಮಾರ್ಗದರ್ಶನ ಸಾರಾಂಶ',
      'Send SOS Now': 'ಈಗ SOS ಕಳುಹಿಸಿ',
      'Nearby healthcare services': 'ಹತ್ತಿರದ ಆರೋಗ್ಯ ಸೇವೆಗಳು',
      'Save record': 'ದಾಖಲೆ ಉಳಿಸಿ',
      'Saving...': 'ಉಳಿಸಲಾಗುತ್ತಿದೆ...',
      'Today': 'ಇಂದು',
      'Weight': 'ತೂಕ',
      'Height': 'ಎತ್ತರ',
      'Not set': 'ಸೆಟ್ ಮಾಡಿಲ್ಲ',
      'None': 'ಯಾವುದೂ ಇಲ್ಲ',
      'Screen time today': 'ಇಂದಿನ ಸ್ಕ್ರೀನ್ ಸಮಯ',
      'hours': 'ಗಂಟೆಗಳು',
      'Emergency contact': 'ತುರ್ತು ಸಂಪರ್ಕ',
      'Edit emergency contact': 'ತುರ್ತು ಸಂಪರ್ಕವನ್ನು ಸಂಪಾದಿಸಿ',
      'Call Emergency Contact': 'ತುರ್ತು ಸಂಪರ್ಕವನ್ನು ಕರೆಯಿರಿ',
      'Enter data': 'ಡೇಟಾ ನಮೂದಿಸಿ',
      'Register as Donor': 'ದಾತರಾಗಿ ನೋಂದಾಯಿಸಿ',
      'Register': 'ನೋಂದಾಯಿಸಿ',
      'Available Donors': 'ಲಭ್ಯವಿರುವ ದಾತರು',
      'Blood Donation': 'ರಕ್ತದಾನ',
      'Describe your symptoms or ask for first aid guidance':
          'ನಿಮ್ಮ ಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ ಅಥವಾ ಪ್ರಥಮ ಚಿಕಿತ್ಸೆ ಮಾರ್ಗದರ್ಶನ ಕೇಳಿ',
      'Map': 'ನಕ್ಷೆ',
      'Find nearby care': 'ಹತ್ತಿರದ ಆರೈಕೆಯನ್ನು ಹುಡುಕಿ',
      'Distance': 'ದೂರ',
      'ETA': 'ಅಂದಾಜು ಸಮಯ',
      'Stop Navigation': 'ನಾವಿಗೇಶನ್ ನಿಲ್ಲಿಸಿ',
      'Start Navigation': 'ನಾವಿಗೇಶನ್ ಪ್ರಾರಂಭಿಸಿ',
      'Following your location...': 'ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಅನುಸರಿಸುತ್ತಿದೆ...',
      'Daily Exercises': 'ದೈನಂದಿನ ವ್ಯಾಯಾಮಗಳು',
      'Based on your conditions': 'ನಿಮ್ಮ ಪರಿಸ್ಥಿತಿಗಳ ಆಧಾರದ ಮೇಲೆ',
      'All exercises done today! Keep the streak alive tomorrow!': 'ಇಂದು ಎಲ್ಲಾ ವ್ಯಾಯಾಮಗಳು ಪೂರ್ಣಗೊಂಡಿವೆ! ನಾಳೆ ಮುಂದುವರಿಸಿ!',
      'Connect Smartwatch': 'ಸ್ಮಾರ್ಟ್‌ವಾಚ್ ಸಂಪರ್ಕಿಸಿ',
      'Find Hospitals & Pharmacies Near You': 'ನಿಮ್ಮ ಹತ್ತಿರ ಆಸ್ಪತ್ರೆಗಳು & ಔಷಧಾಲಯಗಳು ಹುಡುಕಿ',
      'Walking': 'ನಡಿಗೆ',
      'Stretching': 'ಸ್ಟ್ರೆಚಿಂಗ್',
      'Deep Breathing': 'ಆಳವಾದ ಉಸಿರಾಟ',
      'Brisk Walking': 'ವೇಗದ ನಡಿಗೆ',
      'Gentle Walking': 'ಮೃದುವಾದ ನಡಿಗೆ',
      'Meditation': 'ಧ್ಯಾನ',
      'Yoga': 'ಯೋಗ',
      'Yoga Stretching': 'ಯೋಗ ಸ್ಟ್ರೆಚಿಂಗ್',
      'Cycling': 'ಸೈಕ್ಲಿಂಗ್',
      'Jumping Jacks': 'ಜಂಪಿಂಗ್ ಜಾಕ್ಸ್',
      'Streak': 'ಸ್ಟ್ರೀಕ್',
      'days': 'ದಿನಗಳು',
      "day streak! Champions don't quit!": 'ದಿನ ಸ್ಟ್ರೀಕ್! ಚಾಂಪಿಯನ್ಸ್ ಬಿಟ್ಟುಕೊಡುವುದಿಲ್ಲ!',
      "days strong! Don't break the chain!": 'ದಿನಗಳು ಬಲವಾಗಿ! ಸರಪಳಿ ಮುರಿಯಬೇಡಿ!',
      "days! Almost a week - keep pushing!": 'ದಿನಗಳು! ಬಹುತೇಕ ಒಂದು ವಾರ - ಮುಂದುವರಿಸಿ!',
      "day streak started! Build the habit!": 'ದಿನ ಸ್ಟ್ರೀಕ್ ಪ್ರಾರಂಭವಾಯಿತು! ಅಭ್ಯಾಸ ಬೆಳೆಸಿ!',
      'done today. Start your streak now!': 'ಇಂದು ಪೂರ್ಣಗೊಂಡಿದೆ. ನಿಮ್ಮ ಸ್ಟ್ರೀಕ್ ಈಗ ಪ್ರಾರಂಭಿಸಿ!',
      'Refresh location': 'ಸ್ಥಳವನ್ನು ರಿಫ್ರೆಶ್ ಮಾಡಿ',
      'Show Route on Map': 'ನಕ್ಷೆಯಲ್ಲಿ ಮಾರ್ಗ ತೋರಿಸಿ',
      'All': 'ಎಲ್ಲಾ',
      'Dark Mode': 'ಡಾರ್ಕ್ ಮೋಡ್',
      'Dark theme active': 'ಡಾರ್ಕ್ ಥೀಮ್ ಸಕ್ರಿಯ',
      'Light theme active': 'ಲೈಟ್ ಥೀಮ್ ಸಕ್ರಿಯ',
      'Set Step Goal': 'ಹೆಜ್ಜೆ ಗುರಿಯನ್ನು ಹೊಂದಿಸಿ',
      'steps': 'ಹೆಜ್ಜೆಗಳು',
      'Cancel': 'ರದ್ದುಮಾಡಿ',
      'Save': 'ಉಳಿಸಿ',
      'day streak': 'ದಿನ ಸ್ಟ್ರೀಕ್',
      'best': 'ಉತ್ತಮ',
      'Retry — Get My Location': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ — ನನ್ನ ಸ್ಥಳ ಪಡೆಯಿರಿ',
      'Getting your GPS location...': 'GPS ಸ್ಥಳ ಪಡೆಯುತ್ತಿದೆ...',
      'Please wait while we find where you are': 'ನೀವು ಎಲ್ಲಿದ್ದೀರಿ ಎಂದು ಕಂಡುಕೊಳ್ಳುವ ತನಕ ದಯವಿಟ್ಟು ಕಾಯಿರಿ',
      'Navigation started! Map follows your location.': 'ನಾವಿಗೇಶನ್ ಪ್ರಾರಂಭವಾಗಿದೆ! ನಕ್ಷೆ ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಅನುಸರಿಸುತ್ತಿದೆ.',
      'Trigger SOS?': 'SOS ಪ್ರೇರೇಪಿಸಬೇಕೇ?',
      'SEND SOS': 'SOS ಕಳುಹಿಸಿ',
      'Emergency Broadcast?': 'ತುರ್ತು ಪ್ರಸಾರ?',
      'BROADCAST NOW': 'ಈಗ ಪ್ರಸಾರ ಮಾಡಿ',
      'Edit Health Profile': 'ಆರೋಗ್ಯ ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
      'Blood Group': 'ರಕ್ತ ಗುಂಪು',
      'Allergies': 'ಅಲರ್ಜಿಗಳು',
      'Diseases / Conditions': 'ರೋಗಗಳು / ಸ್ಥಿತಿಗಳು',
      'Weight (kg)': 'ತೂಕ (ಕೆಜಿ)',
      'Height (cm)': 'ಎತ್ತು (ಸೆಂ.ಮೀ)',
      'How to use AI Assistant': 'AI ಸಹಾಯಕವನ್ನು ಹೇಗೆ ಬಳಸುವುದು',
      'Got it': 'ಅರ್ಥವಾಯಿತು',
      'How to use': 'ಹೇಗೆ ಬಳಸುವುದು',
      'Family Health Dashboard': 'ಕುಟುಂಬ ಆರೋಗ್ಯ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'Add family member': 'ಕುಟುಂಬ ಸದಸ್ಯರನ್ನು ಸೇರಿಸಿ',
      'Add Family Member': 'ಕುಟುಂಬ ಸದಸ್ಯರನ್ನು ಸೇರಿಸಿ',
      'No family members yet': 'ಇನ್ನೂ ಕುಟುಂಬ ಸದಸ್ಯರು ಇಲ್ಲ',
      'Add family members to monitor their health': 'ಅವರ ಆರೋಗ್ಯವನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಲು ಕುಟುಂಬ ಸದಸ್ಯರನ್ನು ಸೇರಿಸಿ',
      'Health Info': 'ಆರೋಗ್ಯ ಮಾಹಿತಿ',
      'View Health History': 'ಆರೋಗ್ಯ ಇತಿಹಾಸ ನೋಡಿ',
      'Full Name': 'ಪೂರ್ಣ ಹೆಸರು',
      'Relationship': 'ಸಂಬಂಧ',
      'Email (optional)': 'ಇಮೇಲ್ (ಐಚ್ಛಿಕ)',
      'Email': 'ಇಮೇಲ್',
      'Age': 'ವಯಸ್ಸು',
      'Phone': 'ಫೋನ್',
      'Add Member': 'ಸದಸ್ಯರನ್ನು ಸೇರಿಸಿ',
      'Name is required': 'ಹೆಸರು ಅಗತ್ಯವಿದೆ',
      'Edit': 'ಸಂಪಾದಿಸಿ',
      'Remove': 'ತೆಗೆದುಹಾಕಿ',
      'Remove Family Member': 'ಕುಟುಂಬ ಸದಸ್ಯರನ್ನು ತೆಗೆದುಹಾಕಿ',
      'Add Health Data for {name}': '{name} ಗೆ ಆರೋಗ್ಯ ಡೇಟಾ ಸೇರಿಸಿ',
      'Date: {date}': 'ದಿನಾಂಕ: {date}',
      'Blood Pressure': 'ರಕ್ತದೊತ್ತಡ',
      'Blood Sugar': 'ರಕ್ತದ ಸಕ್ಕರೆ',
      'Heart Rate': 'ಹೃದಯ ಬಡಿತ ದರ',
      'Sleep (hours)': 'ನಿದ್ರೆ (ಗಂಟೆಗಳು)',
      'Notes (optional)': 'ಗಮನಿಕೆಗಳು (ಐಚ್ಛಿಕ)',
      'added to family': '{name} ಕುಟುಂಬಕ್ಕೆ ಸೇರಿಸಲಾಗಿದೆ',
      'Remove {name} and all their health data?': '{name} ಮತ್ತು ಅವರ ಎಲ್ಲಾ ಆರೋಗ್ಯ ಡೇಟಾವನ್ನು ತೆಗೆದುಹಾಕಬೇಕೇ?',
      'Hospital': 'ಆಸ್ಪತ್ರೆ',
      'Pharmacy': 'ಔಷಧಾಲಯ',
      'Ambulance': 'ಆಂಬುಲೆನ್ಸ್',
      'places found': 'ಸ್ಥಳಗಳು ಕಂಡುಬಂದಿವೆ',
      'You': 'ನೀವು',
      'Getting your GPS location...': 'ನಿಮ್ಮ GPS ಸ್ಥಳ ಪಡೆಯುತ್ತಿದೆ...',
      'Please wait while we find where you are': 'ನೀವು ಎಲ್ಲಿದ್ದೀರಿ ಎಂದು ಕಂಡುಕೊಳ್ಳುವ ತನಕ ದಯವಿಟ್ಟು ಕಾಯಿರಿ',
      'Navigation started! Map follows your location.': 'ನಾವಿಗೇಶನ್ ಪ್ರಾರಂಭವಾಗಿದೆ! ನಕ್ಷೆ ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಅನುಸರಿಸುತ್ತಿದೆ.',
      'Neck Stretches': 'ಕುತ್ತಿಗೆ ಸ್ಟ್ರೆಚ್‌ಗಳು',
      'Finger Bends': 'ಬೆರಳು ಬಾಗುವಿಕೆ',
      'Shoulder Shrugs': 'ಭುಜ ಶ್ರಗ್‌ಗಳು',
      'Seated Marching': 'ಕುರ್ಚಿಯಲ್ಲಿ ನಡೆ',
      'Arm Circles': 'ಕೈ ವೃತ್ತಗಳು',
      'Chair Squats': 'ಕುರ್ಚಿ ಸ್ಕ್ವಾಟ್ಸ್',
      'Ankle Rotations': 'ಗೋಡೆಯ ತಿರುಗಿಸುವಿಕೆ',
      'Cat-Cow Stretch': 'ಬೆಕ್ಕು-ಹಸು ಸ್ಟ್ರೆಚ್',
      'Knee-to-Chest': 'ಮೊಣಕಾಲು-ಎದೆ',
      'Quad Sets': 'ಕ್ವಾಡ್ ಸೆಟ್‌ಗಳು',
      'Seated Leg Raises': 'ಕುರ್ಚಿಯಲ್ಲಿ ಕಾಲು ಎತ್ತುವಿಕೆ',
      'Step-ups': 'ಹೆಜ್ಜೆ ಏರುವಿಕೆ',
      'Standing Side Bends': 'ನಿಂತು ಬದಿ ಬಾಗುವಿಕೆ',
      'Seated Exercises': 'ಕುರ್ಚಿ ವ್ಯಾಯಾಮಗಳು',
      'Neck Exercises': 'ಕುತ್ತಿಗೆ ವ್ಯಾಯಾಮಗಳು',
      'Abdominal Massage': 'ಹೊಟ್ಟೆ ಮಸಾಜ್',
      'Gentle Neck Rolls': 'ಮೃದುವಾದ ಕುತ್ತಿಗೆ ತಿರುಗಿಸುವಿಕೆ',
      'Pursed Lip Breathing': 'ಒರಿಸಿದ ತುಟಿ ಉಸಿರಾಟ',
      'Health Report': 'ಆರೋಗ್ಯ ವರದಿ',
      'Export monthly health data as PDF': 'ಮಾಸಿಕ ಆರೋಗ್ಯ ಡೇಟಾವನ್ನು PDF ಆಗಿ ರಫ್ತು ಮಾಡಿ',
      'Generating health report...': 'ಆರೋಗ್ಯ ವರದಿ ರಚಿಸಲಾಗುತ್ತಿದೆ...',
      'Error generating report': 'ವರದಿ ರಚಿಸುವಲ್ಲಿ ದೋಷ',
      'Water Intake': 'ನೀರಿನ ಸೇವನೆ',
      'glasses': 'ಗ್ಲಾಸ್‌ಗಳು',
      'Set Water Goal': 'ನೀರಿನ ಗುರಿಯನ್ನು ಹೊಂದಿಸಿ',
      'Remove glass': 'ಗ್ಲಾಸ್ ತೆಗೆದುಹಾಕಿ',
      'Add glass': 'ಗ್ಲಾಸ್ ಸೇರಿಸಿ',
      '250ml per glass': 'ಒಂದು ಗ್ಲಾಸ್ 250ml',
      'Goal reached!': 'ಗುರಿ ತಲುಪಿದೆ!',
      'remaining': 'ಉಳಿದಿದೆ',
      'Water goal reached! Great job staying hydrated!': 'ನೀರಿನ ಗುರಿ ತಲುಪಿದೆ!',
    },
    'Malayalam': {
      'Caregiver Access': 'പരിചാരക പ്രവേശനം',
      'Continue': 'തുടരുക',
      'Create account': 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
      'Home': 'ഹോം',
      'SOS': 'SOS',
      'Health': 'ആരോഗ്യം',
      'Emergency status': 'അടിയന്തര നില',
      'Stable': 'സ്ഥിരം',
      'Emergency SOS': 'അടിയന്തര SOS',
      'Today\'s health snapshot': 'ഇന്നത്തെ ആരോഗ്യ സംഗ്രഹം',
      'Care route': 'പരിചരണ വഴി',
      'Medicine reminder': 'മരുന്ന് ഓർമ്മപ്പെടുത്തൽ',
      'AI Health Assistant': 'AI ആരോഗ്യ സഹായി',
      'Caregiver settings': 'പരിചാരക ക്രമീകരണങ്ങൾ',
      'Sign out': 'പുറത്തുകടക്കുക',
      'Medicine name': 'മരുന്നിന്റെ പേര്',
      'Time': 'സമയം',
      'Submit reminder': 'ഓർമ്മപ്പെടുത്തൽ സമർപ്പിക്കുക',
      'Enter medicine and time': 'മരുന്നും സമയവും നൽകുക',
      'Reminder saved': 'ഓർമ്മപ്പെടുത്തൽ സംരക്ഷിച്ചു',
      'Delete reminder': 'ഓർമ്മപ്പെടുത്തൽ നീക്കം ചെയ്യുക',
      'Get guidance': 'മാർഗനിർദേശം നേടുക',
      'Blood group': 'രക്തഗ്രൂപ്പ്',
      'Allergies': 'അലർജികൾ',
      'Contact': 'ബന്ധപ്പെടുക',
      'Voice input': 'വോയ്സ് ഇൻപുട്ട്',
      'Guidance summary': 'മാർഗനിർദേശ സംഗ്രഹം',
      'Send SOS Now': 'ഇപ്പോൾ SOS അയയ്ക്കുക',
      'Nearby healthcare services': 'സമീപത്തെ ആരോഗ്യ സേവനങ്ങൾ',
      'Save record': 'രേഖ സംരക്ഷിക്കുക',
      'Saving...': 'സംരക്ഷിക്കുന്നു...',
      'Today': 'ഇന്ന്',
      'Weight': 'ഭാരം',
      'Height': 'ഉയരം',
      'Not set': 'സെറ്റ് ചെയ്തിട്ടില്ല',
      'None': 'ഇല്ല',
      'Screen time today': 'ഇന്നത്തെ സ്ക്രീൻ സമയം',
      'hours': 'മണിക്കൂർ',
      'Emergency contact': 'അടിയന്തര ബന്ധം',
      'Edit emergency contact': 'അടിയന്തര ബന്ധം എഡിറ്റ് ചെയ്യുക',
      'Call Emergency Contact': 'അടിയന്തര ബന്ധം വിളിക്കുക',
      'Enter data': 'ഡേറ്റ നൽകുക',
      'Register as Donor': 'ദാതാവായി രജിസ്റ്റർ ചെയ്യുക',
      'Register': 'രജിസ്റ്റർ ചെയ്യുക',
      'Available Donors': 'ലഭ്യമായ ദാതാക്കൾ',
      'Blood Donation': 'രക്തദാനം',
      'Describe your symptoms or ask for first aid guidance':
          'നിങ്ങളുടെ ലക്ഷണങ്ങൾ വിവരിക്കുകയോ പ്രഥമശുശ്രൂഷാ മാർഗനിർദേശം ചോദിക്കുകയോ ചെയ്യുക',
      'Map': 'മാപ്പ്',
      'Find nearby care': 'അടുത്തുള്ള പരിപാലനം കണ്ടെത്തുക',
      'Distance': 'ദൂരം',
      'ETA': 'എസ്റ്റിംഗ് സമയം',
      'Stop Navigation': 'നാവിഗേഷൻ നിർത്തുക',
      'Start Navigation': 'നാവിഗേഷൻ ആരംഭിക്കുക',
      'Following your location...': 'നിങ്ങളുടെ സ്ഥാനം പിന്തുടരുന്നു...',
      'Daily Exercises': 'ദൈനംദിന വ്യായാമങ്ങൾ',
      'Based on your conditions': 'നിങ്ങളുടെ അവസ്ഥകളുടെ അടിസ്ഥാനത്തിൽ',
      'All exercises done today! Keep the streak alive tomorrow!': 'ഇന്ന് എല്ലാ വ്യായാമങ്ങളും പൂർത്തിയായി! നാളെയും തുടരുക!',
      'Connect Smartwatch': 'സ്മാർട്ട്‌വാച്ച് കണക്റ്റ് ചെയ്യുക',
      'Find Hospitals & Pharmacies Near You': 'നിങ്ങളുടെ സമീപത്തുള്ള ആശുപത്രികളും മരുന്നുകടകളും കണ്ടെത്തുക',
      'Walking': 'നടത്തം',
      'Stretching': 'സ്ട്രെച്ചിംഗ്',
      'Deep Breathing': 'ആഴത്തിലുള്ള ശ്വാസം',
      'Brisk Walking': 'വേഗത്തിലുള്ള നടത്തം',
      'Gentle Walking': 'മൃദുവായ നടത്തം',
      'Meditation': 'ധ്യാനം',
      'Yoga': 'യോഗ',
      'Yoga Stretching': 'യോഗ സ്ട്രെച്ചിംഗ്',
      'Cycling': 'സൈക്ലിംഗ്',
      'Jumping Jacks': 'ജംപിംഗ് ജാക്സ്',
      'Streak': 'സ്ട്രീക്ക്',
      'days': 'ദിവസങ്ങൾ',
      "day streak! Champions don't quit!": 'ദിവസ സ്ട്രീക്ക്! ചാമ്പ്യൻമാർ വിടുകയില്ല!',
      "days strong! Don't break the chain!": 'ദിവസങ്ങൾ ശക്തമായി! ചെയിൻ പൊട്ടിക്കരുത്!',
      "days! Almost a week - keep pushing!": 'ദിവസങ്ങൾ! ഏകദേശം ഒരു ആഴ്ച - തുടരുക!',
      "day streak started! Build the habit!": 'ദിവസ സ്ട്രീക്ക് ആരംഭിച്ചു! ശീലം വളർത്തുക!',
      'done today. Start your streak now!': 'ഇന്ന് പൂർത്തിയായി! ഇപ്പോൾ നിങ്ങളുടെ സ്ട്രീക്ക് ആരംഭിക്കുക!',
      'Refresh location': 'സ്ഥാനം റീഫ്രഷ് ചെയ്യുക',
      'Show Route on Map': 'മാപ്പിൽ റൂട്ട് കാണിക്കുക',
      'All': 'എല്ലാം',
      'Dark Mode': 'ഡാർക്ക് മോഡ്',
      'Dark theme active': 'ഡാർക്ക് തീം സജീവം',
      'Light theme active': 'ലൈറ്റ് തീം സജീവം',
      'Set Step Goal': 'സ്റ്റെപ്പ് ലക്ഷ്യം സജ്ജമാക്കുക',
      'steps': 'സ്റ്റെപ്പുകൾ',
      'Cancel': 'റദ്ദാക്കുക',
      'Save': 'സേവ് ചെയ്യുക',
      'day streak': 'ദിവസ സ്ട്രീക്ക്',
      'best': 'ഏറ്റവും നല്ലത്',
      'Retry — Get My Location': 'വീണ്ടും ശ്രമിക്കുക — എൻ്റെ സ്ഥാനം നേടുക',
      'Getting your GPS location...': 'GPS സ്ഥാനം ലഭിക്കുന്നു...',
      'Please wait while we find where you are': 'നിങ്ങൾ എവിടെയാണെന്ന് കണ്ടെത്തുന്നതുവരെ കാത്തിരിക്കുക',
      'Navigation started! Map follows your location.': 'നാവിഗേഷൻ ആരംഭിച്ചു! മാപ്പ് നിങ്ങളുടെ സ്ഥാനം പിന്തുടരുന്നു.',
      'Trigger SOS?': 'SOS ട്രിഗർ ചെയ്യണോ?',
      'SEND SOS': 'SOS അയയ്ക്കുക',
      'Emergency Broadcast?': 'അടിയന്തര പ്രക്ഷേപണം?',
      'BROADCAST NOW': 'ഇപ്പോൾ പ്രക്ഷേപണം ചെയ്യുക',
      'Edit Health Profile': 'ആരോഗ്യ പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക',
      'Blood Group': 'രക്തഗ്രൂപ്പ്',
      'Allergies': 'അലർജികൾ',
      'Diseases / Conditions': 'രോഗങ്ങൾ / അവസ്ഥകൾ',
      'Weight (kg)': 'ഭാരം (കി.ഗ്രാ)',
      'Height (cm)': 'ഉയരം (സെ.മീ)',
      'How to use AI Assistant': 'AI സഹായിയെ എങ്ങനെ ഉപയോഗിക്കാം',
      'Got it': 'മനസ്സിലായി',
      'How to use': 'എങ്ങനെ ഉപയോഗിക്കാം',
      'Family Health Dashboard': 'കുടുംബ ആരോഗ്യ ഡാഷ്‌ബോർഡ്',
      'Add family member': 'കുടുംബ അംഗത്തെ ചേർക്കുക',
      'Add Family Member': 'കുടുംബ അംഗത്തെ ചേർക്കുക',
      'No family members yet': 'ഇതുവരെ കുടുംബ അംഗങ്ങൾ ഇല്ല',
      'Add family members to monitor their health': 'അവരുടെ ആരോഗ്യം നിരീക്ഷിക്കാൻ കുടുംബ അംഗങ്ങളെ ചേർക്കുക',
      'Health Info': 'ആരോഗ്യ വിവരം',
      'View Health History': 'ആരോഗ്യ ചരിത്രം കാണുക',
      'Full Name': 'മുഴുവൻ പേര്',
      'Relationship': 'ബന്ധം',
      'Email (optional)': 'ഇമെയിൽ (ഓപ്ഷണൽ)',
      'Email': 'ഇമെയിൽ',
      'Age': 'പ്രായം',
      'Phone': 'ഫോൺ',
      'Add Member': 'അംഗത്തെ ചേർക്കുക',
      'Name is required': 'പേര് ആവശ്യമാണ്',
      'Edit': 'എഡിറ്റ് ചെയ്യുക',
      'Remove': 'നീക്കം ചെയ്യുക',
      'Remove Family Member': 'കുടുംബ അംഗത്തെ നീക്കം ചെയ്യുക',
      'Add Health Data for {name}': '{name} ന് ആരോഗ്യ ഡേറ്റാ ചേർക്കുക',
      'Date: {date}': 'തീയതി: {date}',
      'Blood Pressure': 'രക്തസമ്മർദം',
      'Blood Sugar': 'രക്തത്തിലെ പഞ്ചസാര',
      'Heart Rate': 'ഹൃദയമിടിപ്പ്',
      'Sleep (hours)': 'ഉറക്കം (മണിക്കൂറുകൾ)',
      'Notes (optional)': 'കുറിപ്പുകൾ (ഓപ്ഷണൽ)',
      'added to family': '{name} നെ കുടുംബത്തിൽ ചേർത്തു',
      'Remove {name} and all their health data?': '{name} ന്റെ എല്ലാ ആരോഗ്യ ഡേറ്റയും നീക്കം ചെയ്യണോ?',
      'Hospital': 'ആശുപത്രി',
      'Pharmacy': 'ഫാർമസി',
      'Ambulance': 'ആംബുലൻസ്',
      'places found': 'സ്ഥലങ്ങൾ കണ്ടെത്തി',
      'You': 'നിങ്ങൾ',
      'Getting your GPS location...': 'നിങ്ങളുടെ GPS സ്ഥാനം ലഭിക്കുന്നു...',
      'Please wait while we find where you are': 'നിങ്ങൾ എവിടെയാണെന്ന് കണ്ടെത്തുന്നതുവരെ കാത്തിരിക്കുക',
      'Navigation started! Map follows your location.': 'നാവിഗേഷൻ ആരംഭിച്ചു! മാപ്പ് നിങ്ങളുടെ സ്ഥാനം പിന്തുടരുന്നു.',
      'Neck Stretches': 'കഴുത്ത് സ്ട്രെച്ചുകൾ',
      'Finger Bends': 'വിരൽ വളവുകൾ',
      'Shoulder Shrugs': 'തോൾ ഷ്രഗുകൾ',
      'Seated Marching': 'കസേരയിൽ നടക്കൽ',
      'Arm Circles': 'കൈ വൃത്തങ്ങൾ',
      'Chair Squats': 'കസേര സ്ക്വാറ്റുകൾ',
      'Ankle Rotations': 'കണുക്കാൽ ഭ്രമണം',
      'Cat-Cow Stretch': 'പൂച്ച-പശു സ്ട്രെച്ച്',
      'Knee-to-Chest': 'മുട്ട-നെഞ്ച്',
      'Quad Sets': 'ക്വാഡ് സെറ്റുകൾ',
      'Seated Leg Raises': 'കസേരയിൽ കാൽ ഉയർത്തൽ',
      'Step-ups': 'പടി കയറൽ',
      'Standing Side Bends': 'നിന്ന് വശം വളയൽ',
      'Seated Exercises': 'കസേര വ്യായാമങ്ങൾ',
      'Neck Exercises': 'കഴുത്ത് വ്യായാമങ്ങൾ',
      'Abdominal Massage': 'വയറ്റിലെ മസാജ്',
      'Gentle Neck Rolls': 'മൃദുവായ കഴുത്ത് ഭ്രമണം',
      'Pursed Lip Breathing': 'ചുണ്ട് ചുരുക്കി ശ്വാസം',
      'Health Report': 'ആരോഗ്യ റിപ്പോർട്ട്',
      'Export monthly health data as PDF': 'മാസിക ആരോഗ്യ ഡേറ്റ PDF ആയി എക്സ്പോർട്ട് ചെയ്യുക',
      'Generating health report...': 'ആരോഗ്യ റിപ്പോർട്ട് ജനറേറ്റ് ചെയ്യുന്നു...',
      'Error generating report': 'റിപ്പോർട്ട് ജനറേറ്റ് ചെയ്യുന്നതിൽ പിശക്',
      'Water Intake': 'ജല ഉപഭോഗം',
      'glasses': 'ഗ്ലാസുകൾ',
      'Set Water Goal': 'ജല ലക്ഷ്യം സെറ്റ് ചെയ്യുക',
      'Remove glass': 'ഗ്ലാസ് നീക്കം ചെയ്യുക',
      'Add glass': 'ഗ്ലാസ് ചേർക്കുക',
      '250ml per glass': 'ഓരോ ഗ്ലാസ് 250ml',
      'Goal reached!': 'ലക്ഷ്യം കൈവരിച്ചു!',
      'remaining': 'ബാക്കി',
      'Water goal reached! Great job staying hydrated!': 'ജല ലക്ഷ്യം കൈവരിച്ചു!',
    },
    'Hindi': {
      'Caregiver Access': 'देखभालकर्ता प्रवेश',
      'Continue': 'जारी रखें',
      'Create account': 'खाता बनाएं',
      'Home': 'होम',
      'SOS': 'SOS',
      'Health': 'स्वास्थ्य',
      'Emergency status': 'आपात स्थिति',
      'Stable': 'स्थिर',
      'Emergency SOS': 'आपात SOS',
      'Today\'s health snapshot': 'आज का स्वास्थ्य सारांश',
      'Care route': 'देखभाल मार्ग',
      'Medicine reminder': 'दवा अनुस्मारक',
      'AI Health Assistant': 'AI स्वास्थ्य सहायक',
      'Caregiver settings': 'देखभालकर्ता सेटिंग्स',
      'Sign out': 'साइन आउट',
      'Medicine name': 'दवा का नाम',
      'Time': 'समय',
      'Submit reminder': 'अनुस्मारक जमा करें',
      'Enter medicine and time': 'दवा और समय दर्ज करें',
      'Reminder saved': 'अनुस्मारक सहेजा गया',
      'Delete reminder': 'अनुस्मारक हटाएं',
      'Get guidance': 'मार्गदर्शन प्राप्त करें',
      'Blood group': 'रक्त समूह',
      'Allergies': 'एलर्जी',
      'Contact': 'संपर्क',
      'Voice input': 'वॉइस इनपुट',
      'Guidance summary': 'मार्गदर्शन सारांश',
      'Send SOS Now': 'अभी SOS भेजें',
      'Nearby healthcare services': 'निकटतम स्वास्थ्य सेवाएं',
      'Save record': 'रिकॉर्ड सहेजें',
      'Saving...': 'सहेजा जा रहा है...',
      'Today': 'आज',
      'Weight': 'वज़न',
      'Height': 'ऊँचाई',
      'Not set': 'सेट नहीं',
      'None': 'कोई नहीं',
      'Screen time today': 'आज का स्क्रीन समय',
      'hours': 'घंटे',
      'Emergency contact': 'आपातकालीन संपर्क',
      'Edit emergency contact': 'आपातकालीन संपर्क संपादित करें',
      'Call Emergency Contact': 'आपातकालीन संपर्क को कॉल करें',
      'Enter data': 'डेटा दर्ज करें',
      'Register as Donor': 'दाता के रूप में रजिस्टर करें',
      'Register': 'रजिस्टर करें',
      'Available Donors': 'उपलब्ध दाता',
      'Blood Donation': 'रक्तदान',
      'Describe your symptoms or ask for first aid guidance':
          'अपने लक्षण बताएं या प्राथमिक उपचार मार्गदर्शन पूछें',
      'Map': 'मानचित्र',
      'Find nearby care': 'नजदीकी देखभाल खोजें',
      'Distance': 'दूरी',
      'ETA': 'अनुमानित समय',
      'Stop Navigation': 'नेविगेशन रोकें',
      'Start Navigation': 'नेविगेशन शुरू करें',
      'Following your location...': 'आपके स्थान का अनुसरण कर रहा है...',
      'Daily Exercises': 'दैनिक व्यायाम',
      'Based on your conditions': 'आपकी स्थिति के आधार पर',
      'All exercises done today! Keep the streak alive tomorrow!': 'आज सभी व्यायाम पूरे हो गए! कल भी जारी रखें!',
      'Connect Smartwatch': 'स्मार्टवॉच कनेक्ट करें',
      'Find Hospitals & Pharmacies Near You': 'अपने पास अस्पताल और फार्मेसी खोजें',
      'Walking': 'चलना',
      'Stretching': 'स्ट्रेचिंग',
      'Deep Breathing': 'गहरी सांस',
      'Brisk Walking': 'तेज़ चलना',
      'Gentle Walking': 'धीमी चाल',
      'Meditation': 'ध्यान',
      'Yoga': 'योग',
      'Yoga Stretching': 'योग स्ट्रेचिंग',
      'Cycling': 'साइक्लिंग',
      'Jumping Jacks': 'जम्पिंग जैक्स',
      'Streak': 'स्ट्रीक',
      'days': 'दिन',
      "day streak! Champions don't quit!": 'दिन स्ट्रीक! चैंपियन नहीं छोड़ते!',
      "days strong! Don't break the chain!": 'दिन मजबूत! श्रृंखला मत तोड़ो!',
      "days! Almost a week - keep pushing!": 'दिन! लगभग एक हफ्ता - जारी रखें!',
      "day streak started! Build the habit!": 'दिन स्ट्रीक शुरू हुई! आदत बनाएं!',
      'done today. Start your streak now!': 'आज पूरा हुआ। अपनी स्ट्रीक अभी शुरू करें!',
      'Refresh location': 'स्थान रीफ्रेश करें',
      'Show Route on Map': 'मानचित्र पर मार्ग दिखाएं',
      'All': 'सभी',
      'Dark Mode': 'डार्क मोड',
      'Dark theme active': 'डार्क थीम सक्रिय',
      'Light theme active': 'लाइट थीम सक्रिय',
      'Set Step Goal': 'कदम लक्ष्य सेट करें',
      'steps': 'कदम',
      'Cancel': 'रद्द करें',
      'Save': 'सहेजें',
      'day streak': 'दिन स्ट्रीक',
      'best': 'सर्वोत्तम',
      'Retry — Get My Location': 'पुनः प्रयास करें — मेरा स्थान प्राप्त करें',
      'Getting your GPS location...': 'GPS स्थान प्राप्त हो रहा है...',
      'Please wait while we find where you are': 'जब तक हम आपका स्थान पता लगाएं कृपया प्रतीक्षा करें',
      'Navigation started! Map follows your location.': 'नेविगेशन शुरू! मानचित्र आपके स्थान का अनुसरण कर रहा है.',
      'Trigger SOS?': 'SOS ट्रिगर करें?',
      'SEND SOS': 'SOS भेजें',
      'Emergency Broadcast?': 'आपातकालीन प्रसारण?',
      'BROADCAST NOW': 'अभी प्रसारित करें',
      'Edit Health Profile': 'स्वास्थ्य प्रोफ़ाइल संपादित करें',
      'Blood Group': 'रक्त समूह',
      'Allergies': 'एलर्जी',
      'Diseases / Conditions': 'रोग / स्थितियाँ',
      'Weight (kg)': 'वज़न (किलो)',
      'Height (cm)': 'ऊँचाई (सेमी)',
      'How to use AI Assistant': 'AI सहायक का उपयोग कैसे करें',
      'Got it': 'समझ गया',
      'How to use': 'कैसे उपयोग करें',
      'Family Health Dashboard': 'पारिवारिक स्वास्थ्य डैशबोर्ड',
      'Add family member': 'परिवार के सदस्य को जोड़ें',
      'Add Family Member': 'परिवार के सदस्य को जोड़ें',
      'No family members yet': 'अभी तक कोई परिवार के सदस्य नहीं',
      'Add family members to monitor their health': 'उनके स्वास्थ्य की निगरानी के लिए परिवार के सदस्यों को जोड़ें',
      'Health Info': 'स्वास्थ्य जानकारी',
      'View Health History': 'स्वास्थ्य इतिहास देखें',
      'Full Name': 'पूरा नाम',
      'Relationship': 'रिश्ता',
      'Email (optional)': 'ईमेल (वैकल्पिक)',
      'Email': 'ईमेल',
      'Age': 'उम्र',
      'Phone': 'फ़ोन',
      'Add Member': 'सदस्य जोड़ें',
      'Name is required': 'नाम आवश्यक है',
      'Edit': 'संपादित करें',
      'Remove': 'हटाएं',
      'Remove Family Member': 'परिवार के सदस्य को हटाएं',
      'Add Health Data for {name}': '{name} के लिए स्वास्थ्य डेटा जोड़ें',
      'Date: {date}': 'तारीख: {date}',
      'Blood Pressure': 'रक्तचाप',
      'Blood Sugar': 'रक्त शर्करा',
      'Heart Rate': 'हृदय गति',
      'Sleep (hours)': 'नींद (घंटे)',
      'Notes (optional)': 'नोट्स (वैकल्पिक)',
      'added to family': '{name} को परिवार में जोड़ा गया',
      'Remove {name} and all their health data?': '{name} और उनका सारा स्वास्थ्य डेटा हटाएं?',
      'Hospital': 'अस्पताल',
      'Pharmacy': 'फार्मेसी',
      'Ambulance': 'एम्बुलेंस',
      'places found': 'स्थान मिले',
      'You': 'आप',
      'Getting your GPS location...': 'आपका GPS स्थान मिल रहा है...',
      'Please wait while we find where you are': 'जब तक हम आपका स्थान पता लगाएं कृपया प्रतीक्षा करें',
      'Navigation started! Map follows your location.': 'नेविगेशन शुरू! मानचित्र आपके स्थान का अनुसरण कर रहा है.',
      'Neck Stretches': 'गर्दन स्ट्रेच',
      'Finger Bends': 'उंगली मोड़',
      'Shoulder Shrugs': 'कंधे श्रग',
      'Seated Marching': 'कुर्सी पर चलना',
      'Arm Circles': 'बाजू के गोले',
      'Chair Squats': 'कुर्सी स्क्वाट',
      'Ankle Rotations': 'टखना घुमाना',
      'Cat-Cow Stretch': 'बिल्ली-गाय स्ट्रेच',
      'Knee-to-Chest': 'घुटना-सीना',
      'Quad Sets': 'क्वाड सेट',
      'Seated Leg Raises': 'कुर्सी पर पैर उठाना',
      'Step-ups': 'सीढ़ी चढ़ना',
      'Standing Side Bends': 'खड़े होकर बगल झुकना',
      'Seated Exercises': 'कुर्सी व्यायाम',
      'Neck Exercises': 'गर्दन व्यायाम',
      'Abdominal Massage': 'पेट की मालिश',
      'Gentle Neck Rolls': 'धीरे गर्दन घुमाना',
      'Pursed Lip Breathing': 'होंठ सिकोड़कर सांस लेना',
      'Health Report': 'स्वास्थ्य रिपोर्ट',
      'Export monthly health data as PDF': 'मासिक स्वास्थ्य डेटा को PDF के रूप में निर्यात करें',
      'Generating health report...': 'स्वास्थ्य रिपोर्ट बना रहे हैं...',
      'Error generating report': 'रिपोर्ट बनाने में त्रुटि',
      'Water Intake': 'पानी का सेवन',
      'glasses': 'गिलास',
      'Set Water Goal': 'पानी का लक्ष्य सेट करें',
      'Remove glass': 'गिलास हटाएं',
      'Add glass': 'गिलास जोड़ें',
      '250ml per glass': 'प्रति गिलास 250ml',
      'Goal reached!': 'लक्ष्य पूरा हुआ!',
      'remaining': 'शेष',
      'Water goal reached! Great job staying hydrated!': 'पानी का लक्ष्य पूरा!',
    },
    'Marathi': {
      'Caregiver Access': 'देखभालकर्ता प्रवेश',
      'Continue': 'सुरू ठेवा',
      'Create account': 'खाते तयार करा',
      'Home': 'मुख्यपृष्ठ',
      'SOS': 'SOS',
      'Health': 'आरोग्य',
      'Emergency status': 'आपत्कालीन स्थिती',
      'Stable': 'स्थिर',
      'Emergency SOS': 'आपत्कालीन SOS',
      'Today\'s health snapshot': 'आजचा आरोग्य सारांश',
      'Care route': 'देखभाल मार्ग',
      'Medicine reminder': 'औषध स्मरणपत्र',
      'AI Health Assistant': 'AI आरोग्य सहाय्यक',
      'Caregiver settings': 'देखभालकर्ता सेटिंग्ज',
      'Sign out': 'साइन आउट',
      'Medicine name': 'औषधाचे नाव',
      'Time': 'वेळ',
      'Submit reminder': 'स्मरणपत्र सबमिट करा',
      'Enter medicine and time': 'औषध आणि वेळ टाका',
      'Reminder saved': 'स्मरणपत्र जतन केले',
      'Delete reminder': 'स्मरणपत्र हटवा',
      'Get guidance': 'मार्गदर्शन मिळवा',
      'Blood group': 'रक्तगट',
      'Allergies': 'अॅलर्जी',
      'Contact': 'संपर्क',
      'Voice input': 'व्हॉइस इनपुट',
      'Guidance summary': 'मार्गदर्शन सारांश',
      'Send SOS Now': 'आता SOS पाठवा',
      'Nearby healthcare services': 'जवळच्या आरोग्य सेवा',
      'Save record': 'नोंद जतन करा',
      'Saving...': 'जतन होत आहे...',
      'Today': 'आज',
      'Weight': 'वजन',
      'Height': 'उंची',
      'Not set': 'सेट केलेले नाही',
      'None': 'काही नाही',
      'Screen time today': 'आजचा स्क्रीन वेळ',
      'hours': 'तास',
      'Emergency contact': 'आपत्कालीन संपर्क',
      'Edit emergency contact': 'आपत्कालीन संपर्क संपादित करा',
      'Call Emergency Contact': 'आपत्कालीन संपर्काला कॉल करा',
      'Enter data': 'डेटा टाका',
      'Register as Donor': 'दाता म्हणून नोंदणी करा',
      'Register': 'नोंदणी करा',
      'Available Donors': 'उपलब्ध दाते',
      'Blood Donation': 'रक्तदान',
      'Describe your symptoms or ask for first aid guidance':
          'तुमची लक्षणे सांगा किंवा प्राथमिक उपचार मार्गदर्शन विचारा',
      'Map': 'नकाशा',
      'Find nearby care': 'जवळील काळजी शोधा',
      'Distance': 'अंतर',
      'ETA': 'अंदाजे वेळ',
      'Stop Navigation': 'नेव्हिगेशन थांबवा',
      'Start Navigation': 'नेव्हिगेशन सुरू करा',
      'Following your location...': 'तुमचे स्थान पाठला लागत आहे...',
      'Daily Exercises': 'दैनिक व्यायाम',
      'Based on your conditions': 'तुमच्या परिस्थितीनुसार',
      'All exercises done today! Keep the streak alive tomorrow!': 'आज सर्व व्यायाम पूर्ण झाले! उद्या देखील चालू ठेवा!',
      'Connect Smartwatch': 'स्मार्टवॉच कनेक्ट करा',
      'Find Hospitals & Pharmacies Near You': 'तुमच्या जवळ रुग्णालय आणि औषधालय शोधा',
      'Walking': 'चालणे',
      'Stretching': 'स्ट्रेचिंग',
      'Deep Breathing': 'खोल श्वास',
      'Brisk Walking': 'जलद चालणे',
      'Gentle Walking': 'मंद चाल',
      'Meditation': 'ध्यान',
      'Yoga': 'योग',
      'Yoga Stretching': 'योग स्ट्रेचिंग',
      'Cycling': 'सायक्लिंग',
      'Jumping Jacks': 'जम्पिंग जॅक्स',
      'Streak': 'स्ट्रीक',
      'days': 'दिवस',
      "day streak! Champions don't quit!": 'दिवस स्ट्रीक! चॅम्पियन सोडत नाहीत!',
      "days strong! Don't break the chain!": 'दिवस मजबूत! चेन तोडू नका!',
      "days! Almost a week - keep pushing!": 'दिवस! जवळजवळ एक आठवडा - सुरू ठेवा!',
      "day streak started! Build the habit!": 'स्ट्रीक सुरू झाली! सवय वाढवा!',
      'done today. Start your streak now!': 'आज पूर्ण झाले! आता तुमची स्ट्रीक सुरू करा!',
      'Refresh location': 'स्थान रिफ्रेश करा',
      'Show Route on Map': 'नकाशावर मार्ग दाखवा',
      'All': 'सर्व',
      'Dark Mode': 'डार्क मोड',
      'Dark theme active': 'डार्क थीम सक्रिय',
      'Light theme active': 'लाइट थीम सक्रिय',
      'Set Step Goal': 'पायऱी ध्येय सेट करा',
      'steps': 'पायऱी',
      'Cancel': 'रद्द करा',
      'Save': 'जतन करा',
      'day streak': 'दिवस स्ट्रीक',
      'best': 'सर्वोत्तम',
      'Retry — Get My Location': 'पुन्हा प्रयत्न करा — माझे स्थान मिळवा',
      'Getting your GPS location...': 'GPS स्थान मिळवत आहे...',
      'Please wait while we find where you are': 'तुम्ही कुठे आहात ते शोधताना कृपया थांबा',
      'Navigation started! Map follows your location.': 'नेव्हिगेशन सुरू! नकाशा तुमच्या स्थानाचा पाठला लागत आहे.',
      'Trigger SOS?': 'SOS ट्रिगर करायचे?',
      'SEND SOS': 'SOS पाठवा',
      'Emergency Broadcast?': 'आपत्कालीन प्रसारण?',
      'BROADCAST NOW': 'आत्ता प्रसारित करा',
      'Edit Health Profile': 'आरोग्य प्रोफाइल संपादित करा',
      'Blood Group': 'रक्त गट',
      'Allergies': 'अॅलर्जी',
      'Diseases / Conditions': 'आजार / स्थिती',
      'Weight (kg)': 'वजन (किलो)',
      'Height (cm)': 'उंची (सेमी)',
      'How to use AI Assistant': 'AI सहाय्यक कसे वापरावे',
      'Got it': 'समजले',
      'How to use': 'कसे वापरावे',
      'Family Health Dashboard': 'कुटुंब आरोग्य डॅशबोर्ड',
      'Add family member': 'कुटुंब सदस्य जोडा',
      'Add Family Member': 'कुटुंब सदस्य जोडा',
      'No family members yet': 'अजून कुटुंब सदस्य नाहीत',
      'Add family members to monitor their health': 'त्यांच्या आरोग्याचा मोनिटरिंग करण्यासाठी कुटुंब सदस्य जोडा',
      'Health Info': 'आरोग्य माहिती',
      'View Health History': 'आरोग्य इतिहास पहा',
      'Full Name': 'पूर्ण नाव',
      'Relationship': 'नातेवाईक',
      'Email (optional)': 'ईमेल (पर्यायी)',
      'Email': 'ईमेल',
      'Age': 'वय',
      'Phone': 'फोन',
      'Add Member': 'सदस्य जोडा',
      'Name is required': 'नाव आवश्यक आहे',
      'Edit': 'संपादित करा',
      'Remove': 'काढा',
      'Remove Family Member': 'कुटुंब सदस्य काढा',
      'Add Health Data for {name}': '{name} साठी आरोग्य डेटा जोडा',
      'Date: {date}': 'तारीख: {date}',
      'Blood Pressure': 'रक्तदाब',
      'Blood Sugar': 'रक्तातील साखर',
      'Heart Rate': 'हृदयाचा ठोका',
      'Sleep (hours)': 'झोप (तास)',
      'Notes (optional)': 'टिपा (पर्यायी)',
      'added to family': '{name} ला कुटुंबात जोडले',
      'Remove {name} and all their health data?': '{name} आणि त्यांचा सारा आरोग्य डेटा काढायचा?',
      'Hospital': 'रुग्णालय',
      'Pharmacy': 'औषधालय',
      'Ambulance': 'एम्ब्युलन्स',
      'places found': 'ठिकाणे सापडली',
      'You': 'तुम्ही',
      'Getting your GPS location...': 'तुमचे GPS स्थान मिळवत आहे...',
      'Please wait while we find where you are': 'तुम्ही कुठे आहात ते शोधताना कृपया थांबा',
      'Navigation started! Map follows your location.': 'नेव्हिगेशन सुरू! नकाशा तुमच्या स्थानाचा पाठला लागत आहे.',
      'Neck Stretches': 'मानेचे स्ट्रेच',
      'Finger Bends': 'बोटे मोडणे',
      'Shoulder Shrugs': 'खांदे उचलणे',
      'Seated Marching': 'खुर्चीवर चालणे',
      'Arm Circles': 'बाहुले फिरवणे',
      'Chair Squats': 'खुर्ची स्क्वॅट',
      'Ankle Rotations': 'गुडघा फिरवणे',
      'Cat-Cow Stretch': 'मांजर-गाय स्ट्रेच',
      'Knee-to-Chest': 'गुडघा-छाती',
      'Quad Sets': 'क्वॉड सेट',
      'Seated Leg Raises': 'खुर्चीवर पाय उचलणे',
      'Step-ups': 'पायरी चढणे',
      'Standing Side Bends': 'उभे राहून बाजू वाकणे',
      'Seated Exercises': 'खुर्ची व्यायाम',
      'Neck Exercises': 'मानेचे व्यायाम',
      'Abdominal Massage': 'पोट मसाज',
      'Gentle Neck Rolls': 'मंद मानेचे फिरवणे',
      'Pursed Lip Breathing': 'ओठ सुटकरून श्वास घेणे',
      'Health Report': 'आरोग्य अहवाल',
      'Export monthly health data as PDF': 'मासिक आरोग्य डेटा PDF म्हणून निर्यात करा',
      'Generating health report...': 'आरोग्य अहवाल तयार करत आहे...',
      'Error generating report': 'अहवाल तयार करण्यात त्रुटी',
      'Water Intake': 'पाणी वापर',
      'glasses': 'ग्लास',
      'Set Water Goal': 'पाणी लक्ष्य सेट करा',
      'Remove glass': 'ग्लास काढा',
      'Add glass': 'ग्लास जोडा',
      '250ml per glass': 'प्रत्येक ग्लास 250ml',
      'Goal reached!': 'लक्ष्य पूर्ण!',
      'remaining': 'उर्वरित',
      'Water goal reached! Great job staying hydrated!': 'पाणी लक्ष्य पूर्ण!',
    },
    'Urdu': {
      'Caregiver Access': 'نگہداشت کنندہ رسائی',
      'Continue': 'جاری رکھیں',
      'Create account': 'اکاؤنٹ بنائیں',
      'Home': 'ہوم',
      'SOS': 'SOS',
      'Health': 'صحت',
      'Emergency status': 'ہنگامی حالت',
      'Stable': 'مستحکم',
      'Emergency SOS': 'ہنگامی SOS',
      'Today\'s health snapshot': 'آج کی صحت کا خلاصہ',
      'Care route': 'دیکھ بھال کا راستہ',
      'Medicine reminder': 'ادویات کی یاد دہانی',
      'AI Health Assistant': 'AI صحت معاون',
      'Caregiver settings': 'نگہداشت کنندہ کی ترتیبات',
      'Sign out': 'سائن آؤٹ',
      'Medicine name': 'دوا کا نام',
      'Time': 'وقت',
      'Submit reminder': 'یاد دہانی جمع کریں',
      'Enter medicine and time': 'دوا اور وقت درج کریں',
      'Reminder saved': 'یاد دہانی محفوظ ہو گئی',
      'Delete reminder': 'یاد دہانی حذف کریں',
      'Get guidance': 'رہنمائی حاصل کریں',
      'Blood group': 'بلڈ گروپ',
      'Allergies': 'الرجی',
      'Contact': 'رابطہ',
      'Voice input': 'آواز ان پٹ',
      'Guidance summary': 'رہنمائی کا خلاصہ',
      'Send SOS Now': 'ابھی SOS بھیجیں',
      'Nearby healthcare services': 'قریبی صحت کی خدمات',
      'Save record': 'ریکارڈ محفوظ کریں',
      'Saving...': 'محفوظ ہو رہا ہے...',
      'Today': 'آج',
      'Weight': 'وزن',
      'Height': 'اونچائی',
      'Not set': 'سیٹ نہیں',
      'None': 'کوئی نہیں',
      'Screen time today': 'آج کا اسکرین وقت',
      'hours': 'گھنٹے',
      'Emergency contact': 'ہنگامی رابطہ',
      'Edit emergency contact': 'ہنگامی رابطہ ترمیم کریں',
      'Call Emergency Contact': 'ہنگامی رابطہ پر کال کریں',
      'Enter data': 'ڈیٹا درج کریں',
      'Register as Donor': 'ڈونر کے طور پر رجسٹر کریں',
      'Register': 'رجسٹر کریں',
      'Available Donors': 'دستیاب ڈونرز',
      'Blood Donation': 'خون کا عطیہ',
      'Describe your symptoms or ask for first aid guidance':
          'اپنی علامات بیان کریں یا ابتدائی طبی امداد کی رہنمائی پوچھیں',
      'Map': 'نقشه',
      'Find nearby care': 'قریب کی دیکھ بھال تلاش کریں',
      'Distance': 'فاصلہ',
      'ETA': 'تخمینی وقت',
      'Stop Navigation': 'نیویگیشن بند کریں',
      'Start Navigation': 'نیویگیشن شروع کریں',
      'Following your location...': 'آپ کی جگہ کی پیروی کر رہا ہے...',
      'Daily Exercises': 'روزانہ ورزش',
      'Based on your conditions': 'آپ کی صورتحال کی بنیاد پر',
      'All exercises done today! Keep the streak alive tomorrow!': 'آج تمام ورزشیں مکمل ہو گئیں! کل بھی جاری رکھیں!',
      'Connect Smartwatch': 'اسمارٹ واچ کنیکٹ کریں',
      'Find Hospitals & Pharmacies Near You': 'اپنے قریب ہسپتال اور فارمیسی تلاش کریں',
      'Walking': 'چلنا',
      'Stretching': 'سٹریچنگ',
      'Deep Breathing': 'گہری سانس',
      'Brisk Walking': 'تیز چلنا',
      'Gentle Walking': 'ہلکی چال',
      'Meditation': 'مراقبہ',
      'Yoga': 'یوگا',
      'Yoga Stretching': 'یوگا سٹریچنگ',
      'Cycling': 'سائیکلنگ',
      'Jumping Jacks': 'جنگنگ جیکس',
      'Streak': 'سٹریک',
      'days': 'دن',
      "day streak! Champions don't quit!": 'دن سٹریک! چیمپئنز چھوڑتے نہیں!',
      "days strong! Don't break the chain!": 'دن مضبوط! زنجیر مت توڑیں!',
      "days! Almost a week - keep pushing!": 'دن! تقریباً ایک ہفتہ - جاری رکھیں!',
      "day streak started! Build the habit!": 'دن سٹریک شروع ہوئی! عادت بنائیں!',
      'done today. Start your streak now!': 'آج مکمل ہوا۔ اب اپنی سٹریک شروع کریں!',
      'Refresh location': '.location تازہ کریں',
      'Show Route on Map': 'نقشه پر راستہ دکھائیں',
      'All': 'سب',
      'Dark Mode': 'ڈارک موڈ',
      'Dark theme active': 'ڈارک تھیم فعال',
      'Light theme active': 'لائٹ تھیم فعال',
      'Set Step Goal': 'قدم کا مقصد مقرر کریں',
      'steps': 'قدم',
      'Cancel': 'منسوخ کریں',
      'Save': 'محفوظ کریں',
      'day streak': 'دن سٹریک',
      'best': 'بہترین',
      'Retry — Get My Location': 'دوبارہ کوشش کریں — میری جگہ حاصل کریں',
      'Getting your GPS location...': 'GPS جگہ مل رہی ہے...',
      'Please wait while we find where you are': 'آپ کہاں ہیں وہ تلاش کرتے وقت مہربانی کر کے انتظار کریں',
      'Navigation started! Map follows your location.': 'نیویگیشن شروع! نقشه آپ کی جگہ کی پیروی کر رہا ہے.',
      'Trigger SOS?': 'SOS محفوظ کریں؟',
      'SEND SOS': 'SOS بھیجیں',
      'Emergency Broadcast?': 'ہنگامی نشریات؟',
      'BROADCAST NOW': 'ابھی نشریات کریں',
      'Edit Health Profile': 'صحت پروفائل میں ترمیم',
      'Blood Group': 'خون کا گروہ',
      'Allergies': 'الرژی',
      'Diseases / Conditions': 'بیماریاں / حالتیں',
      'Weight (kg)': 'وزن (کلو)',
      'Height (cm)': 'قد (سینٹی میٹر)',
      'How to use AI Assistant': 'AI معاون کو کیسے استعمال کریں',
      'Got it': 'سمجھ آگیا',
      'How to use': 'کیسے استعمال کریں',
      'Family Health Dashboard': 'خاندانی صحت ڈیش بورڈ',
      'Add family member': 'خاندان کا رکن شامل کریں',
      'Add Family Member': 'خاندان کا رکن شامل کریں',
      'No family members yet': 'ابھی تک کوئی خاندان کا رکن نہیں',
      'Add family members to monitor their health': 'ان کی صحت کی نگرانی کے لیے خاندان کے افراد شامل کریں',
      'Health Info': 'صحت کی معلومات',
      'View Health History': 'صحت کی تاریخ دیکھیں',
      'Full Name': 'پورا نام',
      'Relationship': 'رشتہ',
      'Email (optional)': 'ای میل (اختیاری)',
      'Email': 'ای میل',
      'Age': 'عمر',
      'Phone': 'فون',
      'Add Member': 'رکن شامل کریں',
      'Name is required': 'نام ضروری ہے',
      'Edit': 'ترمیم',
      'Remove': 'ہٹائیں',
      'Remove Family Member': 'خاندان کا رکن ہٹائیں',
      'Add Health Data for {name}': '{name} کے لیے صحت ڈیٹا شامل کریں',
      'Date: {date}': 'تاریخ: {date}',
      'Blood Pressure': 'بلڈ پریشر',
      'Blood Sugar': 'خون میں شوگر',
      'Heart Rate': 'دل کی دھڑکن',
      'Sleep (hours)': 'نیند (گھنٹے)',
      'Notes (optional)': 'نوٹس (اختیاری)',
      'added to family': '{name} کو خاندان میں شامل کیا گیا',
      'Remove {name} and all their health data?': '{name} اور ان کا سارا صحت ڈیٹا ہٹائیں؟',
      'Hospital': 'ہسپتال',
      'Pharmacy': 'فارمیسی',
      'Ambulance': 'ایمبولینس',
      'places found': 'جگہیں ملیں',
      'You': 'آپ',
      'Getting your GPS location...': 'آپ کا GPS location مل رہا ہے...',
      'Please wait while we find where you are': 'آپ کہاں ہیں وہ تلاش کرتے وقت مہربانی کر کے انتظار کریں',
      'Navigation started! Map follows your location.': 'نیویگیشن شروع! نقشه آپ کی جگہ کی پیروی کر رہا ہے.',
      'Neck Stretches': 'گردن کی سٹریچ',
      'Finger Bends': 'انگلیاں موڑنا',
      'Shoulder Shrugs': 'کندھے اٹھانا',
      'Seated Marching': 'کرسی پر چلنا',
      'Arm Circles': 'بازو گھمانا',
      'Chair Squats': 'کرسی اسکواٹ',
      'Ankle Rotations': 'گھٹنا گھمانا',
      'Cat-Cow Stretch': 'بلی گائے سٹریچ',
      'Knee-to-Chest': 'گھٹنا سینہ',
      'Quad Sets': 'کواڈ سیٹس',
      'Seated Leg Raises': 'کرسی پر پاؤں اٹھانا',
      'Step-ups': 'سیڑھی چڑھنا',
      'Standing Side Bends': 'کھڑے ہو کر جھکنا',
      'Seated Exercises': 'کرسی ورزش',
      'Neck Exercises': 'گردن ورزش',
      'Abdominal Massage': 'پیٹ کی مالش',
      'Gentle Neck Rolls': 'ہلکی گردن گھمانا',
      'Pursed Lip Breathing': 'ہونٹ سیکھ کر سانس لینا',
      'Health Report': 'صحت رپورٹ',
      'Export monthly health data as PDF': 'ماہانہ صحت ڈیٹا PDF کے طور پر برآمد کریں',
      'Generating health report...': 'صحت رپورٹ بنا رہے ہیں...',
      'Error generating report': 'رپورٹ بنانے میں خرابی',
      'Water Intake': 'پانی کا استعمال',
      'glasses': 'گلاس',
      'Set Water Goal': 'پانی کا ہدف مقرر کریں',
      'Remove glass': 'گلاس ہٹائیں',
      'Add glass': 'گلاس شامل کریں',
      '250ml per glass': 'فی گلاس 250ml',
      'Goal reached!': 'ہدف پورا ہوا!',
      'remaining': 'باقی',
      'Water goal reached! Great job staying hydrated!': 'پانی کا ہدف پورا!',
    },
    'French': {
      'Caregiver Access': 'Accès aidant',
      'Continue': 'Continuer',
      'Create account': 'Créer un compte',
      'Home': 'Accueil',
      'SOS': 'SOS',
      'Health': 'Santé',
      'Emergency status': 'État d\'urgence',
      'Stable': 'Stable',
      'Emergency SOS': 'SOS d\'urgence',
      'Today\'s health snapshot': 'Résumé santé du jour',
      'Care route': 'Parcours de soins',
      'Medicine reminder': 'Rappel de médicament',
      'AI Health Assistant': 'Assistant santé IA',
      'Caregiver settings': 'Paramètres de l\'aidant',
      'Sign out': 'Déconnexion',
      'Medicine name': 'Nom du médicament',
      'Time': 'Heure',
      'Submit reminder': 'Valider le rappel',
      'Enter medicine and time': 'Saisissez le médicament et l\'heure',
      'Reminder saved': 'Rappel enregistré',
      'Delete reminder': 'Supprimer le rappel',
      'Get guidance': 'Obtenir des conseils',
      'Blood group': 'Groupe sanguin',
      'Allergies': 'Allergies',
      'Contact': 'Contact',
      'Voice input': 'Saisie vocale',
      'Guidance summary': 'Résumé des conseils',
      'Send SOS Now': 'Envoyer le SOS',
      'Nearby healthcare services': 'Services de santé à proximité',
      'Save record': 'Enregistrer le dossier',
      'Saving...': 'Enregistrement...',
      'Today': 'Aujourd\'hui',
      'Weight': 'Poids',
      'Height': 'Taille',
      'Not set': 'Non défini',
      'None': 'Aucun',
      'Screen time today': 'Temps d\'écran aujourd\'hui',
      'hours': 'heures',
      'Emergency contact': 'Contact d\'urgence',
      'Edit emergency contact': 'Modifier le contact d\'urgence',
      'Call Emergency Contact': 'Appeler le contact d\'urgence',
      'Enter data': 'Saisir les données',
      'Register as Donor': 'S\'inscrire comme donneur',
      'Register': 'S\'inscrire',
      'Available Donors': 'Donneurs disponibles',
      'Blood Donation': 'Don du sang',
      'Describe your symptoms or ask for first aid guidance':
          'Décrivez vos symptômes ou demandez des conseils de premiers secours',
      'Map': 'Carte',
      'Find nearby care': 'Trouver des soins à proximité',
      'Distance': 'Distance',
      'ETA': 'Temps estimé',
      'Stop Navigation': 'Arrêter la navigation',
      'Start Navigation': 'Démarrer la navigation',
      'Following your location...': 'Suivant votre position...',
      'Daily Exercises': 'Exercices quotidiens',
      'Based on your conditions': 'Selon votre état',
      'All exercises done today! Keep the streak alive tomorrow!': 'Tous les exercices terminés! Continuez demain!',
      'Connect Smartwatch': 'Connecter la montre connectée',
      'Find Hospitals & Pharmacies Near You': 'Trouver hôpitaux et pharmacies près de chez vous',
      'Walking': 'Marche',
      'Stretching': 'Étirement',
      'Deep Breathing': 'Respiration profonde',
      'Brisk Walking': 'Marche rapide',
      'Gentle Walking': 'Marche douce',
      'Meditation': 'Méditation',
      'Yoga': 'Yoga',
      'Yoga Stretching': 'Étirement yoga',
      'Cycling': 'Vélo',
      'Jumping Jacks': 'Jumping Jacks',
      'Streak': 'Série',
      'days': 'jours',
      "day streak! Champions don't quit!": 'jour de série! Les champions n\'abandonnent pas!',
      "days strong! Don't break the chain!": 'jours forts! Ne brisez pas la chaîne!',
      "days! Almost a week - keep pushing!": 'jours! Presque une semaine - continuez!',
      "day streak started! Build the habit!": 'jour de série commencé! Créez l\'habitude!',
      'done today. Start your streak now!': 'terminés aujourd\'hui! Commencez votre série maintenant!',
      'Refresh location': 'Actualiser la position',
      'Show Route on Map': 'Afficher l\'itinéraire sur la carte',
      'All': 'Tout',
      'Dark Mode': 'Mode sombre',
      'Dark theme active': 'Thème sombre actif',
      'Light theme active': 'Thème clair actif',
      'Set Step Goal': 'Définir l\'objectif de pas',
      'steps': 'pas',
      'Cancel': 'Annuler',
      'Save': 'Enregistrer',
      'day streak': 'jours de série',
      'best': 'meilleur',
      'Retry — Get My Location': 'Réessayer — Obtenir ma position',
      'Getting your GPS location...': 'Obtention de votre position GPS...',
      'Please wait while we find where you are': 'Veuillez patienter pendant que nous trouvons votre position',
      'Navigation started! Map follows your location.': 'Navigation démarrée! La carte suit votre position.',
      'Trigger SOS?': 'Déclencher SOS ?',
      'SEND SOS': 'ENVOYER SOS',
      'Emergency Broadcast?': 'Diffusion d\'urgence ?',
      'BROADCAST NOW': 'DIFFUSER MAINTENANT',
      'Edit Health Profile': 'Modifier le profil de santé',
      'Blood Group': 'Groupe sanguin',
      'Allergies': 'Allergies',
      'Diseases / Conditions': 'Maladies / Affections',
      'Weight (kg)': 'Poids (kg)',
      'Height (cm)': 'Taille (cm)',
      'How to use AI Assistant': 'Comment utiliser l\'assistant IA',
      'Got it': 'Compris',
      'How to use': 'Comment utiliser',
      'Family Health Dashboard': 'Tableau de bord santé familiale',
      'Add family member': 'Ajouter un membre de la famille',
      'Add Family Member': 'Ajouter un membre de la famille',
      'No family members yet': 'Pas encore de membres de la famille',
      'Add family members to monitor their health': 'Ajoutez des membres de la famille pour surveiller leur santé',
      'Health Info': 'Informations de santé',
      'View Health History': 'Voir l\'historique de santé',
      'Full Name': 'Nom complet',
      'Relationship': 'Relation',
      'Email (optional)': 'E-mail (facultatif)',
      'Email': 'E-mail',
      'Age': 'Âge',
      'Phone': 'Téléphone',
      'Add Member': 'Ajouter un membre',
      'Name is required': 'Le nom est requis',
      'Edit': 'Modifier',
      'Remove': 'Supprimer',
      'Remove Family Member': 'Supprimer le membre de la famille',
      'Add Health Data for {name}': 'Ajouter des données de santé pour {name}',
      'Date: {date}': 'Date: {date}',
      'Blood Pressure': 'Pression artérielle',
      'Blood Sugar': 'Sucre dans le sang',
      'Heart Rate': 'Fréquence cardiaque',
      'Sleep (hours)': 'Sommeil (heures)',
      'Notes (optional)': 'Notes (facultatif)',
      'added to family': '{name} ajouté à la famille',
      'Remove {name} and all their health data?': 'Supprimer {name} et toutes leurs données de santé ?',
      'Hospital': 'Hôpital',
      'Pharmacy': 'Pharmacie',
      'Ambulance': 'Ambulance',
      'places found': 'lieux trouvés',
      'You': 'Vous',
      'Getting your GPS location...': 'Obtention de votre position GPS...',
      'Please wait while we find where you are': 'Veuillez patienter pendant que nous trouvons votre position',
      'Navigation started! Map follows your location.': 'Navigation démarrée! La carte suit votre position.',
      'Neck Stretches': 'Étirements du cou',
      'Finger Bends': 'Flexions des doigts',
      'Shoulder Shrugs': ' haussements d\'épaules',
      'Seated Marching': 'Marche assise',
      'Arm Circles': 'Cercles de bras',
      'Chair Squats': 'Squats sur chaise',
      'Ankle Rotations': 'Rotations de cheville',
      'Cat-Cow Stretch': 'Étirement Chèvre-Vache',
      'Knee-to-Chest': 'Genou-poitrine',
      'Quad Sets': 'Sets de quadriceps',
      'Seated Leg Raises': 'Élévations de jambes assis',
      'Step-ups': 'Montées de marche',
      'Standing Side Bends': 'Inclinaisons latérales debout',
      'Seated Exercises': 'Exercices assis',
      'Neck Exercises': 'Exercices du cou',
      'Abdominal Massage': 'Massage abdominal',
      'Gentle Neck Rolls': 'Rotations douces du cou',
      'Pursed Lip Breathing': 'Respiration à lèvres pincées',
      'Health Report': 'Rapport de santé',
      'Export monthly health data as PDF': 'Exporter les données de santé mensuelles en PDF',
      'Generating health report...': 'Génération du rapport de santé...',
      'Error generating report': 'Erreur lors de la génération du rapport',
      'Water Intake': 'Consommation d’eau',
      'glasses': 'verres',
      'Set Water Goal': 'Définir l’objectif d’eau',
      'Remove glass': 'Retirer un verre',
      'Add glass': 'Ajouter un verre',
      '250ml per glass': '250ml par verre',
      'Goal reached!': 'Objectif atteint !',
      'remaining': 'restant',
      'Water goal reached! Great job staying hydrated!': 'Objectif d’eau atteint !',
    },
    'Japanese': {
      'Caregiver Access': '介護者アクセス',
      'Continue': '続行',
      'Create account': 'アカウントを作成',
      'Home': 'ホーム',
      'SOS': 'SOS',
      'Health': '健康',
      'Emergency status': '緊急状態',
      'Stable': '安定',
      'Emergency SOS': '緊急 SOS',
      'Today\'s health snapshot': '今日の健康概要',
      'Care route': 'ケア経路',
      'Medicine reminder': '服薬リマインダー',
      'AI Health Assistant': 'AI 健康アシスタント',
      'Caregiver settings': '介護者設定',
      'Sign out': 'サインアウト',
      'Medicine name': '薬の名前',
      'Time': '時刻',
      'Submit reminder': 'リマインダーを送信',
      'Enter medicine and time': '薬と時刻を入力してください',
      'Reminder saved': 'リマインダーを保存しました',
      'Delete reminder': 'リマインダーを削除',
      'Get guidance': 'ガイダンスを取得',
      'Blood group': '血液型',
      'Allergies': 'アレルギー',
      'Contact': '連絡先',
      'Voice input': '音声入力',
      'Guidance summary': 'ガイダンス概要',
      'Send SOS Now': '今すぐ SOS を送信',
      'Nearby healthcare services': '近くの医療サービス',
      'Save record': '記録を保存',
      'Saving...': '保存中...',
      'Today': '今日',
      'Weight': '体重',
      'Height': '身長',
      'Not set': '未設定',
      'None': 'なし',
      'Screen time today': '今日のスクリーンタイム',
      'hours': '時間',
      'Emergency contact': '緊急連絡先',
      'Edit emergency contact': '緊急連絡先を編集',
      'Call Emergency Contact': '緊急連絡先に電話',
      'Enter data': 'データを入力',
      'Register as Donor': 'ドナーとして登録',
      'Register': '登録',
      'Available Donors': '利用可能なドナー',
      'Blood Donation': '献血',
      'Describe your symptoms or ask for first aid guidance':
          '症状を説明するか、応急処置の案内を尋ねてください',
      'Map': '地図',
      'Find nearby care': '近隣の医療を探す',
      'Distance': '距離',
      'ETA': '到着予定時間',
      'Stop Navigation': 'ナビゲーションを停止',
      'Start Navigation': 'ナビゲーションを開始',
      'Following your location...': '位置を追跡中...',
      'Daily Exercises': '毎日の運動',
      'Based on your conditions': 'あなたの状態に基づいて',
      'All exercises done today! Keep the streak alive tomorrow!': '今日の運動すべて完了！明日も続けましょう！',
      'Connect Smartwatch': 'スマートウォッチを接続',
      'Find Hospitals & Pharmacies Near You': '近くの病院と薬局を探す',
      'Walking': 'ウォーキング',
      'Stretching': 'ストレッチ',
      'Deep Breathing': '深呼吸',
      'Brisk Walking': '早歩き',
      'Gentle Walking': 'ゆっくり歩く',
      'Meditation': '瞑想',
      'Yoga': 'ヨガ',
      'Yoga Stretching': 'ヨガストレッチ',
      'Cycling': 'サイクリング',
      'Jumping Jacks': 'ジャンピングジャック',
      'Streak': '連続',
      'days': '日',
      "day streak! Champions don't quit!": '日連続！チャンピオンは諦めない！',
      "days strong! Don't break the chain!": '日間強い！チェーンを途切れさせないで！',
      "days! Almost a week - keep pushing!": '日！ほぼ一週間 - 続けましょう！',
      "day streak started! Build the habit!": '日連続スタート！習慣を作りましょう！',
      'done today. Start your streak now!': '今日完了！連続を今始めましょう！',
      'Refresh location': '位置を更新',
      'Show Route on Map': '地図にルートを表示',
      'All': 'すべて',
      'Dark Mode': 'ダークモード',
      'Dark theme active': 'ダークテーマ有効',
      'Light theme active': 'ライトテーマ有効',
      'Set Step Goal': '歩数目標を設定',
      'steps': '歩',
      'Cancel': 'キャンセル',
      'Save': '保存',
      'day streak': '日連続',
      'best': '最高',
      'Retry — Get My Location': '再試行 — 位置情報を取得',
      'Getting your GPS location...': 'GPS位置を取得中...',
      'Please wait while we find where you are': '位置を見つけるまでお待ちください',
      'Navigation started! Map follows your location.': 'ナビ開始！地図があなたの位置を追跡します。',
      'Trigger SOS?': 'SOSを発動しますか？',
      'SEND SOS': 'SOSを送信',
      'Emergency Broadcast?': '緊急放送？',
      'BROADCAST NOW': '今すぐ放送',
      'Edit Health Profile': '健康プロフィールを編集',
      'Blood Group': '血液型',
      'Allergies': 'アレルギー',
      'Diseases / Conditions': '病気 / 状態',
      'Weight (kg)': '体重 (kg)',
      'Height (cm)': '身長 (cm)',
      'How to use AI Assistant': 'AIアシスタントの使い方',
      'Got it': '了解',
      'How to use': '使い方',
      'Family Health Dashboard': '家族ヘルスダッシュボード',
      'Add family member': '家族メンバーを追加',
      'Add Family Member': '家族メンバーを追加',
      'No family members yet': 'まだ家族メンバーがいません',
      'Add family members to monitor their health': '健康を監視するために家族メンバーを追加',
      'Health Info': '健康情報',
      'View Health History': '健康履歴を見る',
      'Full Name': 'フルネーム',
      'Relationship': '関係',
      'Email (optional)': 'メール（オプション）',
      'Email': 'メール',
      'Age': '年齢',
      'Phone': '電話',
      'Add Member': 'メンバーを追加',
      'Name is required': '名前は必須です',
      'Edit': '編集',
      'Remove': '削除',
      'Remove Family Member': '家族メンバーを削除',
      'Add Health Data for {name}': '{name}の健康データを追加',
      'Date: {date}': '日付: {date}',
      'Blood Pressure': '血圧',
      'Blood Sugar': '血糖値',
      'Heart Rate': '心拍数',
      'Sleep (hours)': '睡眠（時間）',
      'Notes (optional)': 'メモ（オプション）',
      'added to family': '{name}を家族に追加しました',
      'Remove {name} and all their health data?': '{name}とすべての健康データを削除しますか？',
      'Hospital': '病院',
      'Pharmacy': '薬局',
      'Ambulance': '救急車',
      'places found': '件発見',
      'You': 'あなた',
      'Getting your GPS location...': 'GPS位置を取得中...',
      'Please wait while we find where you are': '位置を見つけるまでお待ちください',
      'Navigation started! Map follows your location.': 'ナビ開始！地図があなたの位置を追跡します。',
      'Neck Stretches': '首ストレッチ',
      'Finger Bends': '指の曲げ伸ばし',
      'Shoulder Shrugs': '肩すくめ',
      'Seated Marching': '座って歩く',
      'Arm Circles': '腕の円運動',
      'Chair Squats': '椅子スクワット',
      'Ankle Rotations': '足首回し',
      'Cat-Cow Stretch': '猫牛ストレッチ',
      'Knee-to-Chest': '膝を胸に',
      'Quad Sets': '大腿四頭筋運動',
      'Seated Leg Raises': '座位での脚上げ',
      'Step-ups': 'ステップアップ',
      'Standing Side Bends': '立位での側弯',
      'Seated Exercises': '座ってできる運動',
      'Neck Exercises': '首の運動',
      'Abdominal Massage': '腹部マッサージ',
      'Gentle Neck Rolls': 'ゆっくり首を回す',
      'Pursed Lip Breathing': '口をすぼめて呼吸',
      'Health Report': '健康レポート',
      'Export monthly health data as PDF': '月間健康データをPDFとしてエクスポート',
      'Generating health report...': '健康レポートを生成中...',
      'Error generating report': 'レポート生成エラー',
      'Water Intake': '水分摂取量',
      'glasses': '杯',
      'Set Water Goal': '水分目標を設定',
      'Remove glass': 'グラスを減らす',
      'Add glass': 'グラスを追加',
      '250ml per glass': '1杯250ml',
      'Goal reached!': '目標達成！',
      'remaining': '残り',
      'Water goal reached! Great job staying hydrated!': '水分目標達成！',
    },
  };

  static const _descriptions = <String, Map<String, String>>{
    'Tamil': {
      'Walk slowly or stretch for 10 minutes. Stop if you feel unwell.':
          '10 நிமிடங்கள் மெதுவாக நடக்கவும் அல்லது நீட்டிக்கவும்.',
      'Take 5 minutes for slow, comfortable breathing.':
          '5 நிமிடங்கள் மெதுவாகவும் வசதியாகவும் சுவாசிக்கவும்.',
      'Drink water and keep fluids nearby today.':
          'தண்ணீர் குடித்து, இன்று திரவங்களை அருகில் வைத்திருக்கவும்.',
      'Vitals are within range. Keep your emergency contact and record ready.':
          'உடல்நல அளவுகள் சரியான நிலையில் உள்ளன.',
      'This may be an emergency. Call emergency services immediately, keep the person calm, and monitor breathing and pulse. If they become unresponsive, begin CPR and seek urgent care without delay.':
          'இது அவசர நிலையாக இருக்கலாம். உடனடியாக அவசர சேவைகளை அழைக்கவும்.',
      'This looks like a common illness. Encourage rest, hydration, and monitor temperature. Seek urgent assessment if symptoms worsen.':
          'இது பொதுவான நோய் போல் தெரிகிறது. ஓய்வு எடுக்கவும்.',
      'Rest in a cool, quiet place and hydrate. Avoid exertion and seek urgent care if the headache is sudden or severe.':
          'குளிர்ந்த, அமைதியான இடத்தில் ஓய்வெடுக்கவும்.',
      'Monitor symptoms closely, stay hydrated, and avoid heavy activity. Seek professional medical help if the issue worsens.':
          'அறிகுறிகளை கவனமாக கண்காணிக்கவும், தண்ணீர் குடிக்கவும்.',
    },
    'Telugu': {
      'Vitals are within range. Keep your emergency contact and record ready.':
          'ఆరోగ్య కొలతలు సాధారణ పరిధిలో ఉన్నాయి.',
      'This may be an emergency. Call emergency services immediately, keep the person calm, and monitor breathing and pulse. If they become unresponsive, begin CPR and seek urgent care without delay.':
          'ఇది అత్యవసర పరిస్థితి కావచ్చు. వెంటనే అత్యవసర సేవలను పిలవండి.',
      'This looks like a common illness. Encourage rest, hydration, and monitor temperature. Seek urgent assessment if symptoms worsen.':
          'ఇది సాధారణ అనారోగ్యంలా కనిపిస్తుంది. విశ్రాంతి తీసుకోండి.',
      'Rest in a cool, quiet place and hydrate. Avoid exertion and seek urgent care if the headache is sudden or severe.':
          'చల్లని, ప్రశాంతమైన చోట విశ్రాంతి తీసుకోండి.',
      'Monitor symptoms closely, stay hydrated, and avoid heavy activity. Seek professional medical help if the issue worsens.':
          'లక్షణాలను గమనించండి, నీరు తాగండి.',
    },
    'Kannada': {
      'Vitals are within range. Keep your emergency contact and record ready.':
          'ಆರೋಗ್ಯ ಅಳತೆಗಳು ಸಾಮಾನ್ಯ ವ್ಯಾಪ್ತಿಯಲ್ಲಿವೆ.',
      'This may be an emergency. Call emergency services immediately, keep the person calm, and monitor breathing and pulse. If they become unresponsive, begin CPR and seek urgent care without delay.':
          'ಇದು ತುರ್ತು ಪರಿಸ್ಥಿತಿಯಾಗಿರಬಹುದು. ತಕ್ಷಣ ತುರ್ತು ಸೇವೆಗಳನ್ನು ಕರೆಯಿರಿ.',
      'This looks like a common illness. Encourage rest, hydration, and monitor temperature. Seek urgent assessment if symptoms worsen.':
          'ಇದು ಸಾಮಾನ್ಯ ಅನಾರೋಗ್ಯದಂತೆ ಕಾಣುತ್ತದೆ. ವಿಶ್ರಾಂತಿ ಪಡೆಯಿರಿ.',
      'Rest in a cool, quiet place and hydrate. Avoid exertion and seek urgent care if the headache is sudden or severe.':
          'ತಂಪಾದ, ಶಾಂತವಾದ ಸ್ಥಳದಲ್ಲಿ ವಿಶ್ರಾಂತಿ ಪಡೆಯಿರಿ.',
      'Monitor symptoms closely, stay hydrated, and avoid heavy activity. Seek professional medical help if the issue worsens.':
          'ಲಕ್ಷಣಗಳನ್ನು ಗಮನಿಸಿ, ನೀರು ಕುಡಿಯಿರಿ.',
    },
    'Malayalam': {
      'Vitals are within range. Keep your emergency contact and record ready.':
          'ആരോഗ്യ അളവുകൾ സാധാരണ പരിധിയിലാണ്.',
      'This may be an emergency. Call emergency services immediately, keep the person calm, and monitor breathing and pulse. If they become unresponsive, begin CPR and seek urgent care without delay.':
          'ഇത് അടിയന്തര സാഹചര്യമാകാം. ഉടൻ അടിയന്തര സേവനങ്ങളെ വിളിക്കുക.',
      'This looks like a common illness. Encourage rest, hydration, and monitor temperature. Seek urgent assessment if symptoms worsen.':
          'ഇത് സാധാരണ അസുഖം പോലെ തോന്നുന്നു. വിശ്രമം എടുക്കുക.',
      'Rest in a cool, quiet place and hydrate. Avoid exertion and seek urgent care if the headache is sudden or severe.':
          'തണുത്ത, ശാന്തമായ സ്ഥലത്ത് വിശ്രമിക്കുക.',
      'Monitor symptoms closely, stay hydrated, and avoid heavy activity. Seek professional medical help if the issue worsens.':
          'ലക്ഷണങ്ങൾ ശ്രദ്ധിക്കുക, വെള്ളം കുടിക്കുക.',
    },
    'Hindi': {
      'Vitals are within range. Keep your emergency contact and record ready.':
          'स्वास्थ्य माप सामान्य सीमा में हैं।',
      'This may be an emergency. Call emergency services immediately, keep the person calm, and monitor breathing and pulse. If they become unresponsive, begin CPR and seek urgent care without delay.':
          'यह आपात स्थिति हो सकती है। तुरंत आपातकालीन सेवाओं को कॉल करें।',
      'This looks like a common illness. Encourage rest, hydration, and monitor temperature. Seek urgent assessment if symptoms worsen.':
          'यह सामान्य बीमारी जैसा लगता है। आराम करें।',
      'Rest in a cool, quiet place and hydrate. Avoid exertion and seek urgent care if the headache is sudden or severe.':
          'ठंडी, शांत जगह पर आराम करें।',
      'Monitor symptoms closely, stay hydrated, and avoid heavy activity. Seek professional medical help if the issue worsens.':
          'लक्षणों पर ध्यान दें, पानी पिएं।',
    },
    'Marathi': {
      'Vitals are within range. Keep your emergency contact and record ready.':
          'आरोग्य वाचा सामान्य मर्यादेत आहेत.',
      'This may be an emergency. Call emergency services immediately, keep the person calm, and monitor breathing and pulse. If they become unresponsive, begin CPR and seek urgent care without delay.':
          'हे आपत्कालीन परिस्थिती असू शकते. लगेच आपत्कालीन सेवांना कॉल करा.',
      'This looks like a common illness. Encourage rest, hydration, and monitor temperature. Seek urgent assessment if symptoms worsen.':
          'हे सामान्य आजारपणा दिसत आहे. आराम करा.',
      'Rest in a cool, quiet place and hydrate. Avoid exertion and seek urgent care if the headache is sudden or severe.':
          'थंड, शांत जागेत आराम करा.',
      'Monitor symptoms closely, stay hydrated, and avoid heavy activity. Seek professional medical help if the issue worsens.':
          'लक्षणे लक्षात ठेवा, पाणी प्या.',
    },
    'Urdu': {
      'Vitals are within range. Keep your emergency contact and record ready.':
          'صحت کے اعداد معمول کی حد میں ہیں۔',
      'This may be an emergency. Call emergency services immediately, keep the person calm, and monitor breathing and pulse. If they become unresponsive, begin CPR and seek urgent care without delay.':
          'یہ ہنگامی صورتحال ہو سکتی ہے۔ فوراً ہنگامی خدمات کو کال کریں۔',
      'This looks like a common illness. Encourage rest, hydration, and monitor temperature. Seek urgent assessment if symptoms worsen.':
          'یہ عام بیماری لگتی ہے۔ آرام کریں۔',
      'Rest in a cool, quiet place and hydrate. Avoid exertion and seek urgent care if the headache is sudden or severe.':
          'ٹھنڈی، پرسکون جگہ پر آرام کریں۔',
      'Monitor symptoms closely, stay hydrated, and avoid heavy activity. Seek professional medical help if the issue worsens.':
          'علامات پر نظر رکھیں، پانی پئیں۔',
    },
    'French': {
      'Vitals are within range. Keep your emergency contact and record ready.':
          'Les constantes sont normales.',
      'This may be an emergency. Call emergency services immediately, keep the person calm, and monitor breathing and pulse. If they become unresponsive, begin CPR and seek urgent care without delay.':
          'Ceci peut être une urgence. Appelez immédiatement les services d\'urgence.',
      'This looks like a common illness. Encourage rest, hydration, and monitor temperature. Seek urgent assessment if symptoms worsen.':
          'Cela ressemble à une maladie courante. Reposez-vous.',
      'Rest in a cool, quiet place and hydrate. Avoid exertion and seek urgent care if the headache is sudden or severe.':
          'Reposez-vous dans un endroit frais et calme.',
      'Monitor symptoms closely, stay hydrated, and avoid heavy activity. Seek professional medical help if the issue worsens.':
          'Surveillez les symptômes, hydratez-vous.',
    },
    'Japanese': {
      'Vitals are within range. Keep your emergency contact and record ready.':
          '健康指標は正常範囲です。',
      'This may be an emergency. Call emergency services immediately, keep the person calm, and monitor breathing and pulse. If they become unresponsive, begin CPR and seek urgent care without delay.':
          'これは緊急事態の可能性があります。すぐに救急サービスに電話してください。',
      'This looks like a common illness. Encourage rest, hydration, and monitor temperature. Seek urgent assessment if symptoms worsen.':
          '一般的な病気のようです。休んでください。',
      'Rest in a cool, quiet place and hydrate. Avoid exertion and seek urgent care if the headache is sudden or severe.':
          '涼しく静かな場所で休んでください。',
      'Monitor symptoms closely, stay hydrated, and avoid heavy activity. Seek professional medical help if the issue worsens.':
          '症状を注意深く確認し、水分を取り、激しい活動を避けてください。',
    },
  };

  static const _guidanceFallback = <String, String>{
    'Tamil': 'அறிகுறிகளை கவனமாக கண்காணிக்கவும், தண்ணீர் குடிக்கவும்.',
    'Telugu': 'లక్షణాలను గమనించండి, నీరు తాగండి.',
    'Kannada': 'ಲಕ್ಷಣಗಳನ್ನು ಗಮನಿಸಿ, ನೀರು ಕುಡಿಯಿರಿ.',
    'Malayalam': 'ലക്ഷണങ്ങൾ ശ്രദ്ധിക്കുക, വെള്ളം കുടിക്കുക.',
    'Hindi': 'लक्षणों पर ध्यान दें, पानी पिएं।',
    'Marathi': 'लक्षणे लक्षात ठेवा, पाणी प्या.',
    'Urdu': 'علامات پر نظر رکھیں، پانی پئیں۔',
    'French': 'Surveillez les symptômes, hydratez-vous.',
    'Japanese': '症状を注意深く確認し、水分を取り。',
  };

  String text(String key) {
    final translated =
        _translations[language]?[key] ??
        _descriptions[language]?[key] ??
        _guidanceFallback[language];
    if (translated != null && key != translated) return translated;
    return key;
  }
}
