class AppLocalizations {
  AppLocalizations(this.language);

  final String language;

  static const supportedLanguages = [
    'English',
    'Tamil',
    'Telugu',
    'Kannada',
    'Malayalam',
    'Hindi',
    'Marathi',
    'Urdu',
    'French',
    'Japanese',
  ];

  static const _translations = <String, Map<String, String>>{
    'Tamil': {
      'Caregiver Access': 'பராமரிப்பாளர் அணுகல்',
      'Continue': 'தொடரவும்',
      'Create account': 'கணக்கை உருவாக்கு',
      'Home': 'முகப்பு',
      'SOS': 'SOS',
      'Health': 'உடல்நலம்',
      'Emergency status': 'அவசர நிலை',
      'Stable': 'நிலையானது',
      'Emergency SOS': 'அவசர SOS',
      'Today\'s health snapshot': 'இன்றைய உடல்நல சுருக்கம்',
      'Care route': 'சிகிச்சை வழி',
      'Medicine reminder': 'மருந்து நினைவூட்டல்',
      'AI Health Assistant': 'AI உடல்நல உதவியாளர்',
      'Caregiver settings': 'பராமரிப்பாளர் அமைப்புகள்',
      'Sign out': 'வெளியேறு',
      'Medicine name': 'மருந்தின் பெயர்',
      'Time': 'நேரம்',
      'Submit reminder': 'நினைவூட்டலைச் சமர்ப்பி',
      'Enter medicine and time': 'மருந்து மற்றும் நேரத்தை உள்ளிடவும்',
      'Reminder saved': 'நினைவூட்டல் சேமிக்கப்பட்டது',
      'Delete reminder': 'நினைவூட்டலை நீக்கு',
      'Get guidance': 'வழிகாட்டுதலைப் பெறு',
      'Blood group': 'இரத்த வகை',
      'Allergies': 'ஒவ்வாமைகள்',
      'Contact': 'தொடர்பு',
      'Voice input': 'குரல் உள்ளீடு',
      'Guidance summary': 'வழிகாட்டுதல் சுருக்கம்',
      'Send SOS Now': 'இப்போது SOS அனுப்பு',
      'Nearby healthcare services': 'அருகிலுள்ள சுகாதார சேவைகள்',
      'Save record': 'பதிவைச் சேமி',
      'Saving...': 'சேமிக்கிறது...',
      'Today': 'இன்று',
      'Weight': 'எடை',
      'Height': 'உயரம்',
      'Not set': 'அமைக்கப்படவில்லை',
      'None': 'இல்லை',
      'Screen time today': 'இன்றைய திரை நேரம்',
      'hours': 'மணி',
      'Emergency contact': 'அவசர தொடர்பு',
      'Edit emergency contact': 'அவசர தொடர்பைத் திருத்து',
      'Call Emergency Contact': 'அவசர தொடர்பை அழை',
      'Enter data': 'தரவை உள்ளிடு',
      'Register as Donor': 'தானம் செய்பவராக பதிவு செய்யுங்கள்',
      'Register': 'பதிவு செய்',
      'Available Donors': 'கிடைக்கும் தானம் செய்பவர்கள்',
      'Blood Donation': 'இரத்த தானம்',
      'Describe your symptoms and Medly will suggest basic guidance and urgency levels.':
          'உங்கள் அறிகுறிகளை விவரிக்கவும்; Medly அடிப்படை வழிகாட்டுதலையும் அவசர நிலைகளையும் பரிந்துரைக்கும்.',
      'Describe your symptoms or ask for first aid guidance':
          'உங்கள் அறிகுறிகளை விவரிக்கவும் அல்லது முதலுதவி வழிகாட்டுதலைக் கேட்கவும்',
    },
    'Telugu': {
      'Caregiver Access': 'సంరక్షకుని ప్రవేశం',
      'Continue': 'కొనసాగించండి',
      'Create account': 'ఖాతా సృష్టించండి',
      'Home': 'హోమ్',
      'SOS': 'SOS',
      'Health': 'ఆరోగ్యం',
      'Emergency status': 'అత్యవసర స్థితి',
      'Stable': 'స్థిరంగా ఉంది',
      'Emergency SOS': 'అత్యవసర SOS',
      'Today\'s health snapshot': 'నేటి ఆరోగ్య సారాంశం',
      'Care route': 'సంరక్షణ మార్గం',
      'Medicine reminder': 'మందుల రిమైండర్',
      'AI Health Assistant': 'AI ఆరోగ్య సహాయకుడు',
      'Caregiver settings': 'సంరక్షకుని సెట్టింగ్‌లు',
      'Sign out': 'సైన్ అవుట్',
      'Medicine name': 'మందు పేరు',
      'Time': 'సమయం',
      'Submit reminder': 'రిమైండర్ సమర్పించండి',
      'Enter medicine and time': 'మందు మరియు సమయం నమోదు చేయండి',
      'Reminder saved': 'రిమైండర్ సేవ్ చేయబడింది',
      'Delete reminder': 'రిమైండర్ తొలగించండి',
      'Get guidance': 'మార్గదర్శకత్వం పొందండి',
      'Blood group': 'రక్తం గ్రూప్',
      'Allergies': 'అలెర్జీలు',
      'Contact': 'సంప్రదించండి',
      'Voice input': 'వాయిస్ ఇన్‌పుట్',
      'Guidance summary': 'మార్గదర్శక సారాంశం',
      'Send SOS Now': 'ఇప్పుడు SOS పంపండి',
      'Nearby healthcare services': 'సమీప ఆరోగ్య సేవలు',
      'Save record': 'రికార్డును సేవ్ చేయండి',
      'Saving...': 'సేవ్ అవుతోంది...',
      'Today': 'ఈరోజు',
      'Weight': 'బరువు',
      'Height': 'ఎత్తు',
      'Not set': 'సెట్ చేయబడలేదు',
      'None': 'ఏదీ లేదు',
      'Screen time today': 'ఈరోజు స్క్రీన్ సమయం',
      'hours': 'గంటలు',
      'Emergency contact': 'అత్యవసర సంప్రదింపు',
      'Edit emergency contact': 'అత్యవసర సంప్రదింపును సవరించండి',
      'Call Emergency Contact': 'అత్యవసర సంప్రదింపును కాల్ చేయండి',
      'Enter data': 'డేటా నమోదు చేయండి',
      'Register as Donor': 'దాతగా నమోదు చేయండి',
      'Register': 'నమోదు చేయండి',
      'Available Donors': 'అందుబాటులో ఉన్న దాతలు',
      'Blood Donation': 'రక్తదానం',
      'Describe your symptoms or ask for first aid guidance':
          'మీ లక్షణాలను వివరించండి లేదా ప్రథమ చికిత్స మార్గదర్శకత్వం అడగండి',
    },
    'Kannada': {
      'Caregiver Access': 'ಪಾಲಕರ ಪ್ರವೇಶ',
      'Continue': 'ಮುಂದುವರಿಸಿ',
      'Create account': 'ಖಾತೆ ರಚಿಸಿ',
      'Home': 'ಮುಖಪುಟ',
      'SOS': 'SOS',
      'Health': 'ಆರೋಗ್ಯ',
      'Emergency status': 'ತುರ್ತು ಸ್ಥಿತಿ',
      'Stable': 'ಸ್ಥಿರ',
      'Emergency SOS': 'ತುರ್ತು SOS',
      'Today\'s health snapshot': 'ಇಂದಿನ ಆರೋಗ್ಯ ಸಾರಾಂಶ',
      'Care route': 'ಆರೈಕೆ ಮಾರ್ಗ',
      'Medicine reminder': 'ಔಷಧಿ ಜ್ಞಾಪನೆ',
      'AI Health Assistant': 'AI ಆರೋಗ್ಯ ಸಹಾಯಕ',
      'Caregiver settings': 'ಪಾಲಕರ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
      'Sign out': 'ಸೈನ್ ಔಟ್',
      'Medicine name': 'ಔಷಧಿಯ ಹೆಸರು',
      'Time': 'ಸಮಯ',
      'Submit reminder': 'ಜ್ಞಾಪನೆ ಸಲ್ಲಿಸಿ',
      'Enter medicine and time': 'ಔಷಧಿ ಮತ್ತು ಸಮಯ ನಮೂದಿಸಿ',
      'Reminder saved': 'ಜ್ಞಾಪನೆ ಉಳಿಸಲಾಗಿದೆ',
      'Delete reminder': 'ಜ್ಞಾಪನೆ ಅಳಿಸಿ',
      'Get guidance': 'ಮಾರ್ಗದರ್ಶನ ಪಡೆಯಿರಿ',
      'Blood group': 'ರಕ್ತದ ಗುಂಪು',
      'Allergies': 'ಅಲರ್ಜಿ',
      'Contact': 'ಸಂಪರ್ಕ',
      'Voice input': 'ಧ್ವನಿ ಇನ್‌ಪುಟ್',
      'Guidance summary': 'ಮಾರ್ಗದರ್ಶನ ಸಾರಾಂಶ',
      'Send SOS Now': 'ಈಗ SOS ಕಳುಹಿಸಿ',
      'Nearby healthcare services': 'ಹತ್ತಿರದ ಆರೋಗ್ಯ ಸೇವೆಗಳು',
      'Save record': 'ದಾಖಲೆ ಉಳಿಸಿ',
      'Saving...': 'ಉಳಿಸಲಾಗುತ್ತಿದೆ...',
      'Today': 'ಇಂದು',
      'Weight': 'ತೂಕ',
      'Height': 'ಎತ್ತರ',
      'Not set': 'ಸೆಟ್ ಮಾಡಿಲ್ಲ',
      'None': 'ಯಾವುದೂ ಇಲ್ಲ',
      'Screen time today': 'ಇಂದಿನ ಸ್ಕ್ರೀನ್ ಸಮಯ',
      'hours': 'ಗಂಟೆಗಳು',
      'Emergency contact': 'ತುರ್ತು ಸಂಪರ್ಕ',
      'Edit emergency contact': 'ತುರ್ತು ಸಂಪರ್ಕವನ್ನು ಸಂಪಾದಿಸಿ',
      'Call Emergency Contact': 'ತುರ್ತು ಸಂಪರ್ಕವನ್ನು ಕರೆಯಿರಿ',
      'Enter data': 'ಡೇಟಾ ನಮೂದಿಸಿ',
      'Register as Donor': 'ದಾತರಾಗಿ ನೋಂದಾಯಿಸಿ',
      'Register': 'ನೋಂದಾಯಿಸಿ',
      'Available Donors': 'ಲಭ್ಯವಿರುವ ದಾತರು',
      'Blood Donation': 'ರಕ್ತದಾನ',
      'Describe your symptoms or ask for first aid guidance':
          'ನಿಮ್ಮ ಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ ಅಥವಾ ಪ್ರಥಮ ಚಿಕಿತ್ಸೆ ಮಾರ್ಗದರ್ಶನ ಕೇಳಿ',
    },
    'Malayalam': {
      'Caregiver Access': 'പരിചാരക പ്രവേശനം',
      'Continue': 'തുടരുക',
      'Create account': 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
      'Home': 'ഹോം',
      'SOS': 'SOS',
      'Health': 'ആരോഗ്യം',
      'Emergency status': 'അടിയന്തര നില',
      'Stable': 'സ്ഥിരം',
      'Emergency SOS': 'അടിയന്തര SOS',
      'Today\'s health snapshot': 'ഇന്നത്തെ ആരോഗ്യ സംഗ്രഹം',
      'Care route': 'പരിചരണ വഴി',
      'Medicine reminder': 'മരുന്ന് ഓർമ്മപ്പെടുത്തൽ',
      'AI Health Assistant': 'AI ആരോഗ്യ സഹായി',
      'Caregiver settings': 'പരിചാരക ക്രമീകരണങ്ങൾ',
      'Sign out': 'പുറത്തുകടക്കുക',
      'Medicine name': 'മരുന്നിന്റെ പേര്',
      'Time': 'സമയം',
      'Submit reminder': 'ഓർമ്മപ്പെടുത്തൽ സമർപ്പിക്കുക',
      'Enter medicine and time': 'മരുന്നും സമയവും നൽകുക',
      'Reminder saved': 'ഓർമ്മപ്പെടുത്തൽ സംരക്ഷിച്ചു',
      'Delete reminder': 'ഓർമ്മപ്പെടുത്തൽ നീക്കം ചെയ്യുക',
      'Get guidance': 'മാർഗനിർദേശം നേടുക',
      'Blood group': 'രക്തഗ്രൂപ്പ്',
      'Allergies': 'അലർജികൾ',
      'Contact': 'ബന്ധപ്പെടുക',
      'Voice input': 'വോയ്സ് ഇൻപുട്ട്',
      'Guidance summary': 'മാർഗനിർദേശ സംഗ്രഹം',
      'Send SOS Now': 'ഇപ്പോൾ SOS അയയ്ക്കുക',
      'Nearby healthcare services': 'സമീപത്തെ ആരോഗ്യ സേവനങ്ങൾ',
      'Save record': 'രേഖ സംരക്ഷിക്കുക',
      'Saving...': 'സംരക്ഷിക്കുന്നു...',
      'Today': 'ഇന്ന്',
      'Weight': 'ഭാരം',
      'Height': 'ഉയരം',
      'Not set': 'സെറ്റ് ചെയ്തിട്ടില്ല',
      'None': 'ഇല്ല',
      'Screen time today': 'ഇന്നത്തെ സ്ക്രീൻ സമയം',
      'hours': 'മണിക്കൂർ',
      'Emergency contact': 'അടിയന്തര ബന്ധം',
      'Edit emergency contact': 'അടിയന്തര ബന്ധം എഡിറ്റ് ചെയ്യുക',
      'Call Emergency Contact': 'അടിയന്തര ബന്ധം വിളിക്കുക',
      'Enter data': 'ഡേറ്റ നൽകുക',
      'Register as Donor': 'ദാതാവായി രജിസ്റ്റർ ചെയ്യുക',
      'Register': 'രജിസ്റ്റർ ചെയ്യുക',
      'Available Donors': 'ലഭ്യമായ ദാതാക്കൾ',
      'Blood Donation': 'രക്തദാനം',
      'Describe your symptoms or ask for first aid guidance':
          'നിങ്ങളുടെ ലക്ഷണങ്ങൾ വിവരിക്കുകയോ പ്രഥമശുശ്രൂഷാ മാർഗനിർദേശം ചോദിക്കുകയോ ചെയ്യുക',
    },
    'Hindi': {
      'Caregiver Access': 'देखभालकर्ता प्रवेश',
      'Continue': 'जारी रखें',
      'Create account': 'खाता बनाएं',
      'Home': 'होम',
      'SOS': 'SOS',
      'Health': 'स्वास्थ्य',
      'Emergency status': 'आपात स्थिति',
      'Stable': 'स्थिर',
      'Emergency SOS': 'आपात SOS',
      'Today\'s health snapshot': 'आज का स्वास्थ्य सारांश',
      'Care route': 'देखभाल मार्ग',
      'Medicine reminder': 'दवा अनुस्मारक',
      'AI Health Assistant': 'AI स्वास्थ्य सहायक',
      'Caregiver settings': 'देखभालकर्ता सेटिंग्स',
      'Sign out': 'साइन आउट',
      'Medicine name': 'दवा का नाम',
      'Time': 'समय',
      'Submit reminder': 'अनुस्मारक जमा करें',
      'Enter medicine and time': 'दवा और समय दर्ज करें',
      'Reminder saved': 'अनुस्मारक सहेजा गया',
      'Delete reminder': 'अनुस्मारक हटाएं',
      'Get guidance': 'मार्गदर्शन प्राप्त करें',
      'Blood group': 'रक्त समूह',
      'Allergies': 'एलर्जी',
      'Contact': 'संपर्क',
      'Voice input': 'वॉइस इनपुट',
      'Guidance summary': 'मार्गदर्शन सारांश',
      'Send SOS Now': 'अभी SOS भेजें',
      'Nearby healthcare services': 'निकटतम स्वास्थ्य सेवाएं',
      'Save record': 'रिकॉर्ड सहेजें',
      'Saving...': 'सहेजा जा रहा है...',
      'Today': 'आज',
      'Weight': 'वज़न',
      'Height': 'ऊँचाई',
      'Not set': 'सेट नहीं',
      'None': 'कोई नहीं',
      'Screen time today': 'आज का स्क्रीन समय',
      'hours': 'घंटे',
      'Emergency contact': 'आपातकालीन संपर्क',
      'Edit emergency contact': 'आपातकालीन संपर्क संपादित करें',
      'Call Emergency Contact': 'आपातकालीन संपर्क को कॉल करें',
      'Enter data': 'डेटा दर्ज करें',
      'Register as Donor': 'दाता के रूप में रजिस्टर करें',
      'Register': 'रजिस्टर करें',
      'Available Donors': 'उपलब्ध दाता',
      'Blood Donation': 'रक्तदान',
      'Describe your symptoms or ask for first aid guidance':
          'अपने लक्षण बताएं या प्राथमिक उपचार मार्गदर्शन पूछें',
    },
    'Marathi': {
      'Caregiver Access': 'देखभालकर्ता प्रवेश',
      'Continue': 'सुरू ठेवा',
      'Create account': 'खाते तयार करा',
      'Home': 'मुख्यपृष्ठ',
      'SOS': 'SOS',
      'Health': 'आरोग्य',
      'Emergency status': 'आपत्कालीन स्थिती',
      'Stable': 'स्थिर',
      'Emergency SOS': 'आपत्कालीन SOS',
      'Today\'s health snapshot': 'आजचा आरोग्य सारांश',
      'Care route': 'देखभाल मार्ग',
      'Medicine reminder': 'औषध स्मरणपत्र',
      'AI Health Assistant': 'AI आरोग्य सहाय्यक',
      'Caregiver settings': 'देखभालकर्ता सेटिंग्ज',
      'Sign out': 'साइन आउट',
      'Medicine name': 'औषधाचे नाव',
      'Time': 'वेळ',
      'Submit reminder': 'स्मरणपत्र सबमिट करा',
      'Enter medicine and time': 'औषध आणि वेळ टाका',
      'Reminder saved': 'स्मरणपत्र जतन केले',
      'Delete reminder': 'स्मरणपत्र हटवा',
      'Get guidance': 'मार्गदर्शन मिळवा',
      'Blood group': 'रक्तगट',
      'Allergies': 'अॅलर्जी',
      'Contact': 'संपर्क',
      'Voice input': 'व्हॉइस इनपुट',
      'Guidance summary': 'मार्गदर्शन सारांश',
      'Send SOS Now': 'आता SOS पाठवा',
      'Nearby healthcare services': 'जवळच्या आरोग्य सेवा',
      'Save record': 'नोंद जतन करा',
      'Saving...': 'जतन होत आहे...',
      'Today': 'आज',
      'Weight': 'वजन',
      'Height': 'उंची',
      'Not set': 'सेट केलेले नाही',
      'None': 'काही नाही',
      'Screen time today': 'आजचा स्क्रीन वेळ',
      'hours': 'तास',
      'Emergency contact': 'आपत्कालीन संपर्क',
      'Edit emergency contact': 'आपत्कालीन संपर्क संपादित करा',
      'Call Emergency Contact': 'आपत्कालीन संपर्काला कॉल करा',
      'Enter data': 'डेटा टाका',
      'Register as Donor': 'दाता म्हणून नोंदणी करा',
      'Register': 'नोंदणी करा',
      'Available Donors': 'उपलब्ध दाते',
      'Blood Donation': 'रक्तदान',
      'Describe your symptoms or ask for first aid guidance':
          'तुमची लक्षणे सांगा किंवा प्राथमिक उपचार मार्गदर्शन विचारा',
    },
    'Urdu': {
      'Caregiver Access': 'نگہداشت کنندہ رسائی',
      'Continue': 'جاری رکھیں',
      'Create account': 'اکاؤنٹ بنائیں',
      'Home': 'ہوم',
      'SOS': 'SOS',
      'Health': 'صحت',
      'Emergency status': 'ہنگامی حالت',
      'Stable': 'مستحکم',
      'Emergency SOS': 'ہنگامی SOS',
      'Today\'s health snapshot': 'آج کی صحت کا خلاصہ',
      'Care route': 'دیکھ بھال کا راستہ',
      'Medicine reminder': 'ادویات کی یاد دہانی',
      'AI Health Assistant': 'AI صحت معاون',
      'Caregiver settings': 'نگہداشت کنندہ کی ترتیبات',
      'Sign out': 'سائن آؤٹ',
      'Medicine name': 'دوا کا نام',
      'Time': 'وقت',
      'Submit reminder': 'یاد دہانی جمع کریں',
      'Enter medicine and time': 'دوا اور وقت درج کریں',
      'Reminder saved': 'یاد دہانی محفوظ ہو گئی',
      'Delete reminder': 'یاد دہانی حذف کریں',
      'Get guidance': 'رہنمائی حاصل کریں',
      'Blood group': 'بلڈ گروپ',
      'Allergies': 'الرجی',
      'Contact': 'رابطہ',
      'Voice input': 'آواز ان پٹ',
      'Guidance summary': 'رہنمائی کا خلاصہ',
      'Send SOS Now': 'ابھی SOS بھیجیں',
      'Nearby healthcare services': 'قریبی صحت کی خدمات',
      'Save record': 'ریکارڈ محفوظ کریں',
      'Saving...': 'محفوظ ہو رہا ہے...',
      'Today': 'آج',
      'Weight': 'وزن',
      'Height': 'اونچائی',
      'Not set': 'سیٹ نہیں',
      'None': 'کوئی نہیں',
      'Screen time today': 'آج کا اسکرین وقت',
      'hours': 'گھنٹے',
      'Emergency contact': 'ہنگامی رابطہ',
      'Edit emergency contact': 'ہنگامی رابطہ ترمیم کریں',
      'Call Emergency Contact': 'ہنگامی رابطہ پر کال کریں',
      'Enter data': 'ڈیٹا درج کریں',
      'Register as Donor': 'ڈونر کے طور پر رجسٹر کریں',
      'Register': 'رجسٹر کریں',
      'Available Donors': 'دستیاب ڈونرز',
      'Blood Donation': 'خون کا عطیہ',
      'Describe your symptoms or ask for first aid guidance':
          'اپنی علامات بیان کریں یا ابتدائی طبی امداد کی رہنمائی پوچھیں',
    },
    'French': {
      'Caregiver Access': 'Accès aidant',
      'Continue': 'Continuer',
      'Create account': 'Créer un compte',
      'Home': 'Accueil',
      'SOS': 'SOS',
      'Health': 'Santé',
      'Emergency status': 'État d\'urgence',
      'Stable': 'Stable',
      'Emergency SOS': 'SOS d\'urgence',
      'Today\'s health snapshot': 'Résumé santé du jour',
      'Care route': 'Parcours de soins',
      'Medicine reminder': 'Rappel de médicament',
      'AI Health Assistant': 'Assistant santé IA',
      'Caregiver settings': 'Paramètres de l\'aidant',
      'Sign out': 'Déconnexion',
      'Medicine name': 'Nom du médicament',
      'Time': 'Heure',
      'Submit reminder': 'Valider le rappel',
      'Enter medicine and time': 'Saisissez le médicament et l\'heure',
      'Reminder saved': 'Rappel enregistré',
      'Delete reminder': 'Supprimer le rappel',
      'Get guidance': 'Obtenir des conseils',
      'Blood group': 'Groupe sanguin',
      'Allergies': 'Allergies',
      'Contact': 'Contact',
      'Voice input': 'Saisie vocale',
      'Guidance summary': 'Résumé des conseils',
      'Send SOS Now': 'Envoyer le SOS',
      'Nearby healthcare services': 'Services de santé à proximité',
      'Save record': 'Enregistrer le dossier',
      'Saving...': 'Enregistrement...',
      'Today': 'Aujourd\'hui',
      'Weight': 'Poids',
      'Height': 'Taille',
      'Not set': 'Non défini',
      'None': 'Aucun',
      'Screen time today': 'Temps d\'écran aujourd\'hui',
      'hours': 'heures',
      'Emergency contact': 'Contact d\'urgence',
      'Edit emergency contact': 'Modifier le contact d\'urgence',
      'Call Emergency Contact': 'Appeler le contact d\'urgence',
      'Enter data': 'Saisir les données',
      'Register as Donor': 'S\'inscrire comme donneur',
      'Register': 'S\'inscrire',
      'Available Donors': 'Donneurs disponibles',
      'Blood Donation': 'Don du sang',
      'Describe your symptoms or ask for first aid guidance':
          'Décrivez vos symptômes ou demandez des conseils de premiers secours',
    },
    'Japanese': {
      'Caregiver Access': '介護者アクセス',
      'Continue': '続行',
      'Create account': 'アカウントを作成',
      'Home': 'ホーム',
      'SOS': 'SOS',
      'Health': '健康',
      'Emergency status': '緊急状態',
      'Stable': '安定',
      'Emergency SOS': '緊急 SOS',
      'Today\'s health snapshot': '今日の健康概要',
      'Care route': 'ケア経路',
      'Medicine reminder': '服薬リマインダー',
      'AI Health Assistant': 'AI 健康アシスタント',
      'Caregiver settings': '介護者設定',
      'Sign out': 'サインアウト',
      'Medicine name': '薬の名前',
      'Time': '時刻',
      'Submit reminder': 'リマインダーを送信',
      'Enter medicine and time': '薬と時刻を入力してください',
      'Reminder saved': 'リマインダーを保存しました',
      'Delete reminder': 'リマインダーを削除',
      'Get guidance': 'ガイダンスを取得',
      'Blood group': '血液型',
      'Allergies': 'アレルギー',
      'Contact': '連絡先',
      'Voice input': '音声入力',
      'Guidance summary': 'ガイダンス概要',
      'Send SOS Now': '今すぐ SOS を送信',
      'Nearby healthcare services': '近くの医療サービス',
      'Save record': '記録を保存',
      'Saving...': '保存中...',
      'Today': '今日',
      'Weight': '体重',
      'Height': '身長',
      'Not set': '未設定',
      'None': 'なし',
      'Screen time today': '今日のスクリーンタイム',
      'hours': '時間',
      'Emergency contact': '緊急連絡先',
      'Edit emergency contact': '緊急連絡先を編集',
      'Call Emergency Contact': '緊急連絡先に電話',
      'Enter data': 'データを入力',
      'Register as Donor': 'ドナーとして登録',
      'Register': '登録',
      'Available Donors': '利用可能なドナー',
      'Blood Donation': '献血',
      'Describe your symptoms or ask for first aid guidance':
          '症状を説明するか、応急処置の案内を尋ねてください',
    },
  };

  static const _descriptions = <String, Map<String, String>>{
    'Tamil': {
      'Walk slowly or stretch for 10 minutes. Stop if you feel unwell.':
          '10 நிமிடங்கள் மெதுவாக நடக்கவும் அல்லது நீட்டிக்கவும்.',
      'Take 5 minutes for slow, comfortable breathing.':
          '5 நிமிடங்கள் மெதுவாகவும் வசதியாகவும் சுவாசிக்கவும்.',
      'Drink water and keep fluids nearby today.':
          'தண்ணீர் குடித்து, இன்று திரவங்களை அருகில் வைத்திருக்கவும்.',
      'Vitals are within range. Keep your emergency contact and record ready.':
          'உடல்நல அளவுகள் சரியான நிலையில் உள்ளன.',
      'This may be an emergency. Call emergency services immediately, keep the person calm, and monitor breathing and pulse. If they become unresponsive, begin CPR and seek urgent care without delay.':
          'இது அவசர நிலையாக இருக்கலாம். உடனடியாக அவசர சேவைகளை அழைக்கவும்.',
      'This looks like a common illness. Encourage rest, hydration, and monitor temperature. Seek urgent assessment if symptoms worsen.':
          'இது பொதுவான நோய் போல் தெரிகிறது. ஓய்வு எடுக்கவும்.',
      'Rest in a cool, quiet place and hydrate. Avoid exertion and seek urgent care if the headache is sudden or severe.':
          'குளிர்ந்த, அமைதியான இடத்தில் ஓய்வெடுக்கவும்.',
      'Monitor symptoms closely, stay hydrated, and avoid heavy activity. Seek professional medical help if the issue worsens.':
          'அறிகுறிகளை கவனமாக கண்காணிக்கவும், தண்ணீர் குடிக்கவும்.',
    },
    'Telugu': {
      'Vitals are within range. Keep your emergency contact and record ready.':
          'ఆరోగ్య కొలతలు సాధారణ పరిధిలో ఉన్నాయి.',
      'This may be an emergency. Call emergency services immediately, keep the person calm, and monitor breathing and pulse. If they become unresponsive, begin CPR and seek urgent care without delay.':
          'ఇది అత్యవసర పరిస్థితి కావచ్చు. వెంటనే అత్యవసర సేవలను పిలవండి.',
      'This looks like a common illness. Encourage rest, hydration, and monitor temperature. Seek urgent assessment if symptoms worsen.':
          'ఇది సాధారణ అనారోగ్యంలా కనిపిస్తుంది. విశ్రాంతి తీసుకోండి.',
      'Rest in a cool, quiet place and hydrate. Avoid exertion and seek urgent care if the headache is sudden or severe.':
          'చల్లని, ప్రశాంతమైన చోట విశ్రాంతి తీసుకోండి.',
      'Monitor symptoms closely, stay hydrated, and avoid heavy activity. Seek professional medical help if the issue worsens.':
          'లక్షణాలను గమనించండి, నీరు తాగండి.',
    },
    'Kannada': {
      'Vitals are within range. Keep your emergency contact and record ready.':
          'ಆರೋಗ್ಯ ಅಳತೆಗಳು ಸಾಮಾನ್ಯ ವ್ಯಾಪ್ತಿಯಲ್ಲಿವೆ.',
      'This may be an emergency. Call emergency services immediately, keep the person calm, and monitor breathing and pulse. If they become unresponsive, begin CPR and seek urgent care without delay.':
          'ಇದು ತುರ್ತು ಪರಿಸ್ಥಿತಿಯಾಗಿರಬಹುದು. ತಕ್ಷಣ ತುರ್ತು ಸೇವೆಗಳನ್ನು ಕರೆಯಿರಿ.',
      'This looks like a common illness. Encourage rest, hydration, and monitor temperature. Seek urgent assessment if symptoms worsen.':
          'ಇದು ಸಾಮಾನ್ಯ ಅನಾರೋಗ್ಯದಂತೆ ಕಾಣುತ್ತದೆ. ವಿಶ್ರಾಂತಿ ಪಡೆಯಿರಿ.',
      'Rest in a cool, quiet place and hydrate. Avoid exertion and seek urgent care if the headache is sudden or severe.':
          'ತಂಪಾದ, ಶಾಂತವಾದ ಸ್ಥಳದಲ್ಲಿ ವಿಶ್ರಾಂತಿ ಪಡೆಯಿರಿ.',
      'Monitor symptoms closely, stay hydrated, and avoid heavy activity. Seek professional medical help if the issue worsens.':
          'ಲಕ್ಷಣಗಳನ್ನು ಗಮನಿಸಿ, ನೀರು ಕುಡಿಯಿರಿ.',
    },
    'Malayalam': {
      'Vitals are within range. Keep your emergency contact and record ready.':
          'ആരോഗ്യ അളവുകൾ സാധാരണ പരിധിയിലാണ്.',
      'This may be an emergency. Call emergency services immediately, keep the person calm, and monitor breathing and pulse. If they become unresponsive, begin CPR and seek urgent care without delay.':
          'ഇത് അടിയന്തര സാഹചര്യമാകാം. ഉടൻ അടിയന്തര സേവനങ്ങളെ വിളിക്കുക.',
      'This looks like a common illness. Encourage rest, hydration, and monitor temperature. Seek urgent assessment if symptoms worsen.':
          'ഇത് സാധാരണ അസുഖം പോലെ തോന്നുന്നു. വിശ്രമം എടുക്കുക.',
      'Rest in a cool, quiet place and hydrate. Avoid exertion and seek urgent care if the headache is sudden or severe.':
          'തണുത്ത, ശാന്തമായ സ്ഥലത്ത് വിശ്രമിക്കുക.',
      'Monitor symptoms closely, stay hydrated, and avoid heavy activity. Seek professional medical help if the issue worsens.':
          'ലക്ഷണങ്ങൾ ശ്രദ്ധിക്കുക, വെള്ളം കുടിക്കുക.',
    },
    'Hindi': {
      'Vitals are within range. Keep your emergency contact and record ready.':
          'स्वास्थ्य माप सामान्य सीमा में हैं।',
      'This may be an emergency. Call emergency services immediately, keep the person calm, and monitor breathing and pulse. If they become unresponsive, begin CPR and seek urgent care without delay.':
          'यह आपात स्थिति हो सकती है। तुरंत आपातकालीन सेवाओं को कॉल करें।',
      'This looks like a common illness. Encourage rest, hydration, and monitor temperature. Seek urgent assessment if symptoms worsen.':
          'यह सामान्य बीमारी जैसा लगता है। आराम करें।',
      'Rest in a cool, quiet place and hydrate. Avoid exertion and seek urgent care if the headache is sudden or severe.':
          'ठंडी, शांत जगह पर आराम करें।',
      'Monitor symptoms closely, stay hydrated, and avoid heavy activity. Seek professional medical help if the issue worsens.':
          'लक्षणों पर ध्यान दें, पानी पिएं।',
    },
    'Marathi': {
      'Vitals are within range. Keep your emergency contact and record ready.':
          'आरोग्य वाचा सामान्य मर्यादेत आहेत.',
      'This may be an emergency. Call emergency services immediately, keep the person calm, and monitor breathing and pulse. If they become unresponsive, begin CPR and seek urgent care without delay.':
          'हे आपत्कालीन परिस्थिती असू शकते. लगेच आपत्कालीन सेवांना कॉल करा.',
      'This looks like a common illness. Encourage rest, hydration, and monitor temperature. Seek urgent assessment if symptoms worsen.':
          'हे सामान्य आजारपणा दिसत आहे. आराम करा.',
      'Rest in a cool, quiet place and hydrate. Avoid exertion and seek urgent care if the headache is sudden or severe.':
          'थंड, शांत जागेत आराम करा.',
      'Monitor symptoms closely, stay hydrated, and avoid heavy activity. Seek professional medical help if the issue worsens.':
          'लक्षणे लक्षात ठेवा, पाणी प्या.',
    },
    'Urdu': {
      'Vitals are within range. Keep your emergency contact and record ready.':
          'صحت کے اعداد معمول کی حد میں ہیں۔',
      'This may be an emergency. Call emergency services immediately, keep the person calm, and monitor breathing and pulse. If they become unresponsive, begin CPR and seek urgent care without delay.':
          'یہ ہنگامی صورتحال ہو سکتی ہے۔ فوراً ہنگامی خدمات کو کال کریں۔',
      'This looks like a common illness. Encourage rest, hydration, and monitor temperature. Seek urgent assessment if symptoms worsen.':
          'یہ عام بیماری لگتی ہے۔ آرام کریں۔',
      'Rest in a cool, quiet place and hydrate. Avoid exertion and seek urgent care if the headache is sudden or severe.':
          'ٹھنڈی، پرسکون جگہ پر آرام کریں۔',
      'Monitor symptoms closely, stay hydrated, and avoid heavy activity. Seek professional medical help if the issue worsens.':
          'علامات پر نظر رکھیں، پانی پئیں۔',
    },
    'French': {
      'Vitals are within range. Keep your emergency contact and record ready.':
          'Les constantes sont normales.',
      'This may be an emergency. Call emergency services immediately, keep the person calm, and monitor breathing and pulse. If they become unresponsive, begin CPR and seek urgent care without delay.':
          'Ceci peut être une urgence. Appelez immédiatement les services d\'urgence.',
      'This looks like a common illness. Encourage rest, hydration, and monitor temperature. Seek urgent assessment if symptoms worsen.':
          'Cela ressemble à une maladie courante. Reposez-vous.',
      'Rest in a cool, quiet place and hydrate. Avoid exertion and seek urgent care if the headache is sudden or severe.':
          'Reposez-vous dans un endroit frais et calme.',
      'Monitor symptoms closely, stay hydrated, and avoid heavy activity. Seek professional medical help if the issue worsens.':
          'Surveillez les symptômes, hydratez-vous.',
    },
    'Japanese': {
      'Vitals are within range. Keep your emergency contact and record ready.':
          '健康指標は正常範囲です。',
      'This may be an emergency. Call emergency services immediately, keep the person calm, and monitor breathing and pulse. If they become unresponsive, begin CPR and seek urgent care without delay.':
          'これは緊急事態の可能性があります。すぐに救急サービスに電話してください。',
      'This looks like a common illness. Encourage rest, hydration, and monitor temperature. Seek urgent assessment if symptoms worsen.':
          '一般的な病気のようです。休んでください。',
      'Rest in a cool, quiet place and hydrate. Avoid exertion and seek urgent care if the headache is sudden or severe.':
          '涼しく静かな場所で休んでください。',
      'Monitor symptoms closely, stay hydrated, and avoid heavy activity. Seek professional medical help if the issue worsens.':
          '症状を注意深く確認し、水分を取り、激しい活動を避けてください。',
    },
  };

  static const _guidanceFallback = <String, String>{
    'Tamil': 'அறிகுறிகளை கவனமாக கண்காணிக்கவும், தண்ணீர் குடிக்கவும்.',
    'Telugu': 'లక్షణాలను గమనించండి, నీరు తాగండి.',
    'Kannada': 'ಲಕ್ಷಣಗಳನ್ನು ಗಮನಿಸಿ, ನೀರು ಕುಡಿಯಿರಿ.',
    'Malayalam': 'ലക്ഷണങ്ങൾ ശ്രദ്ധിക്കുക, വെള്ളം കുടിക്കുക.',
    'Hindi': 'लक्षणों पर ध्यान दें, पानी पिएं।',
    'Marathi': 'लक्षणे लक्षात ठेवा, पाणी प्या.',
    'Urdu': 'علامات پر نظر رکھیں، پانی پئیں۔',
    'French': 'Surveillez les symptômes, hydratez-vous.',
    'Japanese': '症状を注意深く確認し、水分を取り。',
  };

  String text(String key) {
    final translated =
        _translations[language]?[key] ??
        _descriptions[language]?[key] ??
        _guidanceFallback[language];
    if (translated != null && key != translated) return translated;
    return key;
  }
}
