/// Disease-based exercise service with streak tracking and badge stickers.
class ExerciseService {
  /// Maps diseases/conditions to 3 recommended daily exercises.
  static final Map<String, List<Map<String, String>>> diseaseExercises = {
    'diabetes': [
      {'name': 'Brisk Walking', 'duration': '30 min', 'icon': '🚶', 'desc': 'Walk at a moderate pace to lower blood sugar'},
      {'name': 'Chair Squats', 'duration': '15 reps x 3 sets', 'icon': '🪑', 'desc': 'Stand up and sit down slowly from a chair'},
      {'name': 'Ankle Rotations', 'duration': '10 each foot', 'icon': '🦶', 'desc': 'Rotate ankles clockwise and counter-clockwise'},
    ],
    'hypertension': [
      {'name': 'Deep Breathing', 'duration': '10 min', 'icon': '🫁', 'desc': 'Inhale 4 sec, hold 4 sec, exhale 6 sec'},
      {'name': 'Neck Stretches', 'duration': '5 min', 'icon': '🧘', 'desc': 'Slowly tilt head side to side and forward'},
      {'name': 'Walking', 'duration': '20 min', 'icon': '🚶', 'desc': 'Light walk to help lower blood pressure'},
    ],
    'asthma': [
      {'name': 'Pursed Lip Breathing', 'duration': '10 min', 'icon': '🫁', 'desc': 'Breathe in through nose, out through pursed lips'},
      {'name': 'Gentle Stretching', 'duration': '10 min', 'icon': '🧘', 'desc': 'Stretch arms, shoulders, and torso gently'},
      {'name': 'Walking', 'duration': '15 min', 'icon': '🚶', 'desc': 'Slow walk in clean air, carry inhaler'},
    ],
    'heart disease': [
      {'name': 'Seated Marching', 'duration': '10 min', 'icon': '🪑', 'desc': 'Sit and march legs alternately at a gentle pace'},
      {'name': 'Arm Circles', 'duration': '2 min each direction', 'icon': '💪', 'desc': 'Extend arms and make small circles'},
      {'name': 'Walking', 'duration': '15 min', 'icon': '🚶', 'desc': 'Slow steady walk, rest if dizzy'},
    ],
    'arthritis': [
      {'name': 'Finger Bends', 'duration': '10 reps each', 'icon': '🖐️', 'desc': 'Bend each finger to touch thumb, repeat'},
      {'name': 'Shoulder Shrugs', 'duration': '15 reps', 'icon': '🤷', 'desc': 'Raise shoulders to ears, hold 3 sec, release'},
      {'name': 'Gentle Walking', 'duration': '20 min', 'icon': '🚶', 'desc': 'Walk slowly to keep joints flexible'},
    ],
    'obesity': [
      {'name': 'Brisk Walking', 'duration': '30 min', 'icon': '🚶', 'desc': 'Fast-paced walking to burn calories'},
      {'name': 'Step-ups', 'duration': '10 each leg', 'icon': '🪜', 'desc': 'Step up and down on a low step or stair'},
      {'name': 'Standing Side Bends', 'duration': '15 each side', 'icon': '🧘', 'desc': 'Stand straight, bend torso to each side'},
    ],
    'back pain': [
      {'name': 'Cat-Cow Stretch', 'duration': '10 reps', 'icon': '🐱', 'desc': 'On all fours, arch and round your back slowly'},
      {'name': 'Knee-to-Chest', 'duration': '10 each leg', 'icon': '🦵', 'desc': 'Lie on back, pull one knee to chest, hold 20 sec'},
      {'name': 'Walking', 'duration': '20 min', 'icon': '🚶', 'desc': 'Flat-surface walk to strengthen back muscles'},
    ],
    'knee pain': [
      {'name': 'Quad Sets', 'duration': '10 reps x 3 sets', 'icon': '🦵', 'desc': 'Sit with leg straight, tighten thigh muscle'},
      {'name': 'Seated Leg Raises', 'duration': '10 each leg', 'icon': '🪑', 'desc': 'Sit and slowly straighten one leg at a time'},
      {'name': 'Gentle Walking', 'duration': '15 min', 'icon': '🚶', 'desc': 'Walk on flat surfaces, avoid stairs'},
    ],
    'thyroid': [
      {'name': 'Yoga Stretching', 'duration': '15 min', 'icon': '🧘', 'desc': 'Gentle yoga poses to boost metabolism'},
      {'name': 'Brisk Walking', 'duration': '25 min', 'icon': '🚶', 'desc': 'Moderate pace walk to manage weight'},
      {'name': 'Neck Stretches', 'duration': '5 min', 'icon': '🧘', 'desc': 'Gentle neck rotations to stimulate thyroid area'},
    ],
    'anemia': [
      {'name': 'Gentle Walking', 'duration': '15 min', 'icon': '🚶', 'desc': 'Easy walk to boost circulation'},
      {'name': 'Seated Exercises', 'duration': '10 min', 'icon': '🪑', 'desc': 'Arm raises and leg lifts while seated'},
      {'name': 'Deep Breathing', 'duration': '5 min', 'icon': '🫁', 'desc': 'Increase oxygen intake with deep breaths'},
    ],
    'migraine': [
      {'name': 'Gentle Neck Rolls', 'duration': '5 min', 'icon': '🧘', 'desc': 'Slow circular head movements'},
      {'name': 'Shoulder Shrugs', 'duration': '10 reps', 'icon': '🤷', 'desc': 'Relieve tension in shoulders and neck'},
      {'name': 'Walking', 'duration': '15 min', 'icon': '🚶', 'desc': 'Outdoor walk in fresh air'},
    ],
    'cholesterol': [
      {'name': 'Brisk Walking', 'duration': '30 min', 'icon': '🚶', 'desc': 'Cardio exercise to improve cholesterol levels'},
      {'name': 'Cycling', 'duration': '20 min', 'icon': '🚴', 'desc': 'Stationary or outdoor cycling'},
      {'name': 'Jumping Jacks', 'duration': '20 reps x 3 sets', 'icon': '⭐', 'desc': 'Modified or low-impact version if needed'},
    ],
    'stress': [
      {'name': 'Meditation', 'duration': '10 min', 'icon': '🧘', 'desc': 'Sit quietly and focus on breathing'},
      {'name': 'Yoga', 'duration': '15 min', 'icon': '🧘', 'desc': 'Simple yoga poses for relaxation'},
      {'name': 'Walking', 'duration': '20 min', 'icon': '🚶', 'desc': 'Nature walk to clear the mind'},
    ],
    'insomnia': [
      {'name': 'Gentle Stretching', 'duration': '10 min', 'icon': '🧘', 'desc': 'Before bed stretches to relax the body'},
      {'name': 'Deep Breathing', 'duration': '10 min', 'icon': '🫁', 'desc': '4-7-8 breathing technique before sleep'},
      {'name': 'Walking', 'duration': '15 min', 'icon': '🚶', 'desc': 'Evening walk to tire the body gently'},
    ],
    'constipation': [
      {'name': 'Walking', 'duration': '30 min', 'icon': '🚶', 'desc': 'Regular walking aids digestion'},
      {'name': 'Abdominal Massage', 'duration': '5 min', 'icon': '💆', 'desc': 'Clockwise circular massage on belly'},
      {'name': 'Knee-to-Chest', 'duration': '10 reps', 'icon': '🦵', 'desc': 'Lie down, pull knees to chest alternately'},
    ],
    'thyroid': [
      {'name': 'Yoga', 'duration': '15 min', 'icon': '🧘', 'desc': 'Shoulder stand and fish pose for thyroid'},
      {'name': 'Brisk Walking', 'duration': '25 min', 'icon': '🚶', 'desc': 'Cardio to boost metabolism'},
      {'name': 'Neck Exercises', 'duration': '5 min', 'icon': '🧘', 'desc': 'Slow neck extensions and rotations'},
    ],
    'depression': [
      {'name': 'Walking', 'duration': '30 min', 'icon': '🚶', 'desc': 'Outdoor walk boosts endorphins'},
      {'name': 'Yoga', 'duration': '15 min', 'icon': '🧘', 'desc': 'Gentle yoga for mood improvement'},
      {'name': 'Stretching', 'duration': '10 min', 'icon': '🧘', 'desc': 'Full body stretch to release tension'},
    ],
    'default': [
      {'name': 'Walking', 'duration': '30 min', 'icon': '🚶', 'desc': 'Daily walk for overall health'},
      {'name': 'Stretching', 'duration': '10 min', 'icon': '🧘', 'desc': 'Full body stretch to stay flexible'},
      {'name': 'Deep Breathing', 'duration': '5 min', 'icon': '🫁', 'desc': 'Deep breaths to reduce stress'},
    ],
  };

  /// Get exercises for a person's diseases.
  /// Returns 3 unique exercises (deduped if multiple diseases).
  static List<Map<String, String>> getExercisesForDiseases(String diseases) {
    if (diseases.isEmpty || diseases.toLowerCase() == 'none') {
      return diseaseExercises['default']!;
    }

    final diseaseList = diseases.toLowerCase().split(',').map((d) => d.trim()).toList();
    final Set<String> seen = {};
    final List<Map<String, String>> exercises = [];

    for (final disease in diseaseList) {
      // Find matching exercises
      List<Map<String, String>>? matched;
      for (final entry in diseaseExercises.entries) {
        if (disease.contains(entry.key) || entry.key.contains(disease)) {
          matched = entry.value;
          break;
        }
      }
      matched ??= diseaseExercises['default']!;

      for (final ex in matched) {
        final name = ex['name'] ?? '';
        if (!seen.contains(name) && exercises.length < 3) {
          seen.add(name);
          exercises.add(ex);
        }
      }
    }

    // Fill with defaults if less than 3
    while (exercises.length < 3) {
      for (final ex in diseaseExercises['default']!) {
        final name = ex['name'] ?? '';
        if (!seen.contains(name) && exercises.length < 3) {
          seen.add(name);
          exercises.add(ex);
        }
      }
    }

    return exercises.take(3).toList();
  }

  /// 364 unique weekly badge stickers.
  /// Each week of consecutive streaks unlocks a new sticker.
  static final List<Map<String, String>> weeklyBadges = [
    // Week 1-4: Starter badges
    {'week': '1', 'emoji': '🌟', 'name': 'First Step', 'category': 'starter'},
    {'week': '2', 'emoji': '🔥', 'name': 'On Fire', 'category': 'starter'},
    {'week': '3', 'emoji': '💪', 'name': 'Getting Strong', 'category': 'starter'},
    {'week': '4', 'emoji': '🎯', 'name': 'Target Hit', 'category': 'starter'},
    // Week 5-8: Dogs
    {'week': '5', 'emoji': '🐕', 'name': 'Happy Pup', 'category': 'dogs'},
    {'week': '6', 'emoji': '🦮', 'name': 'Guide Dog', 'category': 'dogs'},
    {'week': '7', 'emoji': '🐶', 'name': 'Puppy Love', 'category': 'dogs'},
    {'week': '8', 'emoji': '🐾', 'name': 'Paw Print', 'category': 'dogs'},
    {'week': '9', 'emoji': '🐕‍🦺', 'name': 'Working Dog', 'category': 'dogs'},
    {'week': '10', 'emoji': '🦴', 'name': 'Bone Collector', 'category': 'dogs'},
    {'week': '11', 'emoji': 'FETCH', 'name': 'Fetch Master', 'category': 'dogs'},
    {'week': '12', 'emoji': '🐕', 'name': 'Best Friend', 'category': 'dogs'},
    // Week 13-24: Cats
    {'week': '13', 'emoji': '🐱', 'name': 'Curious Kitty', 'category': 'cats'},
    {'week': '14', 'emoji': '😺', 'name': 'Grinning Cat', 'category': 'cats'},
    {'week': '15', 'emoji': '😸', 'name': 'Happy Cat', 'category': 'cats'},
    {'week': '16', 'emoji': '😹', 'name': 'LOL Cat', 'category': 'cats'},
    {'week': '17', 'emoji': '😻', 'name': 'Heart Eyes', 'category': 'cats'},
    {'week': '18', 'emoji': '😼', 'name': 'Sly Cat', 'category': 'cats'},
    {'week': '19', 'emoji': '😽', 'name': 'Kiss Cat', 'category': 'cats'},
    {'week': '20', 'emoji': '🙀', 'name': 'Shocked Cat', 'category': 'cats'},
    {'week': '21', 'emoji': '😿', 'name': 'Sad Cat', 'category': 'cats'},
    {'week': '22', 'emoji': '😾', 'name': 'Grumpy Cat', 'category': 'cats'},
    {'week': '23', 'emoji': '🐾', 'name': 'Cat Paw', 'category': 'cats'},
    {'week': '24', 'emoji': '🐈', 'name': 'Elegant Cat', 'category': 'cats'},
    {'week': '25', 'emoji': '🐈‍⬛', 'name': 'Black Cat', 'category': 'cats'},
    {'week': '26', 'emoji': '🐱', 'name': 'Nap Time', 'category': 'cats'},
    // Week 27-40: Animals
    {'week': '27', 'emoji': '🦁', 'name': 'Lion Heart', 'category': 'animals'},
    {'week': '28', 'emoji': '🐯', 'name': 'Tiger Power', 'category': 'animals'},
    {'week': '29', 'emoji': '🐘', 'name': 'Elephant Wise', 'category': 'animals'},
    {'week': '30', 'emoji': '🐼', 'name': 'Panda Zen', 'category': 'animals'},
    {'week': '31', 'emoji': '🦊', 'name': 'Clever Fox', 'category': 'animals'},
    {'week': '32', 'emoji': '🐸', 'name': 'Leap Frog', 'category': 'animals'},
    {'week': '33', 'emoji': '🦋', 'name': 'Butterfly', 'category': 'animals'},
    {'week': '34', 'emoji': '🐝', 'name': 'Busy Bee', 'category': 'animals'},
    {'week': '35', 'emoji': '🐬', 'name': 'Dolphin Joy', 'category': 'animals'},
    {'week': '36', 'emoji': '🐋', 'name': 'Whale Song', 'category': 'animals'},
    {'week': '37', 'emoji': '🦅', 'name': 'Eagle Eye', 'category': 'animals'},
    {'week': '38', 'emoji': '🦉', 'name': 'Wise Owl', 'category': 'animals'},
    {'week': '39', 'emoji': '🦩', 'name': 'Flamingo', 'category': 'animals'},
    {'week': '40', 'emoji': '🦜', 'name': 'Parrot Talk', 'category': 'animals'},
    {'week': '41', 'emoji': '🐧', 'name': 'Penguin Waddle', 'category': 'animals'},
    {'week': '42', 'emoji': '🦘', 'name': 'Kangaroo Hop', 'category': 'animals'},
    {'week': '43', 'emoji': '🦈', 'name': 'Shark Strength', 'category': 'animals'},
    {'week': '44', 'emoji': '🐢', 'name': 'Turtle Pace', 'category': 'animals'},
    // Week 45-52: Anime
    {'week': '45', 'emoji': '⚔️', 'name': 'Sword Master', 'category': 'anime'},
    {'week': '46', 'emoji': '🍥', 'name': 'Naruto Ramen', 'category': 'anime'},
    {'week': '47', 'emoji': '🔥', 'name': 'Dragon Flame', 'category': 'anime'},
    {'week': '48', 'emoji': '⭐', 'name': 'Star Power', 'category': 'anime'},
    {'week': '49', 'emoji': '🎭', 'name': 'Mask Hero', 'category': 'anime'},
    {'week': '50', 'emoji': '🌸', 'name': 'Cherry Blossom', 'category': 'anime'},
    {'week': '51', 'emoji': '🎨', 'name': 'Artist Soul', 'category': 'anime'},
    {'week': '52', 'emoji': '🏆', 'name': 'Champion', 'category': 'anime'},
    // Week 53-65: Web Series
    {'week': '53', 'emoji': '📺', 'name': 'Binge Watcher', 'category': 'webseries'},
    {'week': '54', 'emoji': '🎬', 'name': 'Movie Night', 'category': 'webseries'},
    {'week': '55', 'emoji': '🍿', 'name': 'Popcorn Time', 'category': 'webseries'},
    {'week': '56', 'emoji': '🎪', 'name': 'Circus Star', 'category': 'webseries'},
    {'week': '57', 'emoji': '🎸', 'name': 'Rock Star', 'category': 'webseries'},
    {'week': '58', 'emoji': '🎤', 'name': 'Mic Drop', 'category': 'webseries'},
    {'week': '59', 'emoji': '🥁', 'name': 'Drum Roll', 'category': 'webseries'},
    {'week': '60', 'emoji': '🎹', 'name': 'Piano Pro', 'category': 'webseries'},
    {'week': '61', 'emoji': '🎺', 'name': 'Trumpet Call', 'category': 'webseries'},
    {'week': '62', 'emoji': '🎻', 'name': 'Violin Grace', 'category': 'webseries'},
    {'week': '63', 'emoji': '🪗', 'name': 'Accordion Joy', 'category': 'webseries'},
    {'week': '64', 'emoji': '🪘', 'name': 'Drum Beat', 'category': 'webseries'},
    {'week': '65', 'emoji': '🎵', 'name': 'Music Note', 'category': 'webseries'},
    // Week 66-80: Nature
    {'week': '66', 'emoji': '🌍', 'name': 'Earth Guardian', 'category': 'nature'},
    {'week': '67', 'emoji': '🌎', 'name': 'World Traveler', 'category': 'nature'},
    {'week': '68', 'emoji': '🌏', 'name': 'Asia Explorer', 'category': 'nature'},
    {'week': '69', 'emoji': '🌿', 'name': 'Green Thumb', 'category': 'nature'},
    {'week': '70', 'emoji': '🍀', 'name': 'Lucky Clover', 'category': 'nature'},
    {'week': '71', 'emoji': '🌱', 'name': 'Seedling', 'category': 'nature'},
    {'week': '72', 'emoji': '🌲', 'name': 'Tree Hugger', 'category': 'nature'},
    {'week': '73', 'emoji': '🌳', 'name': 'Oak Strong', 'category': 'nature'},
    {'week': '74', 'emoji': '🌴', 'name': 'Palm Paradise', 'category': 'nature'},
    {'week': '75', 'emoji': '🌵', 'name': 'Desert Rose', 'category': 'nature'},
    {'week': '76', 'emoji': '🍄', 'name': 'Mushroom Magic', 'category': 'nature'},
    {'week': '77', 'emoji': '🌾', 'name': 'Harvest Moon', 'category': 'nature'},
    {'week': '78', 'emoji': '🌺', 'name': 'Hibiscus', 'category': 'nature'},
    {'week': '79', 'emoji': '🌻', 'name': 'Sunflower', 'category': 'nature'},
    {'week': '80', 'emoji': '🌹', 'name': 'Rose Bud', 'category': 'nature'},
    // Week 81-95: Sports
    {'week': '81', 'emoji': '⚽', 'name': 'Goal!', 'category': 'sports'},
    {'week': '82', 'emoji': '🏀', 'name': 'Slam Dunk', 'category': 'sports'},
    {'week': '83', 'emoji': '🏈', 'name': 'Touchdown', 'category': 'sports'},
    {'week': '84', 'emoji': '⚾', 'name': 'Home Run', 'category': 'sports'},
    {'week': '85', 'emoji': '🎾', 'name': 'Ace Serve', 'category': 'sports'},
    {'week': '86', 'emoji': '🏐', 'name': 'Spike!', 'category': 'sports'},
    {'week': '87', 'emoji': '🏉', 'name': 'Rugby Rush', 'category': 'sports'},
    {'week': '88', 'emoji': '🎱', 'name': 'Pool Shark', 'category': 'sports'},
    {'week': '89', 'emoji': '🏓', 'name': 'Ping Pong', 'category': 'sports'},
    {'week': '90', 'emoji': '🏸', 'name': 'Shuttle Drop', 'category': 'sports'},
    {'week': '91', 'emoji': '🥊', 'name': 'Boxer', 'category': 'sports'},
    {'week': '92', 'emoji': '🥋', 'name': 'Karate Kid', 'category': 'sports'},
    {'week': '93', 'emoji': '🎯', 'name': 'Bullseye', 'category': 'sports'},
    {'week': '94', 'emoji': '🏹', 'name': 'Archer', 'category': 'sports'},
    {'week': '95', 'emoji': '🏋️', 'name': 'Heavy Lifter', 'category': 'sports'},
    // Week 96-110: Food
    {'week': '96', 'emoji': '🍎', 'name': 'Apple A Day', 'category': 'food'},
    {'week': '97', 'emoji': '🍊', 'name': 'Orange Zest', 'category': 'food'},
    {'week': '98', 'emoji': '🍋', 'name': 'Lemon Fresh', 'category': 'food'},
    {'week': '99', 'emoji': '🍇', 'name': 'Grape Vine', 'category': 'food'},
    {'week': '100', 'emoji': '🍓', 'name': 'Strawberry', 'category': 'food'},
    {'week': '101', 'emoji': '🫐', 'name': 'Blueberry', 'category': 'food'},
    {'week': '102', 'emoji': '🥝', 'name': 'Kiwi Sprint', 'category': 'food'},
    {'week': '103', 'emoji': '🍑', 'name': 'Peachy', 'category': 'food'},
    {'week': '104', 'emoji': '🍒', 'name': 'Cherry Pick', 'category': 'food'},
    {'week': '105', 'emoji': '🥑', 'name': 'Avocado', 'category': 'food'},
    {'week': '106', 'emoji': '🥕', 'name': 'Carrot Crunch', 'category': 'food'},
    {'week': '107', 'emoji': '🥦', 'name': 'Broccoli Boss', 'category': 'food'},
    {'week': '108', 'emoji': '🌽', 'name': 'Corn Star', 'category': 'food'},
    {'week': '109', 'emoji': '🍞', 'name': 'Bread Winner', 'category': 'food'},
    {'week': '110', 'emoji': '🧀', 'name': 'Cheese Please', 'category': 'food'},
    // Week 111-125: Space
    {'week': '111', 'emoji': '🚀', 'name': 'Rocket Launch', 'category': 'space'},
    {'week': '112', 'emoji': '🛸', 'name': 'UFO Sighting', 'category': 'space'},
    {'week': '113', 'emoji': '🌙', 'name': 'Moon Walker', 'category': 'space'},
    {'week': '114', 'emoji': '⭐', 'name': 'Star Gazer', 'category': 'space'},
    {'week': '115', 'emoji': '🌟', 'name': 'Bright Star', 'category': 'space'},
    {'week': '116', 'emoji': '✨', 'name': 'Sparkle', 'category': 'space'},
    {'week': '117', 'emoji': '💫', 'name': 'Dizzy Star', 'category': 'space'},
    {'week': '118', 'emoji': '🌠', 'name': 'Shooting Star', 'category': 'space'},
    {'week': '119', 'emoji': '🌌', 'name': 'Galaxy', 'category': 'space'},
    {'week': '120', 'emoji': '☀️', 'name': 'Sunshine', 'category': 'space'},
    {'week': '121', 'emoji': '🌈', 'name': 'Rainbow', 'category': 'space'},
    {'week': '122', 'emoji': '⚡', 'name': 'Lightning', 'category': 'space'},
    {'week': '123', 'emoji': '🔥', 'name': 'Fire Power', 'category': 'space'},
    {'week': '124', 'emoji': '❄️', 'name': 'Ice Cold', 'category': 'space'},
    {'week': '125', 'emoji': '💨', 'name': 'Wind Rush', 'category': 'space'},
    // Week 126-140: Vehicles
    {'week': '126', 'emoji': '🚗', 'name': 'Road Trip', 'category': 'vehicles'},
    {'week': '127', 'emoji': '🏎️', 'name': 'Speed Racer', 'category': 'vehicles'},
    {'week': '128', 'emoji': '🚜', 'name': 'Farm Fresh', 'category': 'vehicles'},
    {'week': '129', 'emoji': '🛩️', 'name': 'Sky High', 'category': 'vehicles'},
    {'week': '130', 'emoji': '🚁', 'name': 'Helicopter', 'category': 'vehicles'},
    {'week': '131', 'emoji': '🚂', 'name': 'Choo Choo', 'category': 'vehicles'},
    {'week': '132', 'emoji': '🚀', 'name': 'Blast Off', 'category': 'vehicles'},
    {'week': '133', 'emoji': '🛴', 'name': 'Scooter Zoom', 'category': 'vehicles'},
    {'week': '134', 'emoji': '🚲', 'name': 'Bicycle Belle', 'category': 'vehicles'},
    {'week': '135', 'emoji': '⛵', 'name': 'Sail Away', 'category': 'vehicles'},
    {'week': '136', 'emoji': '🛶', 'name': 'Canoe Calm', 'category': 'vehicles'},
    {'week': '137', 'emoji': '🚤', 'name': 'Speedboat', 'category': 'vehicles'},
    {'week': '138', 'emoji': '🛩️', 'name': 'Jet Set', 'category': 'vehicles'},
    {'week': '139', 'emoji': '🛸', 'name': 'Space Ship', 'category': 'vehicles'},
    {'week': '140', 'emoji': '🚎', 'name': 'Bus Buddy', 'category': 'vehicles'},
    // Week 141-160: Music
    {'week': '141', 'emoji': '🎵', 'name': 'Musical Note', 'category': 'music'},
    {'week': '142', 'emoji': '🎶', 'name': 'Music Notes', 'category': 'music'},
    {'week': '143', 'emoji': '🎤', 'name': 'Karaoke King', 'category': 'music'},
    {'week': '144', 'emoji': '🎧', 'name': 'Headphone Hero', 'category': 'music'},
    {'week': '145', 'emoji': '🎹', 'name': 'Piano Pro', 'category': 'music'},
    {'week': '146', 'emoji': '🎸', 'name': 'Guitar Hero', 'category': 'music'},
    {'week': '147', 'emoji': '🎺', 'name': 'Trumpet Star', 'category': 'music'},
    {'week': '148', 'emoji': '🎻', 'name': 'Violin Virtuoso', 'category': 'music'},
    {'week': '149', 'emoji': '🥁', 'name': 'Drum Beat', 'category': 'music'},
    {'week': '150', 'emoji': '🪘', 'name': 'Bongo Groove', 'category': 'music'},
    {'week': '151', 'emoji': '🪗', 'name': 'Accordion', 'category': 'music'},
    {'week': '152', 'emoji': '🎷', 'name': 'Sax Smooth', 'category': 'music'},
    {'week': '153', 'emoji': '🪕', 'name': 'Banjo Pluck', 'category': 'music'},
    {'week': '154', 'emoji': '🎶', 'name': 'Melody Maker', 'category': 'music'},
    {'week': '155', 'emoji': '🔊', 'name': 'Bass Drop', 'category': 'music'},
    {'week': '156', 'emoji': '🔉', 'name': 'Volume Up', 'category': 'music'},
    {'week': '157', 'emoji': '🔈', 'name': 'Soft Sound', 'category': 'music'},
    {'week': '158', 'emoji': '🎙️', 'name': 'Studio Session', 'category': 'music'},
    {'week': '159', 'emoji': '🎚️', 'name': 'Mixer Master', 'category': 'music'},
    {'week': '160', 'emoji': '🎛️', 'name': 'Control freak', 'category': 'music'},
    // Week 161-180: Seasons & Weather
    {'week': '161', 'emoji': '🌸', 'name': 'Spring Bloom', 'category': 'seasons'},
    {'week': '162', 'emoji': '☀️', 'name': 'Summer Sun', 'category': 'seasons'},
    {'week': '163', 'emoji': '🍂', 'name': 'Autumn Leaf', 'category': 'seasons'},
    {'week': '164', 'emoji': '❄️', 'name': 'Winter Snow', 'category': 'seasons'},
    {'week': '165', 'emoji': '🌧️', 'name': 'Rainy Day', 'category': 'seasons'},
    {'week': '166', 'emoji': '⛈️', 'name': 'Thunder Storm', 'category': 'seasons'},
    {'week': '167', 'emoji': '🌤️', 'name': 'Partly Sunny', 'category': 'seasons'},
    {'week': '168', 'emoji': '🌥️', 'name': 'Cloudy', 'category': 'seasons'},
    {'week': '169', 'emoji': '🌦️', 'name': 'Sun Shower', 'category': 'seasons'},
    {'week': '170', 'emoji': '🌬️', 'name': 'Windy', 'category': 'seasons'},
    {'week': '171', 'emoji': '🌪️', 'name': 'Tornado', 'category': 'seasons'},
    {'week': '172', 'emoji': '🌊', 'name': 'Tsunami', 'category': 'seasons'},
    {'week': '173', 'emoji': '🏔️', 'name': 'Mountain Top', 'category': 'seasons'},
    {'week': '174', 'emoji': '🏝️', 'name': 'Island Life', 'category': 'seasons'},
    {'week': '175', 'emoji': '🌅', 'name': 'Sunset Glow', 'category': 'seasons'},
    {'week': '176', 'emoji': '🌄', 'name': 'Sunrise Hope', 'category': 'seasons'},
    {'week': '177', 'emoji': '🌠', 'name': 'Night Sky', 'category': 'seasons'},
    {'week': '178', 'emoji': '🌅', 'name': 'Golden Hour', 'category': 'seasons'},
    {'week': '179', 'emoji': '🌃', 'name': 'City Lights', 'category': 'seasons'},
    {'week': '180', 'emoji': '🌁', 'name': 'Foggy Morning', 'category': 'seasons'},
    // Week 181-200: Professions
    {'week': '181', 'emoji': '👨‍⚕️', 'name': 'Doctor', 'category': 'professions'},
    {'week': '182', 'emoji': '👩‍⚕️', 'name': 'Nurse', 'category': 'professions'},
    {'week': '183', 'emoji': '👨‍🍳', 'name': 'Chef', 'category': 'professions'},
    {'week': '184', 'emoji': '👩‍🔧', 'name': 'Mechanic', 'category': 'professions'},
    {'week': '185', 'emoji': '👨‍🎨', 'name': 'Artist', 'category': 'professions'},
    {'week': '186', 'emoji': '👩‍🏫', 'name': 'Teacher', 'category': 'professions'},
    {'week': '187', 'emoji': '👨‍🚀', 'name': 'Astronaut', 'category': 'professions'},
    {'week': '188', 'emoji': '👩‍🔬', 'name': 'Scientist', 'category': 'professions'},
    {'week': '189', 'emoji': '👨‍💼', 'name': 'Office Hero', 'category': 'professions'},
    {'week': '190', 'emoji': '👩‍🚒', 'name': 'Firefighter', 'category': 'professions'},
    {'week': '191', 'emoji': '👨‍✈️', 'name': 'Pilot', 'category': 'professions'},
    {'week': '192', 'emoji': '👩‍⚖️', 'name': 'Justice', 'category': 'professions'},
    {'week': '193', 'emoji': '👨‍🌾', 'name': 'Farmer', 'category': 'professions'},
    {'week': '194', 'emoji': '👩‍💻', 'name': 'Coder', 'category': 'professions'},
    {'week': '195', 'emoji': '👨‍🏭', 'name': 'Builder', 'category': 'professions'},
    {'week': '196', 'emoji': '👩‍🎤', 'name': 'Rockstar', 'category': 'professions'},
    {'week': '197', 'emoji': '👨‍⚖️', 'name': 'Lawyer', 'category': 'professions'},
    {'week': '198', 'emoji': '👩‍⚕️', 'name': 'Surgeon', 'category': 'professions'},
    {'week': '199', 'emoji': '👨‍🏫', 'name': 'Professor', 'category': 'professions'},
    {'week': '200', 'emoji': '👩‍🚀', 'name': 'Space Explorer', 'category': 'professions'},
    // Week 201-220: Emotions
    {'week': '201', 'emoji': '😊', 'name': 'Happy', 'category': 'emotions'},
    {'week': '202', 'emoji': '😂', 'name': 'Laughing', 'category': 'emotions'},
    {'week': '203', 'emoji': '🥰', 'name': 'Love Struck', 'category': 'emotions'},
    {'week': '204', 'emoji': '😎', 'name': 'Cool Cat', 'category': 'emotions'},
    {'week': '205', 'emoji': '🤓', 'name': 'Nerd Alert', 'category': 'emotions'},
    {'week': '206', 'emoji': '😈', 'name': 'Devilish', 'category': 'emotions'},
    {'week': '207', 'emoji': '😇', 'name': 'Angel', 'category': 'emotions'},
    {'week': '208', 'emoji': '🤠', 'name': 'Yeehaw', 'category': 'emotions'},
    {'week': '209', 'emoji': '🥳', 'name': 'Party Time', 'category': 'emotions'},
    {'week': '210', 'emoji': '😏', 'name': 'Smirk', 'category': 'emotions'},
    {'week': '211', 'emoji': '😐', 'name': 'Meh', 'category': 'emotions'},
    {'week': '212', 'emoji': '😮', 'name': 'Wow', 'category': 'emotions'},
    {'week': '213', 'emoji': '😯', 'name': 'Surprised', 'category': 'emotions'},
    {'week': '214', 'emoji': '😲', 'name': 'Shocked', 'category': 'emotions'},
    {'week': '215', 'emoji': '🤤', 'name': 'Yummy', 'category': 'emotions'},
    {'week': '216', 'emoji': '😴', 'name': 'Sleepy', 'category': 'emotions'},
    {'week': '217', 'emoji': '😵', 'name': 'Dizzy', 'category': 'emotions'},
    {'week': '218', 'emoji': '🤯', 'name': 'Mind Blown', 'category': 'emotions'},
    {'week': '219', 'emoji': '🥳', 'name': 'Celebration', 'category': 'emotions'},
    {'week': '220', 'emoji': '🫡', 'name': 'Salute', 'category': 'emotions'},
    // Week 221-240: Medical
    {'week': '221', 'emoji': '💊', 'name': 'Pill Power', 'category': 'medical'},
    {'week': '222', 'emoji': '💉', 'name': 'Shot Fired', 'category': 'medical'},
    {'week': '223', 'emoji': '🩺', 'name': 'Check Up', 'category': 'medical'},
    {'week': '224', 'emoji': '🩹', 'name': 'Bandaid', 'category': 'medical'},
    {'week': '225', 'emoji': '🩻', 'name': 'X-Ray', 'category': 'medical'},
    {'week': '226', 'emoji': '🩼', 'name': 'Crutch', 'category': 'medical'},
    {'week': '227', 'emoji': '🧬', 'name': 'DNA', 'category': 'medical'},
    {'week': '228', 'emoji': '🔬', 'name': 'Microscope', 'category': 'medical'},
    {'week': '229', 'emoji': '🧪', 'name': 'Lab Rat', 'category': 'medical'},
    {'week': '230', 'emoji': '🩺', 'name': 'Heart Check', 'category': 'medical'},
    {'week': '231', 'emoji': '❤️', 'name': 'Healthy Heart', 'category': 'medical'},
    {'week': '232', 'emoji': '🧡', 'name': 'Orange Heart', 'category': 'medical'},
    {'week': '233', 'emoji': '💛', 'name': 'Yellow Heart', 'category': 'medical'},
    {'week': '234', 'emoji': '💚', 'name': 'Green Heart', 'category': 'medical'},
    {'week': '235', 'emoji': '💙', 'name': 'Blue Heart', 'category': 'medical'},
    {'week': '236', 'emoji': '💜', 'name': 'Purple Heart', 'category': 'medical'},
    {'week': '237', 'emoji': '🖤', 'name': 'Black Heart', 'category': 'medical'},
    {'week': '238', 'emoji': '🤍', 'name': 'White Heart', 'category': 'medical'},
    {'week': '239', 'emoji': '🤎', 'name': 'Brown Heart', 'category': 'medical'},
    {'week': '240', 'emoji': '💔', 'name': 'Broken Heart', 'category': 'medical'},
    // Week 241-260: Technology
    {'week': '241', 'emoji': '💻', 'name': 'Laptop Legend', 'category': 'tech'},
    {'week': '242', 'emoji': '🖥️', 'name': 'Desktop Dynasty', 'category': 'tech'},
    {'week': '243', 'emoji': '📱', 'name': 'Mobile Master', 'category': 'tech'},
    {'week': '244', 'emoji': '📲', 'name': 'App Attack', 'category': 'tech'},
    {'week': '245', 'emoji': '⌨️', 'name': 'Keyboard King', 'category': 'tech'},
    {'week': '246', 'emoji': '🖱️', 'name': 'Click Master', 'category': 'tech'},
    {'week': '247', 'emoji': '💾', 'name': 'Save Point', 'category': 'tech'},
    {'week': '248', 'emoji': '📀', 'name': 'Disk Jockey', 'category': 'tech'},
    {'week': '249', 'emoji': '📀', 'name': 'CD Collector', 'category': 'tech'},
    {'week': '250', 'emoji': '🔌', 'name': 'Plug In', 'category': 'tech'},
    {'week': '251', 'emoji': '🔋', 'name': 'Battery Full', 'category': 'tech'},
    {'week': '252', 'emoji': '⚡', 'name': 'Charged Up', 'category': 'tech'},
    {'week': '253', 'emoji': '📡', 'name': 'Signal Boost', 'category': 'tech'},
    {'week': '254', 'emoji': '📻', 'name': 'Radio Waves', 'category': 'tech'},
    {'week': '255', 'emoji': '📺', 'name': 'Screen Time', 'category': 'tech'},
    {'week': '256', 'emoji': '🔊', 'name': 'Sound On', 'category': 'tech'},
    {'week': '257', 'emoji': '🔉', 'name': 'Volume Up', 'category': 'tech'},
    {'week': '258', 'emoji': '🔈', 'name': 'Volume Down', 'category': 'tech'},
    {'week': '259', 'emoji': '📠', 'name': 'Fax It', 'category': 'tech'},
    {'week': '260', 'emoji': '🖨️', 'name': 'Print Master', 'category': 'tech'},
    // Week 261-280: Nature & Landscape
    {'week': '261', 'emoji': '🏔️', 'name': 'Mountain Climber', 'category': 'landscape'},
    {'week': '262', 'emoji': '🌋', 'name': 'Volcano', 'category': 'landscape'},
    {'week': '263', 'emoji': '🗻', 'name': 'Mount Fuji', 'category': 'landscape'},
    {'week': '264', 'emoji': '🏕️', 'name': 'Camper', 'category': 'landscape'},
    {'week': '265', 'emoji': '⛺', 'name': 'Tent Life', 'category': 'landscape'},
    {'week': '266', 'emoji': '🏜️', 'name': 'Desert Warrior', 'category': 'landscape'},
    {'week': '267', 'emoji': '🏖️', 'name': 'Beach Bum', 'category': 'landscape'},
    {'week': '268', 'emoji': '🌅', 'name': 'Sunset Chaser', 'category': 'landscape'},
    {'week': '269', 'emoji': '🌄', 'name': 'Sunrise Seeker', 'category': 'landscape'},
    {'week': '270', 'emoji': '🌃', 'name': 'Night Owl', 'category': 'landscape'},
    {'week': '271', 'emoji': '🌌', 'name': 'Stargazer', 'category': 'landscape'},
    {'week': '272', 'emoji': '🌠', 'name': 'Wish Upon', 'category': 'landscape'},
    {'week': '273', 'emoji': '🎆', 'name': 'Fireworks', 'category': 'landscape'},
    {'week': '274', 'emoji': '🎇', 'name': 'Sparkler', 'category': 'landscape'},
    {'week': '275', 'emoji': '🎊', 'name': 'Confetti', 'category': 'landscape'},
    {'week': '276', 'emoji': '🎉', 'name': 'Party Popper', 'category': 'landscape'},
    {'week': '277', 'emoji': '🎎', 'name': 'Doll Festival', 'category': 'landscape'},
    {'week': '278', 'emoji': '🎏', 'name': 'Carp Streamer', 'category': 'landscape'},
    {'week': '279', 'emoji': '🎐', 'name': 'Wind Chime', 'category': 'landscape'},
    {'week': '280', 'emoji': '🎑', 'name': 'Moon Viewing', 'category': 'landscape'},
    // Week 281-300: Anime Characters
    {'week': '281', 'emoji': '🦸', 'name': 'Superhero', 'category': 'anime'},
    {'week': '282', 'emoji': '🦹', 'name': 'Supervillain', 'category': 'anime'},
    {'week': '283', 'emoji': '🧙', 'name': 'Wizard', 'category': 'anime'},
    {'week': '284', 'emoji': '🧝', 'name': 'Elf Warrior', 'category': 'anime'},
    {'week': '285', 'emoji': '🧛', 'name': 'Vampire', 'category': 'anime'},
    {'week': '286', 'emoji': '🧟', 'name': 'Zombie Runner', 'category': 'anime'},
    {'week': '287', 'emoji': '🧞', 'name': 'Genie', 'category': 'anime'},
    {'week': '288', 'emoji': '🧜', 'name': 'Mermaid', 'category': 'anime'},
    {'week': '289', 'emoji': '🧚', 'name': 'Fairy', 'category': 'anime'},
    {'week': '290', 'emoji': '🎅', 'name': 'Santa', 'category': 'anime'},
    {'week': '291', 'emoji': '🤶', 'name': 'Mrs. Claus', 'category': 'anime'},
    {'week': '292', 'emoji': '🧑‍🎄', 'name': 'Christmas Elf', 'category': 'anime'},
    {'week': '293', 'emoji': '🍩', 'name': 'Donut Day', 'category': 'anime'},
    {'week': '294', 'emoji': '🍪', 'name': 'Cookie Monster', 'category': 'anime'},
    {'week': '295', 'emoji': '🎂', 'name': 'Birthday', 'category': 'anime'},
    {'week': '296', 'emoji': '🍰', 'name': 'Shortcake', 'category': 'anime'},
    {'week': '297', 'emoji': '🧁', 'name': 'Cupcake', 'category': 'anime'},
    {'week': '298', 'emoji': '🍫', 'name': 'Chocolate', 'category': 'anime'},
    {'week': '299', 'emoji': '🍬', 'name': 'Candy', 'category': 'anime'},
    {'week': '300', 'emoji': '🍭', 'name': 'Lollipop', 'category': 'anime'},
    // Week 301-320: Cute Things
    {'week': '301', 'emoji': '🧸', 'name': 'Teddy Bear', 'category': 'cute'},
    {'week': '302', 'emoji': '🎀', 'name': 'Ribbon', 'category': 'cute'},
    {'week': '303', 'emoji': '🎁', 'name': 'Gift Box', 'category': 'cute'},
    {'week': '304', 'emoji': '🎈', 'name': 'Balloon', 'category': 'cute'},
    {'week': '305', 'emoji': '🎊', 'name': 'Party Ball', 'category': 'cute'},
    {'week': '306', 'emoji': '🏮', 'name': 'Lantern', 'category': 'cute'},
    {'week': '307', 'emoji': '🎎', 'name': 'Kokeshi', 'category': 'cute'},
    {'week': '308', 'emoji': '🏮', 'name': 'Red Lantern', 'category': 'cute'},
    {'week': '309', 'emoji': '🪆', 'name': 'Nesting Doll', 'category': 'cute'},
    {'week': '310', 'emoji': '🪅', 'name': 'Piggy Bank', 'category': 'cute'},
    {'week': '311', 'emoji': '🪩', 'name': 'Disco Ball', 'category': 'cute'},
    {'week': '312', 'emoji': '🪬', 'name': 'Hamsa', 'category': 'cute'},
    {'week': '313', 'emoji': '🧸', 'name': 'Plush Pal', 'category': 'cute'},
    {'week': '314', 'emoji': '🎎', 'name': 'Daruma', 'category': 'cute'},
    {'week': '315', 'emoji': '🎏', 'name': 'Koinobori', 'category': 'cute'},
    {'week': '316', 'emoji': '🎐', 'name': 'Furin Bell', 'category': 'cute'},
    {'week': '317', 'emoji': '🏮', 'name': 'Paper Lantern', 'category': 'cute'},
    {'week': '318', 'emoji': '🪅', 'name': 'Lucky Charm', 'category': 'cute'},
    {'week': '319', 'emoji': '🪆', 'name': 'Treasure Box', 'category': 'cute'},
    {'week': '320', 'emoji': '🪩', 'name': 'Party Hat', 'category': 'cute'},
    // Week 321-340: Food & Drinks
    {'week': '321', 'emoji': '☕', 'name': 'Coffee Lover', 'category': 'drinks'},
    {'week': '322', 'emoji': '🍵', 'name': 'Tea Time', 'category': 'drinks'},
    {'week': '323', 'emoji': '🧃', 'name': 'Juice Box', 'category': 'drinks'},
    {'week': '324', 'emoji': '🥤', 'name': 'Smoothie', 'category': 'drinks'},
    {'week': '325', 'emoji': '🧋', 'name': 'Boba Tea', 'category': 'drinks'},
    {'week': '326', 'emoji': '🥛', 'name': 'Milk Drinker', 'category': 'drinks'},
    {'week': '327', 'emoji': '🍶', 'name': 'Sake', 'category': 'drinks'},
    {'week': '328', 'emoji': '🍷', 'name': 'Wine Down', 'category': 'drinks'},
    {'week': '329', 'emoji': '🍺', 'name': 'Beer Mug', 'category': 'drinks'},
    {'week': '330', 'emoji': '🍻', 'name': 'Cheers!', 'category': 'drinks'},
    {'week': '331', 'emoji': '🥂', 'name': 'Champagne', 'category': 'drinks'},
    {'week': '332', 'emoji': '🥃', 'name': 'Whiskey', 'category': 'drinks'},
    {'week': '333', 'emoji': '🍸', 'name': 'Cocktail', 'category': 'drinks'},
    {'week': '334', 'emoji': '🍹', 'name': 'Tropical', 'category': 'drinks'},
    {'week': '335', 'emoji': '🧉', 'name': 'Mate', 'category': 'drinks'},
    {'week': '336', 'emoji': '🧊', 'name': 'Ice Cube', 'category': 'drinks'},
    {'week': '337', 'emoji': '🥤', 'name': 'Soda Pop', 'category': 'drinks'},
    {'week': '338', 'emoji': '🧃', 'name': 'Energy Boost', 'category': 'drinks'},
    {'week': '339', 'emoji': '🍵', 'name': 'Matcha', 'category': 'drinks'},
    {'week': '340', 'emoji': '☕', 'name': 'Espresso', 'category': 'drinks'},
    // Week 341-364: Final stretch — rare & epic
    {'week': '341', 'emoji': '🏆', 'name': 'Trophy Winner', 'category': 'epic'},
    {'week': '342', 'emoji': '🥇', 'name': 'Gold Medal', 'category': 'epic'},
    {'week': '343', 'emoji': '🥈', 'name': 'Silver Medal', 'category': 'epic'},
    {'week': '344', 'emoji': '🥉', 'name': 'Bronze Medal', 'category': 'epic'},
    {'week': '345', 'emoji': '🎖️', 'name': 'Military Medal', 'category': 'epic'},
    {'week': '346', 'emoji': '🏅', 'name': 'Sports Medal', 'category': 'epic'},
    {'week': '347', 'emoji': '🎗️', 'name': 'Ribbon Award', 'category': 'epic'},
    {'week': '348', 'emoji': '🏵️', 'name': 'Rosette', 'category': 'epic'},
    {'week': '349', 'emoji': '💎', 'name': 'Diamond', 'category': 'epic'},
    {'week': '350', 'emoji': '👑', 'name': 'Crown', 'category': 'epic'},
    {'week': '351', 'emoji': '🤴', 'name': 'Prince', 'category': 'epic'},
    {'week': '352', 'emoji': '👸', 'name': 'Princess', 'category': 'epic'},
    {'week': '353', 'emoji': '🏰', 'name': 'Castle', 'category': 'epic'},
    {'week': '354', 'emoji': '🐉', 'name': 'Dragon Tamer', 'category': 'epic'},
    {'week': '355', 'emoji': '🦄', 'name': 'Unicorn', 'category': 'epic'},
    {'week': '356', 'emoji': '🦩', 'name': 'Phoenix Rising', 'category': 'epic'},
    {'week': '357', 'emoji': '🪽', 'name': 'Angel Wings', 'category': 'epic'},
    {'week': '358', 'emoji': '🪶', 'name': 'Feather', 'category': 'epic'},
    {'week': '359', 'emoji': '⭐', 'name': 'Legendary', 'category': 'epic'},
    {'week': '360', 'emoji': '🌟', 'name': 'Mythic', 'category': 'epic'},
    {'week': '361', 'emoji': '✨', 'name': 'Divine', 'category': 'epic'},
    {'week': '362', 'emoji': '💫', 'name': 'Cosmic', 'category': 'epic'},
    {'week': '363', 'emoji': '🌠', 'name': 'Celestial', 'category': 'epic'},
    {'week': '364', 'emoji': '🎆', 'name': 'Eternal Champion', 'category': 'epic'},
  ];

  /// Get badge for a given week number.
  static Map<String, String> getBadgeForWeek(int week) {
    final index = (week - 1).clamp(0, weeklyBadges.length - 1);
    return weeklyBadges[index];
  }
}
