import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';
import 'database_service.dart';

class HealthReportService {
  /// Generate a monthly health report PDF and share it
  static Future<void> generateAndShareReport({
    required String patientName,
    required String email,
    required String language,
  }) async {
    final pdf = pw.Document();

    // Fetch data
    final snapshots = await DatabaseService.getHealthSnapshots(patientName);
    final sosLogs = await DatabaseService.getSosLog();
    final streak = await DatabaseService.getStreak(email);
    final account = await DatabaseService.getAccount(email);

    // Get current month data
    final now = DateTime.now();
    final monthStart = DateTime(now.year, now.month, 1);
    final monthName = _getMonthName(now.month, language);

    // Filter this month's snapshots
    final monthSnapshots = snapshots.where((s) {
      final ts = s['timestamp'];
      if (ts == null) return false;
      final date = DateTime.tryParse(ts.toString());
      return date != null && date.isAfter(monthStart);
    }).toList();

    // Filter this month's SOS logs
    final monthSos = sosLogs.where((s) {
      final ts = s['timestamp'];
      if (ts == null) return false;
      final date = DateTime.tryParse(ts.toString());
      return date != null && date.isAfter(monthStart);
    }).toList();

    // Fetch medicine reminders
    final medicineReminders = await DatabaseService.getMedicineReminders();

    // Build PDF
    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(30),
        header: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  'Medly Health Report',
                  style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColor.fromHex('#2E7D32')),
                ),
                pw.Text(
                  '$monthName ${now.year}',
                  style: pw.TextStyle(fontSize: 14, color: PdfColors.grey700),
                ),
              ],
            ),
            pw.Divider(color: PdfColor.fromHex('#2E7D32'), thickness: 2),
            pw.SizedBox(height: 8),
            pw.Text('Patient: $patientName', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
            if (account != null) ...[
              pw.Text('Blood Group: ${account['blood_group'] ?? 'N/A'}', style: const pw.TextStyle(fontSize: 12)),
              pw.Text('Allergies: ${account['allergies'] ?? 'None'}', style: const pw.TextStyle(fontSize: 12)),
              pw.Text('Diseases: ${account['diseases'] ?? 'None'}', style: const pw.TextStyle(fontSize: 12)),
              pw.Text('Weight: ${account['weight'] ?? 'N/A'} kg | Height: ${account['height'] ?? 'N/A'} cm', style: const pw.TextStyle(fontSize: 12)),
            ],
            pw.SizedBox(height: 4),
            pw.Text('Generated: ${now.day}/${now.month}/${now.year} at ${now.hour}:${now.minute.toString().padLeft(2, '0')}',
                style: pw.TextStyle(fontSize: 10, color: PdfColors.grey500)),
          ],
        ),
        build: (context) => [
          // Health Snapshots Summary
          _buildSection('Health Snapshots', _getHealthSnapshotContent(monthSnapshots, language), PdfColor.fromHex('#1565C0')),

          // Blood Pressure Analysis
          _buildSection('Blood Pressure Analysis', _getBPAnalysis(monthSnapshots), PdfColor.fromHex('#C62828')),

          // Blood Sugar Analysis
          _buildSection('Blood Sugar Analysis', _getBSAnalysis(monthSnapshots), PdfColor.fromHex('#00838F')),

          // Exercise & Streak
          _buildSection('Exercise & Streak', _getExerciseContent(streak, language), PdfColor.fromHex('#6A1B9A')),

          // SOS Activity
          _buildSection('Emergency Activity', _getSosContent(monthSos, language), PdfColor.fromHex('#E65100')),

          // Medicine Reminders
          _buildMedicineSection(language, medicineReminders),

          // Footer
          pw.SizedBox(height: 20),
          pw.Divider(),
          pw.Text(
            '⚠️ This report is for informational purposes only. Consult a healthcare professional for medical advice.',
            style: pw.TextStyle(fontSize: 9, color: PdfColors.grey600, fontStyle: pw.FontStyle.italic),
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            'Generated by Medly - Smart Emergency Healthcare Assistant',
            style: pw.TextStyle(fontSize: 8, color: PdfColors.grey400),
          ),
        ],
      ),
    );

    // Save to temp directory
    final output = await getTemporaryDirectory();
    final file = File('${output.path}/Medly_Health_Report_${now.month}_${now.year}.pdf');
    await file.writeAsBytes(await pdf.save());

    // Share the PDF
    await Share.shareXFiles(
      [XFile(file.path)],
      subject: 'Medly Health Report - $monthName ${now.year}',
      text: 'Health report for $patientName - $monthName ${now.year}',
    );
  }

  static pw.Widget _buildSection(String title, List<pw.Widget> content, PdfColor color) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Container(
          padding: const pw.EdgeInsets.symmetric(vertical: 6, horizontal: 10),
          decoration: pw.BoxDecoration(
            color: color,
            borderRadius: pw.BorderRadius.circular(4),
          ),
          child: pw.Text(title, style: pw.TextStyle(color: PdfColors.white, fontWeight: pw.FontWeight.bold, fontSize: 14)),
        ),
        pw.SizedBox(height: 8),
        ...content,
        pw.SizedBox(height: 16),
      ],
    );
  }

  static List<pw.Widget> _getHealthSnapshotContent(List<Map<String, dynamic>> snapshots, String lang) {
    if (snapshots.isEmpty) {
      return [pw.Text('No health data recorded this month.', style: const pw.TextStyle(color: PdfColors.grey600))];
    }

    return [
      pw.Text('Total records: ${snapshots.length}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
      pw.SizedBox(height: 8),
      // Table of recent snapshots
      pw.TableHelper.fromTextArray(
        headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10),
        cellStyle: const pw.TextStyle(fontSize: 9),
        headerDecoration: pw.BoxDecoration(color: PdfColor.fromHex('#E3F2FD')),
        cellHeight: 24,
        headers: ['Date', 'BP', 'Sugar', 'Heart Rate', 'Sleep'],
        data: snapshots.take(15).map((s) => [
          (s['date'] ?? s['timestamp']?.toString().substring(0, 10) ?? 'N/A'),
          '${s['blood_pressure'] ?? 'N/A'}',
          '${s['blood_sugar'] ?? 'N/A'}',
          '${s['heart_rate'] ?? 'N/A'}',
          '${s['sleep_hours'] ?? 'N/A'}',
        ]).toList(),
      ),
    ];
  }

  static List<pw.Widget> _getBPAnalysis(List<Map<String, dynamic>> snapshots) {
    final bpValues = <double>[];
    for (final s in snapshots) {
      final bp = s['blood_pressure']?.toString();
      if (bp != null && bp.contains('/')) {
        final parts = bp.split('/');
        final systolic = double.tryParse(parts[0].trim());
        if (systolic != null) bpValues.add(systolic);
      }
    }

    if (bpValues.isEmpty) {
      return [pw.Text('No blood pressure data recorded.', style: const pw.TextStyle(color: PdfColors.grey600))];
    }

    final avg = bpValues.reduce((a, b) => a + b) / bpValues.length;
    final min = bpValues.reduce((a, b) => a < b ? a : b);
    final max = bpValues.reduce((a, b) => a > b ? a : b);

    String status;
    if (avg < 120) {
      status = '✅ Normal - Average systolic: ${avg.toStringAsFixed(0)} mmHg';
    } else if (avg < 140) {
      status = '⚠️ Elevated - Average systolic: ${avg.toStringAsFixed(0)} mmHg';
    } else {
      status = '🔴 High - Average systolic: ${avg.toStringAsFixed(0)} mmHg. Consult doctor.';
    }

    return [
      pw.Text('Records: ${bpValues.length}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
      pw.SizedBox(height: 4),
      pw.Text('Average: ${avg.toStringAsFixed(0)} mmHg'),
      pw.Text('Range: ${min.toStringAsFixed(0)} - ${max.toStringAsFixed(0)} mmHg'),
      pw.SizedBox(height: 4),
      pw.Text(status, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
    ];
  }

  static List<pw.Widget> _getBSAnalysis(List<Map<String, dynamic>> snapshots) {
    final bsValues = <double>[];
    for (final s in snapshots) {
      final bs = s['blood_sugar']?.toString();
      if (bs != null) {
        final val = double.tryParse(bs.replaceAll(RegExp(r'[^0-9.]'), ''));
        if (val != null) bsValues.add(val);
      }
    }

    if (bsValues.isEmpty) {
      return [pw.Text('No blood sugar data recorded.', style: const pw.TextStyle(color: PdfColors.grey600))];
    }

    final avg = bsValues.reduce((a, b) => a + b) / bsValues.length;
    final min = bsValues.reduce((a, b) => a < b ? a : b);
    final max = bsValues.reduce((a, b) => a > b ? a : b);

    String status;
    if (avg < 100) {
      status = '✅ Normal fasting - Average: ${avg.toStringAsFixed(0)} mg/dL';
    } else if (avg < 126) {
      status = '⚠️ Pre-diabetic range - Average: ${avg.toStringAsFixed(0)} mg/dL';
    } else {
      status = '🔴 Diabetic range - Average: ${avg.toStringAsFixed(0)} mg/dL. Consult doctor.';
    }

    return [
      pw.Text('Records: ${bsValues.length}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
      pw.SizedBox(height: 4),
      pw.Text('Average: ${avg.toStringAsFixed(0)} mg/dL'),
      pw.Text('Range: ${min.toStringAsFixed(0)} - ${max.toStringAsFixed(0)} mg/dL'),
      pw.SizedBox(height: 4),
      pw.Text(status, style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
    ];
  }

  static List<pw.Widget> _getExerciseContent(Map<String, dynamic>? streak, String lang) {
    if (streak == null) {
      return [pw.Text('No exercise data available.', style: const pw.TextStyle(color: PdfColors.grey600))];
    }

    final current = streak['current_streak'] ?? 0;
    final longest = streak['longest_streak'] ?? 0;
    final badges = streak['total_badges'] ?? 0;

    return [
      pw.Text('Current Streak: $current days', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 14)),
      pw.Text('Longest Streak: $longest days'),
      pw.Text('Badges Earned: $badges'),
      pw.SizedBox(height: 8),
      pw.Container(
        padding: const pw.EdgeInsets.all(8),
        decoration: pw.BoxDecoration(
          color: current >= 7 ? PdfColor.fromHex('#E8F5E9') : PdfColor.fromHex('#FFF3E0'),
          borderRadius: pw.BorderRadius.circular(4),
        ),
        child: pw.Text(
          current >= 7 ? 'Great job! You\'ve maintained a week-long streak!' : 'Keep going! Try to reach a 7-day streak.',
          style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
        ),
      ),
    ];
  }

  static List<pw.Widget> _getSosContent(List<Map<String, dynamic>> sosLogs, String lang) {
    if (sosLogs.isEmpty) {
      return [pw.Text('No emergency calls this month. ✅', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColor.fromHex('#2E7D32')))];
    }

    return [
      pw.Text('Total SOS calls: ${sosLogs.length}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
      pw.SizedBox(height: 8),
      pw.TableHelper.fromTextArray(
        headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10),
        cellStyle: const pw.TextStyle(fontSize: 9),
        headerDecoration: pw.BoxDecoration(color: PdfColor.fromHex('#FFF3E0')),
        cellHeight: 24,
        headers: ['Date', 'Contact', 'Phone'],
        data: sosLogs.map((s) => [
          s['timestamp']?.toString().substring(0, 19) ?? 'N/A',
          s['contact_name'] ?? 'Unknown',
          s['contact_phone'] ?? 'N/A',
        ]).toList(),
      ),
    ];
  }

  static pw.Widget _buildMedicineSection(String lang, List<Map<String, dynamic>> reminders) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Container(
          padding: const pw.EdgeInsets.symmetric(vertical: 6, horizontal: 10),
          decoration: pw.BoxDecoration(
            color: PdfColor.fromHex('#00695C'),
            borderRadius: pw.BorderRadius.circular(4),
          ),
          child: pw.Text('Medicine Reminders', style: pw.TextStyle(color: PdfColors.white, fontWeight: pw.FontWeight.bold, fontSize: 14)),
        ),
        pw.SizedBox(height: 8),
        if (reminders.isEmpty)
          pw.Text('No medicine reminders set.', style: const pw.TextStyle(color: PdfColors.grey600))
        else ...[
          pw.Text('Active reminders: ${reminders.length}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 4),
          ...reminders.map((r) => pw.Text('• ${r['name'] ?? 'N/A'} - ${r['time'] ?? 'N/A'}')),
        ],
        pw.SizedBox(height: 16),
      ],
    );
  }

  static String _getMonthName(int month, String lang) {
    const months = {
      'English': ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
      'Tamil': ['ஜனவரி', 'பிப்ரவரி', 'மார்ச்', 'ஏப்ரல்', 'மே', 'ஜூன்', 'ஜூலை', 'ஆகஸ்ட்', 'செப்டம்பர்', 'அக்டோபர்', 'நவம்பர்', 'டிசம்பர்'],
      'Telugu': ['జనవరి', 'ఫిబ్రవరి', 'మార్చి', 'ఏప్రిల్', 'మే', 'జూన్', 'జూలై', 'ఆగస్టు', 'సెప్టెంబర్', 'అక్టోబర్', 'నవంబర్', 'డిసెంబర్'],
      'Kannada': ['ಜನವರಿ', 'ಫೆಬ್ರವರಿ', 'ಮಾರ್ಚ್', 'ಏಪ್ರಿಲ್', 'ಮೇ', 'ಜೂನ್', 'ಜುಲೈ', 'ಆಗಸ್ಟ್', 'ಸೆಪ್ಟೆಂಬರ್', 'ಅಕ್ಟೋಬರ್', 'ನವೆಂಬರ್', 'ಡಿಸೆಂಬರ್'],
      'Malayalam': ['ജനുവരി', 'ഫെബ്രുവരി', 'മാർച്ച്', 'ഏപ്രിൽ', 'മേയ്', 'ജൂൺ', 'ജൂലൈ', 'ഓഗസ്റ്റ്', 'സെപ്റ്റംബർ', 'ഒക്ടോബർ', 'നവംബർ', 'ഡിസംബർ'],
      'Hindi': ['जनवरी', 'फरवरी', 'मार्च', 'अप्रैल', 'मई', 'जून', 'जुलाई', 'अगस्त', 'सितंबर', 'अक्टूबर', 'नवंबर', 'दिसंबर'],
      'Marathi': ['जानेवारी', 'फेब्रुवारी', 'मार्च', 'एप्रिल', 'मे', 'जून', 'जुलै', 'ऑगस्ट', 'सप्टेंबर', 'ऑक्टोबर', 'नोव्हेंबर', 'डिसेंबर'],
      'Urdu': ['جنوری', 'فروری', 'مارچ', 'اپریل', 'مئ', 'جون', 'جولائی', 'اگست', 'ستمبر', 'اکتوبر', 'نومبر', 'دسمبر'],
      'French': ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
      'Japanese': ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
    };
    return (months[lang] ?? months['English'])![month - 1];
  }
}
